# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleEntityAlignmentRule do
  @moduledoc """
  A rule that aligns specified fields with each other.

  ## Attributes

  *   `alignment_rule` (*type:* `Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule.t()`) - The alignment rule to apply to the fields.
  *   `fields` (*type:* `list(Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t())`) - The fields to be aligned.
  """

  defstruct [:alignment_rule, :fields]

  @type t :: %__MODULE__{
          alignment_rule:
            Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule.t()
            | nil,
          fields:
            list(
              Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()
            )
            | nil
        }

  @wire %{alignment_rule: "alignmentRule"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      alignment_rule:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule.decode(
          m["alignmentRule"]
        ),
      fields:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.decode(
          m["fields"]
        )
    }
  end
end
