# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField do
  @moduledoc """


  ## Attributes

  *   `default_value` (*type:* `Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant.t()`) - Default value to use if the field is not present. If the field is missing and the default value is not set, the validation run as if the field is not present in the validation logic.
  *   `field_name` (*type:* `String.t()`) - The field name to validate. This can be a simple field name or a nested field one using the ':' (meant as an aggregator) or '*' (meant as foreach) operators.
  """

  defstruct [:default_value, :field_name]

  @type t :: %__MODULE__{
          default_value:
            Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant.t()
            | nil,
          field_name: String.t() | nil
        }

  @wire %{default_value: "defaultValue", field_name: "fieldName"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      default_value:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant.decode(
          m["defaultValue"]
        ),
      field_name: m["fieldName"]
    }
  end
end
