# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleChildAlignmentRule do
  @moduledoc """
  A rule that aligns specified child fields with a parent field.

  ## Attributes

  *   `alignment_rule` (*type:* `Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule.t()`) - The alignment rule to apply to the child fields.
  *   `child_fields` (*type:* `list(Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t())`) - The child fields to be aligned within the parent field.
  *   `parent_field` (*type:* `Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()`) - The full path of the parent field.
  """

  defstruct [:alignment_rule, :child_fields, :parent_field]

  @type t :: %__MODULE__{
          alignment_rule:
            Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule.t()
            | nil,
          child_fields:
            list(
              Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()
            )
            | nil,
          parent_field:
            Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()
            | nil
        }

  @wire %{
    alignment_rule: "alignmentRule",
    child_fields: "childFields",
    parent_field: "parentField"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      alignment_rule:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule.decode(
          m["alignmentRule"]
        ),
      child_fields:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.decode(
          m["childFields"]
        ),
      parent_field:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.decode(
          m["parentField"]
        )
    }
  end
end
