# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInput do
  @moduledoc """
  Definition of the validation rules. Those are the input to the validator logic and they are used to validate a document. Next ID: 3

  ## Attributes

  *   `validation_rules` (*type:* `list(Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRule.t())`) - 
  """

  defstruct [:validation_rules]

  @type t :: %__MODULE__{
          validation_rules:
            list(
              Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRule.t()
            )
            | nil
        }

  @wire %{validation_rules: "validationRules"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      validation_rules:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRule.decode(
          m["validationRules"]
        )
    }
  end
end
