# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleFormValidationOperation do
  @moduledoc """


  ## Attributes

  *   `constants` (*type:* `list(Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant.t())`) - A list of constants to be used as operands.
  *   `fields` (*type:* `list(Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t())`) - A list of fields to be used as operands.
  *   `operation_type` (*type:* `String.t()`) - The operation type to be applied to all the operands.
  *   `operations` (*type:* `list(Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleFormValidationOperation.t())`) - A list of recursive operations to be used as operands.
  """

  defstruct [:constants, :fields, :operation_type, :operations]

  @type t :: %__MODULE__{
          constants:
            list(
              Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant.t()
            )
            | nil,
          fields:
            list(
              Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()
            )
            | nil,
          operation_type: String.t() | nil,
          operations:
            list(
              Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleFormValidationOperation.t()
            )
            | nil
        }

  @wire %{operation_type: "operationType"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      constants:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant.decode(
          m["constants"]
        ),
      fields:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.decode(
          m["fields"]
        ),
      operation_type: m["operationType"],
      operations:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleFormValidationOperation.decode(
          m["operations"]
        )
    }
  end
end
