# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleFieldOccurrences do
  @moduledoc """


  ## Attributes

  *   `field` (*type:* `Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()`) - 
  *   `max_occurrences` (*type:* `integer()`) - 
  *   `min_occurrences` (*type:* `integer()`) - Min and max occurrences of the field. If not set, there is limit set. The defined interval is a closed-closed interval, i.e. [min, max].
  """

  defstruct [:field, :max_occurrences, :min_occurrences]

  @type t :: %__MODULE__{
          field:
            Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.t()
            | nil,
          max_occurrences: integer() | nil,
          min_occurrences: integer() | nil
        }

  @wire %{max_occurrences: "maxOccurrences", min_occurrences: "minOccurrences"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      field:
        Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleField.decode(
          m["field"]
        ),
      max_occurrences: m["maxOccurrences"],
      min_occurrences: m["minOccurrences"]
    }
  end
end
