# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleConstant do
  @moduledoc """
  The constant value used in the validation rules.

  ## Attributes

  *   `float_value` (*type:* `number()`) - 
  """

  defstruct [:float_value]

  @type t :: %__MODULE__{
          float_value: number() | nil
        }

  @wire %{float_value: "floatValue"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      float_value: m["floatValue"]
    }
  end
end
