# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.CloudAiDocumentaiLabHifiaToolsValidationValidatorInputValidationRuleAlignmentRule do
  @moduledoc """
  A rule for checking field alignment. Horizontal alignment checks if fields are on the same row by comparing y-coordinates of bounding box centers, while vertical alignment checks if fields are on the same column by comparing x-coordinates of bounding box centers.

  ## Attributes

  *   `alignment_type` (*type:* `String.t()`) - 
  *   `tolerance` (*type:* `number()`) - The tolerance to use when comparing coordinates.
  """

  defstruct [:alignment_type, :tolerance]

  @type t :: %__MODULE__{
          alignment_type: String.t() | nil,
          tolerance: number() | nil
        }

  @wire %{alignment_type: "alignmentType"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      alignment_type: m["alignmentType"],
      tolerance: m["tolerance"]
    }
  end
end
