# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkChunkField do
  @moduledoc """
  The chunk field in the chunk. A chunk field could be one of the various types (for example, image, table) supported.

  ## Attributes

  *   `image_chunk_field` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkImageChunkField.t()`) - The image chunk field in the chunk.
  *   `table_chunk_field` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkTableChunkField.t()`) - The table chunk field in the chunk.
  """

  defstruct [:image_chunk_field, :table_chunk_field]

  @type t :: %__MODULE__{
          image_chunk_field:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkImageChunkField.t()
            | nil,
          table_chunk_field:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkTableChunkField.t()
            | nil
        }

  @wire %{image_chunk_field: "imageChunkField", table_chunk_field: "tableChunkField"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      image_chunk_field:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkImageChunkField.decode(
          m["imageChunkField"]
        ),
      table_chunk_field:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkTableChunkField.decode(
          m["tableChunkField"]
        )
    }
  end
end
