# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorVersionGenAiModelInfoCustomGenAiModelInfo do
  @moduledoc """
  Information for a custom Generative AI model created by the user. These are created with `Create New Version` in either the `Call foundation model` or `Fine tuning` tabs.

  ## Attributes

  *   `base_processor_version_id` (*type:* `String.t()`) - The base processor version ID for the custom model.
  *   `custom_model_type` (*type:* `String.t()`) - The type of custom model created by the user.
  """

  defstruct [:base_processor_version_id, :custom_model_type]

  @type t :: %__MODULE__{
          base_processor_version_id: String.t() | nil,
          custom_model_type: String.t() | nil
        }

  @wire %{
    base_processor_version_id: "baseProcessorVersionId",
    custom_model_type: "customModelType"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      base_processor_version_id: m["baseProcessorVersionId"],
      custom_model_type: m["customModelType"]
    }
  end
end
