# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageMatrix do
  @moduledoc """
  Representation for transformation matrix, intended to be compatible and used with OpenCV format for image manipulation.

  ## Attributes

  *   `cols` (*type:* `integer()`) - Number of columns in the matrix.
  *   `data` (*type:* `String.t()`) - The matrix data.
  *   `rows` (*type:* `integer()`) - Number of rows in the matrix.
  *   `type` (*type:* `integer()`) - This encodes information about what data type the matrix uses. For example, 0 (CV_8U) is an unsigned 8-bit image. For the full list of OpenCV primitive data types, please refer to https://docs.opencv.org/4.3.0/d1/d1b/group__core__hal__interface.html
  """

  defstruct [:cols, :data, :rows, :type]

  @type t :: %__MODULE__{
          cols: integer() | nil,
          data: String.t() | nil,
          rows: integer() | nil,
          type: integer() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      cols: m["cols"],
      data: m["data"],
      rows: m["rows"],
      type: m["type"]
    }
  end
end
