# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentBlobAsset do
  @moduledoc """
  Represents a blob asset. It's used to store the content of the inline blob in this document, for example, image bytes, such that it can be referenced by other fields in the document via asset ID.

  ## Attributes

  *   `asset_id` (*type:* `String.t()`) - Optional. The id of the blob asset.
  *   `content` (*type:* `String.t()`) - Optional. The content of the blob asset, for example, image bytes.
  *   `mime_type` (*type:* `String.t()`) - The mime type of the blob asset. An IANA published [media type (MIME type)](https://www.iana.org/assignments/media-types/media-types.xhtml).
  """

  defstruct [:asset_id, :content, :mime_type]

  @type t :: %__MODULE__{
          asset_id: String.t() | nil,
          content: String.t() | nil,
          mime_type: String.t() | nil
        }

  @wire %{asset_id: "assetId", mime_type: "mimeType"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      asset_id: m["assetId"],
      content: m["content"],
      mime_type: m["mimeType"]
    }
  end
end
