# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3BatchProcessMetadataIndividualProcessStatus do
  @moduledoc """
  The status of a each individual document in the batch process.

  ## Attributes

  *   `human_review_operation` (*type:* `String.t()`) - The name of the operation triggered by the processed document. If the human review process isn't triggered, this field will be empty. It has the same response type and metadata as the long-running operation returned by the ReviewDocument method.
  *   `human_review_status` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3HumanReviewStatus.t()`) - The status of human review on the processed document.
  *   `input_gcs_source` (*type:* `String.t()`) - The source of the document, same as the input_gcs_source field in the request when the batch process started.
  *   `output_gcs_destination` (*type:* `String.t()`) - The Cloud Storage output destination (in the request as DocumentOutputConfig.GcsOutputConfig.gcs_uri) of the processed document if it was successful, otherwise empty.
  *   `status` (*type:* `Googly.DocumentAI.Model.GoogleRpcStatus.t()`) - The status processing the document.
  """

  defstruct [
    :human_review_operation,
    :human_review_status,
    :input_gcs_source,
    :output_gcs_destination,
    :status
  ]

  @type t :: %__MODULE__{
          human_review_operation: String.t() | nil,
          human_review_status:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3HumanReviewStatus.t() | nil,
          input_gcs_source: String.t() | nil,
          output_gcs_destination: String.t() | nil,
          status: Googly.DocumentAI.Model.GoogleRpcStatus.t() | nil
        }

  @wire %{
    human_review_operation: "humanReviewOperation",
    human_review_status: "humanReviewStatus",
    input_gcs_source: "inputGcsSource",
    output_gcs_destination: "outputGcsDestination"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      human_review_operation: m["humanReviewOperation"],
      human_review_status:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3HumanReviewStatus.decode(
          m["humanReviewStatus"]
        ),
      input_gcs_source: m["inputGcsSource"],
      output_gcs_destination: m["outputGcsDestination"],
      status: Googly.DocumentAI.Model.GoogleRpcStatus.decode(m["status"])
    }
  end
end
