# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3EvaluateProcessorVersionMetadata do
  @moduledoc """
  Metadata of the EvaluateProcessorVersion method.

  ## Attributes

  *   `common_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3CommonOperationMetadata.t()`) - The basic metadata of the long-running operation.
  """

  defstruct [:common_metadata]

  @type t :: %__MODULE__{
          common_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3CommonOperationMetadata.t() | nil
        }

  @wire %{common_metadata: "commonMetadata"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      common_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3CommonOperationMetadata.decode(
          m["commonMetadata"]
        )
    }
  end
end
