# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput do
  @moduledoc """
  The output of the validation given the document and the validation rules.

  ## Attributes

  *   `pass_all_rules` (*type:* `boolean()`) - The overall result of the validation, true if all applicable rules are valid.
  *   `validation_results` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutputValidationResult.t())`) - The result of each validation rule.
  """

  defstruct [:pass_all_rules, :validation_results]

  @type t :: %__MODULE__{
          pass_all_rules: boolean() | nil,
          validation_results:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutputValidationResult.t()
            )
            | nil
        }

  @wire %{pass_all_rules: "passAllRules", validation_results: "validationResults"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      pass_all_rules: m["passAllRules"],
      validation_results:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutputValidationResult.decode(
          m["validationResults"]
        )
    }
  end
end
