# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableCell do
  @moduledoc """
  A cell representation inside the table.

  ## Attributes

  *   `col_span` (*type:* `integer()`) - How many columns this cell spans.
  *   `detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages together with confidence.
  *   `layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for TableCell.
  *   `row_span` (*type:* `integer()`) - How many rows this cell spans.
  """

  defstruct [:col_span, :detected_languages, :layout, :row_span]

  @type t :: %__MODULE__{
          col_span: integer() | nil,
          detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          layout: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          row_span: integer() | nil
        }

  @wire %{col_span: "colSpan", detected_languages: "detectedLanguages", row_span: "rowSpan"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      col_span: m["colSpan"],
      detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["detectedLanguages"]
        ),
      layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["layout"]),
      row_span: m["rowSpan"]
    }
  end
end
