# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions do
  @moduledoc """
  Options for Process API

  ## Attributes

  *   `from_end` (*type:* `integer()`) - Only process certain pages from the end, same as above.
  *   `from_start` (*type:* `integer()`) - Only process certain pages from the start. Process all if the document has fewer pages.
  *   `individual_page_selector` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsIndividualPageSelector.t()`) - Which pages to process (1-indexed).
  *   `layout_config` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfig.t()`) - Optional. Only applicable to `LAYOUT_PARSER_PROCESSOR`. Returns error if set on other processor types.
  *   `ocr_config` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1OcrConfig.t()`) - Only applicable to `OCR_PROCESSOR` and `FORM_PARSER_PROCESSOR`. Returns error if set on other processor types.
  *   `schema_override` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.t()`) - Optional. Override the schema of the ProcessorVersion. Will return an Invalid Argument error if this field is set when the underlying ProcessorVersion doesn't support schema override.
  """

  defstruct [
    :from_end,
    :from_start,
    :individual_page_selector,
    :layout_config,
    :ocr_config,
    :schema_override
  ]

  @type t :: %__MODULE__{
          from_end: integer() | nil,
          from_start: integer() | nil,
          individual_page_selector:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsIndividualPageSelector.t()
            | nil,
          layout_config:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfig.t() | nil,
          ocr_config: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1OcrConfig.t() | nil,
          schema_override: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.t() | nil
        }

  @wire %{
    from_end: "fromEnd",
    from_start: "fromStart",
    individual_page_selector: "individualPageSelector",
    layout_config: "layoutConfig",
    ocr_config: "ocrConfig",
    schema_override: "schemaOverride"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      from_end: m["fromEnd"],
      from_start: m["fromStart"],
      individual_page_selector:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsIndividualPageSelector.decode(
          m["individualPageSelector"]
        ),
      layout_config:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfig.decode(
          m["layoutConfig"]
        ),
      ocr_config: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1OcrConfig.decode(m["ocrConfig"]),
      schema_override:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.decode(m["schemaOverride"])
    }
  end
end
