# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentSchemaEntityTypeEnumValues do
  @moduledoc """
  Defines the a list of enum values.

  ## Attributes

  *   `values` (*type:* `list(String.t())`) - The individual values that this enum values type can include.
  """

  defstruct [:values]

  @type t :: %__MODULE__{
          values: list(String.t()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      values: m["values"]
    }
  end
end
