# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEditabilityMetadata do
  @moduledoc """
  Metadata that specifies whether a label is editable and reasons why. These fields are read-only. Changing these fields has no impact on the backend.

  ## Attributes

  *   `editable` (*type:* `boolean()`) - Explicit flag that controls whether the label is editable.
  *   `processor_versions` (*type:* `list(String.t())`) - Full resource name of processor versions that contain this label. e.g. `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`
  """

  defstruct [:editable, :processor_versions]

  @type t :: %__MODULE__{
          editable: boolean() | nil,
          processor_versions: list(String.t()) | nil
        }

  @wire %{processor_versions: "processorVersions"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      editable: m["editable"],
      processor_versions: m["processorVersions"]
    }
  end
end
