# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenStyleInfo do
  @moduledoc """
  Font and other text style attributes.

  ## Attributes

  *   `background_color` (*type:* `Googly.DocumentAI.Model.GoogleTypeColor.t()`) - Color of the background.
  *   `bold` (*type:* `boolean()`) - Whether the text is bold (equivalent to font_weight is at least `700`).
  *   `font_size` (*type:* `integer()`) - Font size in points (`1` point is `¹⁄₇₂` inches).
  *   `font_type` (*type:* `String.t()`) - Name or style of the font.
  *   `font_weight` (*type:* `integer()`) - TrueType weight on a scale `100` (thin) to `1000` (ultra-heavy). Normal is `400`, bold is `700`.
  *   `handwritten` (*type:* `boolean()`) - Whether the text is handwritten.
  *   `italic` (*type:* `boolean()`) - Whether the text is italic.
  *   `letter_spacing` (*type:* `float()`) - Letter spacing in points.
  *   `pixel_font_size` (*type:* `float()`) - Font size in pixels, equal to _unrounded font_size_ * _resolution_ ÷ `72.0`.
  *   `smallcaps` (*type:* `boolean()`) - Whether the text is in small caps. This feature is not supported yet.
  *   `strikeout` (*type:* `boolean()`) - Whether the text is strikethrough. This feature is not supported yet.
  *   `subscript` (*type:* `boolean()`) - Whether the text is a subscript. This feature is not supported yet.
  *   `superscript` (*type:* `boolean()`) - Whether the text is a superscript. This feature is not supported yet.
  *   `text_color` (*type:* `Googly.DocumentAI.Model.GoogleTypeColor.t()`) - Color of the text.
  *   `underlined` (*type:* `boolean()`) - Whether the text is underlined.
  """

  defstruct [
    :background_color,
    :bold,
    :font_size,
    :font_type,
    :font_weight,
    :handwritten,
    :italic,
    :letter_spacing,
    :pixel_font_size,
    :smallcaps,
    :strikeout,
    :subscript,
    :superscript,
    :text_color,
    :underlined
  ]

  @type t :: %__MODULE__{
          background_color: Googly.DocumentAI.Model.GoogleTypeColor.t() | nil,
          bold: boolean() | nil,
          font_size: integer() | nil,
          font_type: String.t() | nil,
          font_weight: integer() | nil,
          handwritten: boolean() | nil,
          italic: boolean() | nil,
          letter_spacing: float() | nil,
          pixel_font_size: float() | nil,
          smallcaps: boolean() | nil,
          strikeout: boolean() | nil,
          subscript: boolean() | nil,
          superscript: boolean() | nil,
          text_color: Googly.DocumentAI.Model.GoogleTypeColor.t() | nil,
          underlined: boolean() | nil
        }

  @wire %{
    background_color: "backgroundColor",
    font_size: "fontSize",
    font_type: "fontType",
    font_weight: "fontWeight",
    letter_spacing: "letterSpacing",
    pixel_font_size: "pixelFontSize",
    text_color: "textColor"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      background_color: Googly.DocumentAI.Model.GoogleTypeColor.decode(m["backgroundColor"]),
      bold: m["bold"],
      font_size: m["fontSize"],
      font_type: m["fontType"],
      font_weight: m["fontWeight"],
      handwritten: m["handwritten"],
      italic: m["italic"],
      letter_spacing: m["letterSpacing"],
      pixel_font_size: m["pixelFontSize"],
      smallcaps: m["smallcaps"],
      strikeout: m["strikeout"],
      subscript: m["subscript"],
      superscript: m["superscript"],
      text_color: Googly.DocumentAI.Model.GoogleTypeColor.decode(m["textColor"]),
      underlined: m["underlined"]
    }
  end
end
