# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTable do
  @moduledoc """
  A table representation similar to HTML table structure.

  ## Attributes

  *   `body_rows` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow.t())`) - Body rows of the table.
  *   `detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages together with confidence.
  *   `header_rows` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow.t())`) - Header rows of the table.
  *   `layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for Table.
  *   `provenance` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t()`) - The history of this table.
  """

  defstruct [:body_rows, :detected_languages, :header_rows, :layout, :provenance]

  @type t :: %__MODULE__{
          body_rows:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow.t())
            | nil,
          detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          header_rows:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow.t())
            | nil,
          layout: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          provenance: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t() | nil
        }

  @wire %{
    body_rows: "bodyRows",
    detected_languages: "detectedLanguages",
    header_rows: "headerRows"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      body_rows:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow.decode(
          m["bodyRows"]
        ),
      detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["detectedLanguages"]
        ),
      header_rows:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow.decode(
          m["headerRows"]
        ),
      layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["layout"]),
      provenance:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.decode(m["provenance"])
    }
  end
end
