# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion do
  @moduledoc """
  SchemaVersion is a version of the Schema which is created in SchemaGroup.

  ## Attributes

  *   `create_time` (*type:* `DateTime.t()`) - Output only. The time when the SchemaVersion was created.
  *   `display_name` (*type:* `String.t()`) - Required. The user-defined name of the SchemaVersion.
  *   `labels` (*type:* `map()`) - Optional. The {{gcp_name_short}} labels for the SchemaVersion.
  *   `name` (*type:* `String.t()`) - Identifier. The resource name of the SchemaVersion. Format: `projects/{project}/locations/{location}/schemas/{schema}/schemaVersions/{schema_version}`
  *   `schema` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.t()`) - Required. The schema of the SchemaVersion.
  """

  alias Googly.DocumentAI.Decode

  defstruct [:create_time, :display_name, :labels, :name, :schema]

  @type t :: %__MODULE__{
          create_time: DateTime.t() | nil,
          display_name: String.t() | nil,
          labels: map() | nil,
          name: String.t() | nil,
          schema: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.t() | nil
        }

  @wire %{create_time: "createTime", display_name: "displayName"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      create_time: Decode.datetime(m["createTime"]),
      display_name: m["displayName"],
      labels: m["labels"],
      name: m["name"],
      schema: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.decode(m["schema"])
    }
  end
end
