# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScores do
  @moduledoc """
  Image quality scores for the page image.

  ## Attributes

  *   `detected_defects` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScoresDetectedDefect.t())`) - A list of detected defects.
  *   `quality_score` (*type:* `number()`) - The overall quality score. Range `[0, 1]` where `1` is perfect quality.
  """

  defstruct [:detected_defects, :quality_score]

  @type t :: %__MODULE__{
          detected_defects:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScoresDetectedDefect.t()
            )
            | nil,
          quality_score: number() | nil
        }

  @wire %{detected_defects: "detectedDefects", quality_score: "qualityScore"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      detected_defects:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScoresDetectedDefect.decode(
          m["detectedDefects"]
        ),
      quality_score: m["qualityScore"]
    }
  end
end
