# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaMetadata do
  @moduledoc """
  Metadata for global schema behavior.

  ## Attributes

  *   `document_allow_multiple_labels` (*type:* `boolean()`) - If true, on a given page, there can be multiple `document` annotations covering it.
  *   `document_splitter` (*type:* `boolean()`) - If true, a `document` entity type can be applied to subdocument (splitting). Otherwise, it can only be applied to the entire document (classification).
  *   `prefixed_naming_on_properties` (*type:* `boolean()`) - If set, all the nested entities must be prefixed with the parents.
  *   `skip_naming_validation` (*type:* `boolean()`) - If set, this will skip the naming format validation in the schema. So the string values in `DocumentSchema.EntityType.name` and `DocumentSchema.EntityType.Property.name` will not be checked.
  """

  defstruct [
    :document_allow_multiple_labels,
    :document_splitter,
    :prefixed_naming_on_properties,
    :skip_naming_validation
  ]

  @type t :: %__MODULE__{
          document_allow_multiple_labels: boolean() | nil,
          document_splitter: boolean() | nil,
          prefixed_naming_on_properties: boolean() | nil,
          skip_naming_validation: boolean() | nil
        }

  @wire %{
    document_allow_multiple_labels: "documentAllowMultipleLabels",
    document_splitter: "documentSplitter",
    prefixed_naming_on_properties: "prefixedNamingOnProperties",
    skip_naming_validation: "skipNamingValidation"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document_allow_multiple_labels: m["documentAllowMultipleLabels"],
      document_splitter: m["documentSplitter"],
      prefixed_naming_on_properties: m["prefixedNamingOnProperties"],
      skip_naming_validation: m["skipNamingValidation"]
    }
  end
end
