# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityRelation do
  @moduledoc """
  Relationship between Entities.

  ## Attributes

  *   `object_id` (*type:* `String.t()`) - Object entity id.
  *   `relation` (*type:* `String.t()`) - Relationship description.
  *   `subject_id` (*type:* `String.t()`) - Subject entity id.
  """

  defstruct [:object_id, :relation, :subject_id]

  @type t :: %__MODULE__{
          object_id: String.t() | nil,
          relation: String.t() | nil,
          subject_id: String.t() | nil
        }

  @wire %{object_id: "objectId", subject_id: "subjectId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      object_id: m["objectId"],
      relation: m["relation"],
      subject_id: m["subjectId"]
    }
  end
end
