# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoFoundationGenAiModelInfo do
  @moduledoc """
  Information for a pretrained Google-managed foundation model.

  ## Attributes

  *   `finetuning_allowed` (*type:* `boolean()`) - Whether fine tuning is allowed for this base processor version.
  *   `min_train_labeled_documents` (*type:* `integer()`) - The minimum number of labeled documents in the training dataset required for fine tuning.
  """

  defstruct [:finetuning_allowed, :min_train_labeled_documents]

  @type t :: %__MODULE__{
          finetuning_allowed: boolean() | nil,
          min_train_labeled_documents: integer() | nil
        }

  @wire %{
    finetuning_allowed: "finetuningAllowed",
    min_train_labeled_documents: "minTrainLabeledDocuments"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      finetuning_allowed: m["finetuningAllowed"],
      min_train_labeled_documents: m["minTrainLabeledDocuments"]
    }
  end
end
