# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataSplitExportStat do
  @moduledoc """
  The statistic representing a dataset split type for this export.

  ## Attributes

  *   `split_type` (*type:* `String.t()`) - The dataset split type.
  *   `total_document_count` (*type:* `integer()`) - Total number of documents with the given dataset split type to be exported.
  """

  defstruct [:split_type, :total_document_count]

  @type t :: %__MODULE__{
          split_type: String.t() | nil,
          total_document_count: integer() | nil
        }

  @wire %{split_type: "splitType", total_document_count: "totalDocumentCount"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      split_type: m["splitType"],
      total_document_count: m["totalDocumentCount"]
    }
  end
end
