# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityNormalizedValue do
  @moduledoc """
  Parsed and normalized entity value.

  ## Attributes

  *   `address_value` (*type:* `Googly.DocumentAI.Model.GoogleTypePostalAddress.t()`) - Postal address. See also: https://github.com/googleapis/googleapis/blob/master/google/type/postal_address.proto
  *   `boolean_value` (*type:* `boolean()`) - Boolean value. Can be used for entities with binary values, or for checkboxes.
  *   `date_value` (*type:* `Googly.DocumentAI.Model.GoogleTypeDate.t()`) - Date value. Includes year, month, day. See also: https://github.com/googleapis/googleapis/blob/master/google/type/date.proto
  *   `datetime_value` (*type:* `Googly.DocumentAI.Model.GoogleTypeDateTime.t()`) - DateTime value. Includes date, time, and timezone. See also: https://github.com/googleapis/googleapis/blob/master/google/type/datetime.proto
  *   `float_value` (*type:* `number()`) - Float value.
  *   `integer_value` (*type:* `integer()`) - Integer value.
  *   `money_value` (*type:* `Googly.DocumentAI.Model.GoogleTypeMoney.t()`) - Money value. See also: https://github.com/googleapis/googleapis/blob/master/google/type/money.proto
  *   `signature_value` (*type:* `boolean()`) - A signature - a graphical representation of a person's name, often used to sign a document.
  *   `text` (*type:* `String.t()`) - Optional. An optional field to store a normalized string. For some entity types, one of respective `structured_value` fields may also be populated. Also not all the types of `structured_value` will be normalized. For example, some processors may not generate `float` or `integer` normalized text by default. Below are sample formats mapped to structured values. - Money/Currency type (`money_value`) is in the ISO 4217 text format. - Date type (`date_value`) is in the ISO 8601 text format. - Datetime type (`datetime_value`) is in the ISO 8601 text format.
  """

  defstruct [
    :address_value,
    :boolean_value,
    :date_value,
    :datetime_value,
    :float_value,
    :integer_value,
    :money_value,
    :signature_value,
    :text
  ]

  @type t :: %__MODULE__{
          address_value: Googly.DocumentAI.Model.GoogleTypePostalAddress.t() | nil,
          boolean_value: boolean() | nil,
          date_value: Googly.DocumentAI.Model.GoogleTypeDate.t() | nil,
          datetime_value: Googly.DocumentAI.Model.GoogleTypeDateTime.t() | nil,
          float_value: number() | nil,
          integer_value: integer() | nil,
          money_value: Googly.DocumentAI.Model.GoogleTypeMoney.t() | nil,
          signature_value: boolean() | nil,
          text: String.t() | nil
        }

  @wire %{
    address_value: "addressValue",
    boolean_value: "booleanValue",
    date_value: "dateValue",
    datetime_value: "datetimeValue",
    float_value: "floatValue",
    integer_value: "integerValue",
    money_value: "moneyValue",
    signature_value: "signatureValue"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      address_value: Googly.DocumentAI.Model.GoogleTypePostalAddress.decode(m["addressValue"]),
      boolean_value: m["booleanValue"],
      date_value: Googly.DocumentAI.Model.GoogleTypeDate.decode(m["dateValue"]),
      datetime_value: Googly.DocumentAI.Model.GoogleTypeDateTime.decode(m["datetimeValue"]),
      float_value: m["floatValue"],
      integer_value: m["integerValue"],
      money_value: Googly.DocumentAI.Model.GoogleTypeMoney.decode(m["moneyValue"]),
      signature_value: m["signatureValue"],
      text: m["text"]
    }
  end
end
