# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock do
  @moduledoc """
  Represents a block. A block could be one of the various types (text, table, list) supported.

  ## Attributes

  *   `block_id` (*type:* `String.t()`) - ID of the block.
  *   `bounding_box` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.t()`) - Identifies the bounding box for the block.
  *   `image_block` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutImageBlock.t()`) - Block consisting of image content.
  *   `list_block` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListBlock.t()`) - Block consisting of list content/structure.
  *   `page_span` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutPageSpan.t()`) - Page span of the block.
  *   `table_block` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableBlock.t()`) - Block consisting of table content/structure.
  *   `text_block` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTextBlock.t()`) - Block consisting of text content.
  """

  defstruct [
    :block_id,
    :bounding_box,
    :image_block,
    :list_block,
    :page_span,
    :table_block,
    :text_block
  ]

  @type t :: %__MODULE__{
          block_id: String.t() | nil,
          bounding_box: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.t() | nil,
          image_block:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutImageBlock.t()
            | nil,
          list_block:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListBlock.t()
            | nil,
          page_span:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutPageSpan.t()
            | nil,
          table_block:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableBlock.t()
            | nil,
          text_block:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTextBlock.t()
            | nil
        }

  @wire %{
    block_id: "blockId",
    bounding_box: "boundingBox",
    image_block: "imageBlock",
    list_block: "listBlock",
    page_span: "pageSpan",
    table_block: "tableBlock",
    text_block: "textBlock"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      block_id: m["blockId"],
      bounding_box:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.decode(m["boundingBox"]),
      image_block:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutImageBlock.decode(
          m["imageBlock"]
        ),
      list_block:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListBlock.decode(
          m["listBlock"]
        ),
      page_span:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutPageSpan.decode(
          m["pageSpan"]
        ),
      table_block:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableBlock.decode(
          m["tableBlock"]
        ),
      text_block:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTextBlock.decode(
          m["textBlock"]
        )
    }
  end
end
