# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3Processor do
  @moduledoc """
  The first-class citizen for Document AI. Each processor defines how to extract structural information from a document.

  ## Attributes

  *   `active_schema_version` (*type:* `String.t()`) - Optional. SchemaVersion used by the Processor. It is the same as Processor's DatasetSchema.schema_version Format is `projects/{project}/locations/{location}/schemas/{schema}/schemaVersions/{schema_version}`
  *   `create_time` (*type:* `DateTime.t()`) - Output only. The time the processor was created.
  *   `default_processor_version` (*type:* `String.t()`) - The default processor version.
  *   `display_name` (*type:* `String.t()`) - The display name of the processor.
  *   `kms_key_name` (*type:* `String.t()`) - The [KMS key](https://cloud.google.com/security-key-management) used for encryption and decryption in CMEK scenarios.
  *   `name` (*type:* `String.t()`) - Output only. Immutable. The resource name of the processor. Format: `projects/{project}/locations/{location}/processors/{processor}`
  *   `process_endpoint` (*type:* `String.t()`) - Output only. Immutable. The http endpoint that can be called to invoke processing.
  *   `processor_version_aliases` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionAlias.t())`) - Output only. The processor version aliases.
  *   `satisfies_pzi` (*type:* `boolean()`) - Output only. Reserved for future use.
  *   `satisfies_pzs` (*type:* `boolean()`) - Output only. Reserved for future use.
  *   `state` (*type:* `String.t()`) - Output only. The state of the processor.
  *   `type` (*type:* `String.t()`) - The processor type, such as: `OCR_PROCESSOR`, `INVOICE_PROCESSOR`. To get a list of processor types, see FetchProcessorTypes.
  """

  alias Googly.DocumentAI.Decode

  defstruct [
    :active_schema_version,
    :create_time,
    :default_processor_version,
    :display_name,
    :kms_key_name,
    :name,
    :process_endpoint,
    :processor_version_aliases,
    :satisfies_pzi,
    :satisfies_pzs,
    :state,
    :type
  ]

  @type t :: %__MODULE__{
          active_schema_version: String.t() | nil,
          create_time: DateTime.t() | nil,
          default_processor_version: String.t() | nil,
          display_name: String.t() | nil,
          kms_key_name: String.t() | nil,
          name: String.t() | nil,
          process_endpoint: String.t() | nil,
          processor_version_aliases:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionAlias.t())
            | nil,
          satisfies_pzi: boolean() | nil,
          satisfies_pzs: boolean() | nil,
          state: String.t() | nil,
          type: String.t() | nil
        }

  @wire %{
    active_schema_version: "activeSchemaVersion",
    create_time: "createTime",
    default_processor_version: "defaultProcessorVersion",
    display_name: "displayName",
    kms_key_name: "kmsKeyName",
    process_endpoint: "processEndpoint",
    processor_version_aliases: "processorVersionAliases",
    satisfies_pzi: "satisfiesPzi",
    satisfies_pzs: "satisfiesPzs"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      active_schema_version: m["activeSchemaVersion"],
      create_time: Decode.datetime(m["createTime"]),
      default_processor_version: m["defaultProcessorVersion"],
      display_name: m["displayName"],
      kms_key_name: m["kmsKeyName"],
      name: m["name"],
      process_endpoint: m["processEndpoint"],
      processor_version_aliases:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionAlias.decode(
          m["processorVersionAliases"]
        ),
      satisfies_pzi: m["satisfiesPzi"],
      satisfies_pzs: m["satisfiesPzs"],
      state: m["state"],
      type: m["type"]
    }
  end
end
