# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableCell do
  @moduledoc """
  Represents a cell in a table row.

  ## Attributes

  *   `blocks` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.t())`) - A table cell is a list of blocks. Repeated blocks support further hierarchies and nested blocks.
  *   `col_span` (*type:* `integer()`) - How many columns this cell spans.
  *   `row_span` (*type:* `integer()`) - How many rows this cell spans.
  """

  defstruct [:blocks, :col_span, :row_span]

  @type t :: %__MODULE__{
          blocks:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.t()
            )
            | nil,
          col_span: integer() | nil,
          row_span: integer() | nil
        }

  @wire %{col_span: "colSpan", row_span: "rowSpan"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      blocks:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.decode(
          m["blocks"]
        ),
      col_span: m["colSpan"],
      row_span: m["rowSpan"]
    }
  end
end
