# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfo do
  @moduledoc """
  Information about Generative AI model-based processor versions.

  ## Attributes

  *   `custom_gen_ai_model_info` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoCustomGenAiModelInfo.t()`) - Information for a custom Generative AI model created by the user.
  *   `foundation_gen_ai_model_info` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoFoundationGenAiModelInfo.t()`) - Information for a pretrained Google-managed foundation model.
  """

  defstruct [:custom_gen_ai_model_info, :foundation_gen_ai_model_info]

  @type t :: %__MODULE__{
          custom_gen_ai_model_info:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoCustomGenAiModelInfo.t()
            | nil,
          foundation_gen_ai_model_info:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoFoundationGenAiModelInfo.t()
            | nil
        }

  @wire %{
    custom_gen_ai_model_info: "customGenAiModelInfo",
    foundation_gen_ai_model_info: "foundationGenAiModelInfo"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      custom_gen_ai_model_info:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoCustomGenAiModelInfo.decode(
          m["customGenAiModelInfo"]
        ),
      foundation_gen_ai_model_info:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ProcessorVersionGenAiModelInfoFoundationGenAiModelInfo.decode(
          m["foundationGenAiModelInfo"]
        )
    }
  end
end
