# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3ImportDocumentsMetadataIndividualImportStatus do
  @moduledoc """
  The status of each individual document in the import process.

  ## Attributes

  *   `input_gcs_source` (*type:* `String.t()`) - The source Cloud Storage URI of the document.
  *   `output_document_id` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentId.t()`) - The document id of imported document if it was successful, otherwise empty.
  *   `status` (*type:* `Googly.DocumentAI.Model.GoogleRpcStatus.t()`) - The status of the importing of the document.
  """

  defstruct [:input_gcs_source, :output_document_id, :status]

  @type t :: %__MODULE__{
          input_gcs_source: String.t() | nil,
          output_document_id:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentId.t() | nil,
          status: Googly.DocumentAI.Model.GoogleRpcStatus.t() | nil
        }

  @wire %{input_gcs_source: "inputGcsSource", output_document_id: "outputDocumentId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      input_gcs_source: m["inputGcsSource"],
      output_document_id:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentId.decode(
          m["outputDocumentId"]
        ),
      status: Googly.DocumentAI.Model.GoogleRpcStatus.decode(m["status"])
    }
  end
end
