# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageBlock do
  @moduledoc """
  A block has a set of lines (collected into paragraphs) that have a common line-spacing and orientation.

  ## Attributes

  *   `detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages together with confidence.
  *   `layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for Block.
  *   `provenance` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t()`) - The history of this annotation.
  """

  defstruct [:detected_languages, :layout, :provenance]

  @type t :: %__MODULE__{
          detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          layout: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          provenance: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t() | nil
        }

  @wire %{detected_languages: "detectedLanguages"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["detectedLanguages"]
        ),
      layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["layout"]),
      provenance:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.decode(m["provenance"])
    }
  end
end
