# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadata do
  @moduledoc """


  ## Attributes

  *   `common_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()`) - The basic metadata of the long-running operation.
  *   `error_document_count` (*type:* `integer()`) - Total number of documents that failed to be deleted in storage.
  *   `individual_batch_delete_statuses` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataIndividualBatchDeleteStatus.t())`) - The list of response details of each document.
  *   `total_document_count` (*type:* `integer()`) - Total number of documents deleting from dataset.
  """

  defstruct [
    :common_metadata,
    :error_document_count,
    :individual_batch_delete_statuses,
    :total_document_count
  ]

  @type t :: %__MODULE__{
          common_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()
            | nil,
          error_document_count: integer() | nil,
          individual_batch_delete_statuses:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataIndividualBatchDeleteStatus.t()
            )
            | nil,
          total_document_count: integer() | nil
        }

  @wire %{
    common_metadata: "commonMetadata",
    error_document_count: "errorDocumentCount",
    individual_batch_delete_statuses: "individualBatchDeleteStatuses",
    total_document_count: "totalDocumentCount"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      common_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.decode(
          m["commonMetadata"]
        ),
      error_document_count: m["errorDocumentCount"],
      individual_batch_delete_statuses:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchDeleteDocumentsMetadataIndividualBatchDeleteStatus.decode(
          m["individualBatchDeleteStatuses"]
        ),
      total_document_count: m["totalDocumentCount"]
    }
  end
end
