# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1OcrConfigHints do
  @moduledoc """
  Hints for OCR Engine

  ## Attributes

  *   `language_hints` (*type:* `list(String.t())`) - List of BCP-47 language codes to use for OCR. In most cases, not specifying it yields the best results since it enables automatic language detection. For languages based on the Latin alphabet, setting hints is not needed. In rare cases, when the language of the text in the image is known, setting a hint will help get better results (although it will be a significant hindrance if the hint is wrong).
  """

  defstruct [:language_hints]

  @type t :: %__MODULE__{
          language_hints: list(String.t()) | nil
        }

  @wire %{language_hints: "languageHints"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      language_hints: m["languageHints"]
    }
  end
end
