# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListBlock do
  @moduledoc """
  Represents a list type block.

  ## Attributes

  *   `list_entries` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListEntry.t())`) - List entries that constitute a list block.
  *   `type` (*type:* `String.t()`) - Type of the list_entries (if exist). Available options are `ordered` and `unordered`.
  """

  defstruct [:list_entries, :type]

  @type t :: %__MODULE__{
          list_entries:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListEntry.t()
            )
            | nil,
          type: String.t() | nil
        }

  @wire %{list_entries: "listEntries"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      list_entries:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListEntry.decode(
          m["listEntries"]
        ),
      type: m["type"]
    }
  end
end
