# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageFormField do
  @moduledoc """
  A form field detected on the page.

  ## Attributes

  *   `corrected_key_text` (*type:* `String.t()`) - Created for Labeling UI to export key text. If corrections were made to the text identified by the `field_name.text_anchor`, this field will contain the correction.
  *   `corrected_value_text` (*type:* `String.t()`) - Created for Labeling UI to export value text. If corrections were made to the text identified by the `field_value.text_anchor`, this field will contain the correction.
  *   `field_name` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for the FormField name. For example, `Address`, `Email`, `Grand total`, `Phone number`, etc.
  *   `field_value` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for the FormField value.
  *   `name_detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages for name together with confidence.
  *   `provenance` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t()`) - The history of this annotation.
  *   `value_detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages for value together with confidence.
  *   `value_type` (*type:* `String.t()`) - If the value is non-textual, this field represents the type. Current valid values are: - blank (this indicates the `field_value` is normal text) - `unfilled_checkbox` - `filled_checkbox`
  """

  defstruct [
    :corrected_key_text,
    :corrected_value_text,
    :field_name,
    :field_value,
    :name_detected_languages,
    :provenance,
    :value_detected_languages,
    :value_type
  ]

  @type t :: %__MODULE__{
          corrected_key_text: String.t() | nil,
          corrected_value_text: String.t() | nil,
          field_name: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          field_value:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          name_detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          provenance: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t() | nil,
          value_detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          value_type: String.t() | nil
        }

  @wire %{
    corrected_key_text: "correctedKeyText",
    corrected_value_text: "correctedValueText",
    field_name: "fieldName",
    field_value: "fieldValue",
    name_detected_languages: "nameDetectedLanguages",
    value_detected_languages: "valueDetectedLanguages",
    value_type: "valueType"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      corrected_key_text: m["correctedKeyText"],
      corrected_value_text: m["correctedValueText"],
      field_name:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["fieldName"]),
      field_value:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["fieldValue"]),
      name_detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["nameDetectedLanguages"]
        ),
      provenance:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.decode(m["provenance"]),
      value_detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["valueDetectedLanguages"]
        ),
      value_type: m["valueType"]
    }
  end
end
