# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListProcessorVersionsResponse do
  @moduledoc """
  Response message for the ListProcessorVersions method.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - Points to the next processor, otherwise empty.
  *   `processor_versions` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorVersion.t())`) - The list of processors.
  """

  defstruct [:next_page_token, :processor_versions]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          processor_versions:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorVersion.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken", processor_versions: "processorVersions"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      processor_versions:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorVersion.decode(
          m["processorVersions"]
        )
    }
  end
end
