# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionRequestGenerateSchemaVersionParams do
  @moduledoc """
  The parameters for the schema generation.

  ## Attributes

  *   `history` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationHistory.t()`) - Optional. Previous prompt-answers in a chronological order.
  *   `prompt` (*type:* `String.t()`) - Optional. The prompt used for the schema generation.
  """

  defstruct [:history, :prompt]

  @type t :: %__MODULE__{
          history:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationHistory.t() | nil,
          prompt: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      history:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationHistory.decode(
          m["history"]
        ),
      prompt: m["prompt"]
    }
  end
end
