# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListSchemaVersionsResponse do
  @moduledoc """
  Response message for ListSchemaVersions.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - Points to the next SchemaVersion, otherwise empty.
  *   `schema_versions` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t())`) - The list of SchemaVersions.
  """

  defstruct [:next_page_token, :schema_versions]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          schema_versions:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken", schema_versions: "schemaVersions"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      schema_versions:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.decode(m["schemaVersions"])
    }
  end
end
