# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3EnableProcessorResponse do
  @moduledoc """
  Response message for the EnableProcessor method. Intentionally empty proto for adding fields in future.
  """

  defstruct []

  @type t :: %__MODULE__{}

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(_map), do: %__MODULE__{}
end
