# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageAnchor do
  @moduledoc """
  Referencing the visual context of the entity in the Document.pages. Page anchors can be cross-page, consist of multiple bounding polygons and optionally reference specific layout element types.

  ## Attributes

  *   `page_refs` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageAnchorPageRef.t())`) - One or more references to visual page elements
  """

  defstruct [:page_refs]

  @type t :: %__MODULE__{
          page_refs:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageAnchorPageRef.t())
            | nil
        }

  @wire %{page_refs: "pageRefs"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      page_refs:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageAnchorPageRef.decode(
          m["pageRefs"]
        )
    }
  end
end
