# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3BatchDeleteDocumentsMetadataIndividualBatchDeleteStatus do
  @moduledoc """
  The status of each individual document in the batch delete process.

  ## Attributes

  *   `document_id` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentId.t()`) - The document id of the document.
  *   `status` (*type:* `Googly.DocumentAI.Model.GoogleRpcStatus.t()`) - The status of deleting the document in storage.
  """

  defstruct [:document_id, :status]

  @type t :: %__MODULE__{
          document_id: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentId.t() | nil,
          status: Googly.DocumentAI.Model.GoogleRpcStatus.t() | nil
        }

  @wire %{document_id: "documentId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document_id:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentId.decode(m["documentId"]),
      status: Googly.DocumentAI.Model.GoogleRpcStatus.decode(m["status"])
    }
  end
end
