# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ImportProcessorVersionResponse do
  @moduledoc """
  The response message for the ImportProcessorVersion method.

  ## Attributes

  *   `processor_version` (*type:* `String.t()`) - The destination processor version name.
  """

  defstruct [:processor_version]

  @type t :: %__MODULE__{
          processor_version: String.t() | nil
        }

  @wire %{processor_version: "processorVersion"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      processor_version: m["processorVersion"]
    }
  end
end
