# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3DocumentIdGCSManagedDocumentId do
  @moduledoc """
  Identifies a document uniquely within the scope of a dataset in the user-managed Cloud Storage option.

  ## Attributes

  *   `cw_doc_id` (*type:* `String.t()`) - Id of the document (indexed) managed by Content Warehouse.
  *   `gcs_uri` (*type:* `String.t()`) - Required. The Cloud Storage URI where the actual document is stored.
  """

  defstruct [:cw_doc_id, :gcs_uri]

  @type t :: %__MODULE__{
          cw_doc_id: String.t() | nil,
          gcs_uri: String.t() | nil
        }

  @wire %{cw_doc_id: "cwDocId", gcs_uri: "gcsUri"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      cw_doc_id: m["cwDocId"],
      gcs_uri: m["gcsUri"]
    }
  end
end
