# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocument do
  @moduledoc """
  Payload message of raw document content (bytes).

  ## Attributes

  *   `content` (*type:* `String.t()`) - Inline document content.
  *   `display_name` (*type:* `String.t()`) - The display name of the document, it supports all Unicode characters except the following: `*`, `?`, `[`, `]`, `%`, `{`, `}`,`'`, `\\"`, `,` `~`, `=` and `:` are reserved. If not specified, a default ID is generated.
  *   `mime_type` (*type:* `String.t()`) - An IANA MIME type (RFC6838) indicating the nature and format of the content.
  """

  defstruct [:content, :display_name, :mime_type]

  @type t :: %__MODULE__{
          content: String.t() | nil,
          display_name: String.t() | nil,
          mime_type: String.t() | nil
        }

  @wire %{display_name: "displayName", mime_type: "mimeType"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      content: m["content"],
      display_name: m["displayName"],
      mime_type: m["mimeType"]
    }
  end
end
