# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadata do
  @moduledoc """
  Metadata for how this field value is extracted.

  ## Attributes

  *   `entity_query` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadataEntityQuery.t()`) - Entity query config.
  *   `summary_options` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SummaryOptions.t()`) - Summary options config.
  """

  defstruct [:entity_query, :summary_options]

  @type t :: %__MODULE__{
          entity_query:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadataEntityQuery.t()
            | nil,
          summary_options:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SummaryOptions.t() | nil
        }

  @wire %{entity_query: "entityQuery", summary_options: "summaryOptions"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      entity_query:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadataEntityQuery.decode(
          m["entityQuery"]
        ),
      summary_options:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SummaryOptions.decode(
          m["summaryOptions"]
        )
    }
  end
end
