# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDimension do
  @moduledoc """
  Dimension for the page.

  ## Attributes

  *   `height` (*type:* `number()`) - Page height.
  *   `unit` (*type:* `String.t()`) - Dimension unit.
  *   `width` (*type:* `number()`) - Page width.
  """

  defstruct [:height, :unit, :width]

  @type t :: %__MODULE__{
          height: number() | nil,
          unit: String.t() | nil,
          width: number() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      height: m["height"],
      unit: m["unit"],
      width: m["width"]
    }
  end
end
