# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenDetectedBreak do
  @moduledoc """
  Detected break at the end of a Token.

  ## Attributes

  *   `type` (*type:* `String.t()`) - Detected break type.
  """

  defstruct [:type]

  @type t :: %__MODULE__{
          type: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      type: m["type"]
    }
  end
end
