# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewValidationMetadata do
  @moduledoc """
  Metadata for Human Review config.

  ## Attributes

  *   `confidence_threshold` (*type:* `number()`) - The confidence threshold if human review validation is enabled.
  *   `enable_validation` (*type:* `boolean()`) - Whether to enable human review validation.
  """

  defstruct [:confidence_threshold, :enable_validation]

  @type t :: %__MODULE__{
          confidence_threshold: number() | nil,
          enable_validation: boolean() | nil
        }

  @wire %{confidence_threshold: "confidenceThreshold", enable_validation: "enableValidation"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      confidence_threshold: m["confidenceThreshold"],
      enable_validation: m["enableValidation"]
    }
  end
end
