# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionRequest do
  @moduledoc """
  Request message for GenerateSchemaVersion.

  ## Attributes

  *   `base_schema_version` (*type:* `String.t()`) - The base schema version name to use for the schema generation. Format: `projects/{project}/locations/{location}/schemas/{schema}/schemaVersions/{schema_version}`
  *   `gcs_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocuments.t()`) - The set of documents placed on Cloud Storage.
  *   `gcs_prefix` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsPrefix.t()`) - The common prefix of documents placed on Cloud Storage.
  *   `generate_schema_version_params` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionRequestGenerateSchemaVersionParams.t()`) - Optional. User specified parameters for the schema generation.
  *   `inline_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Documents.t()`) - The set of documents specified inline. For each document, its `uri` or `content` field must be set.
  *   `raw_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocuments.t()`) - The set of raw documents.
  """

  defstruct [
    :base_schema_version,
    :gcs_documents,
    :gcs_prefix,
    :generate_schema_version_params,
    :inline_documents,
    :raw_documents
  ]

  @type t :: %__MODULE__{
          base_schema_version: String.t() | nil,
          gcs_documents: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocuments.t() | nil,
          gcs_prefix: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsPrefix.t() | nil,
          generate_schema_version_params:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionRequestGenerateSchemaVersionParams.t()
            | nil,
          inline_documents: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Documents.t() | nil,
          raw_documents: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocuments.t() | nil
        }

  @wire %{
    base_schema_version: "baseSchemaVersion",
    gcs_documents: "gcsDocuments",
    gcs_prefix: "gcsPrefix",
    generate_schema_version_params: "generateSchemaVersionParams",
    inline_documents: "inlineDocuments",
    raw_documents: "rawDocuments"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      base_schema_version: m["baseSchemaVersion"],
      gcs_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocuments.decode(m["gcsDocuments"]),
      gcs_prefix: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsPrefix.decode(m["gcsPrefix"]),
      generate_schema_version_params:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionRequestGenerateSchemaVersionParams.decode(
          m["generateSchemaVersionParams"]
        ),
      inline_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Documents.decode(m["inlineDocuments"]),
      raw_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocuments.decode(m["rawDocuments"])
    }
  end
end
