# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3Schema do
  @moduledoc """
  The schema defines the output of the processed document by a processor.

  ## Attributes

  *   `description` (*type:* `String.t()`) - Description of the schema.
  *   `display_name` (*type:* `String.t()`) - Display name to show users.
  *   `entity_types` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEntityType.t())`) - Entity types of the schema.
  """

  defstruct [:description, :display_name, :entity_types]

  @type t :: %__MODULE__{
          description: String.t() | nil,
          display_name: String.t() | nil,
          entity_types:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEntityType.t()) | nil
        }

  @wire %{display_name: "displayName", entity_types: "entityTypes"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      description: m["description"],
      display_name: m["displayName"],
      entity_types:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEntityType.decode(
          m["entityTypes"]
        )
    }
  end
end
