# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchProcessRequest do
  @moduledoc """
  Request message for BatchProcessDocuments.

  ## Attributes

  *   `document_output_config` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfig.t()`) - The output configuration for the BatchProcessDocuments method.
  *   `input_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t()`) - The input documents for the BatchProcessDocuments method.
  *   `labels` (*type:* `map()`) - Optional. The labels with user-defined metadata for the request. Label keys and values can be no longer than 63 characters (Unicode codepoints) and can only contain lowercase letters, numeric characters, underscores, and dashes. International characters are allowed. Label values are optional. Label keys must start with a letter.
  *   `process_options` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions.t()`) - Inference-time options for the process API
  *   `skip_human_review` (*type:* `boolean()`) - Whether human review should be skipped for this request. Default to `false`.
  """

  defstruct [
    :document_output_config,
    :input_documents,
    :labels,
    :process_options,
    :skip_human_review
  ]

  @type t :: %__MODULE__{
          document_output_config:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfig.t() | nil,
          input_documents:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t() | nil,
          labels: map() | nil,
          process_options:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions.t() | nil,
          skip_human_review: boolean() | nil
        }

  @wire %{
    document_output_config: "documentOutputConfig",
    input_documents: "inputDocuments",
    process_options: "processOptions",
    skip_human_review: "skipHumanReview"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document_output_config:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfig.decode(
          m["documentOutputConfig"]
        ),
      input_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.decode(
          m["inputDocuments"]
        ),
      labels: m["labels"],
      process_options:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions.decode(m["processOptions"]),
      skip_human_review: m["skipHumanReview"]
    }
  end
end
