# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleLongrunningListOperationsResponse do
  @moduledoc """
  The response message for Operations.ListOperations.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - The standard List next-page token.
  *   `operations` (*type:* `list(Googly.DocumentAI.Model.GoogleLongrunningOperation.t())`) - A list of operations that matches the specified filter in the request.
  *   `unreachable` (*type:* `list(String.t())`) - Unordered list. Unreachable resources. Populated when the request sets `ListOperationsRequest.return_partial_success` and reads across collections. For example, when attempting to list all resources across all supported locations.
  """

  defstruct [:next_page_token, :operations, :unreachable]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          operations: list(Googly.DocumentAI.Model.GoogleLongrunningOperation.t()) | nil,
          unreachable: list(String.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      operations: Googly.DocumentAI.Model.GoogleLongrunningOperation.decode(m["operations"]),
      unreachable: m["unreachable"]
    }
  end
end
