# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageToken do
  @moduledoc """
  A detected token.

  ## Attributes

  *   `detected_break` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenDetectedBreak.t()`) - Detected break at the end of a Token.
  *   `detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages together with confidence.
  *   `layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for Token.
  *   `provenance` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t()`) - The history of this annotation.
  *   `style_info` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenStyleInfo.t()`) - Text style attributes.
  """

  defstruct [:detected_break, :detected_languages, :layout, :provenance, :style_info]

  @type t :: %__MODULE__{
          detected_break:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenDetectedBreak.t()
            | nil,
          detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          layout: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          provenance: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t() | nil,
          style_info:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenStyleInfo.t() | nil
        }

  @wire %{
    detected_break: "detectedBreak",
    detected_languages: "detectedLanguages",
    style_info: "styleInfo"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      detected_break:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenDetectedBreak.decode(
          m["detectedBreak"]
        ),
      detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["detectedLanguages"]
        ),
      layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["layout"]),
      provenance:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.decode(m["provenance"]),
      style_info:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTokenStyleInfo.decode(
          m["styleInfo"]
        )
    }
  end
end
