# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListProcessorTypesResponse do
  @moduledoc """
  Response message for the ListProcessorTypes method.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - Points to the next page, otherwise empty.
  *   `processor_types` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType.t())`) - The processor types.
  """

  defstruct [:next_page_token, :processor_types]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          processor_types:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken", processor_types: "processorTypes"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      processor_types:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType.decode(m["processorTypes"])
    }
  end
end
