# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadata do
  @moduledoc """


  ## Attributes

  *   `common_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()`) - The basic metadata of the long-running operation.
  *   `dest_dataset_type` (*type:* `String.t()`) - The destination dataset split type.
  *   `dest_split_type` (*type:* `String.t()`) - The destination dataset split type.
  *   `individual_batch_move_statuses` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataIndividualBatchMoveStatus.t())`) - The list of response details of each document.
  """

  defstruct [
    :common_metadata,
    :dest_dataset_type,
    :dest_split_type,
    :individual_batch_move_statuses
  ]

  @type t :: %__MODULE__{
          common_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()
            | nil,
          dest_dataset_type: String.t() | nil,
          dest_split_type: String.t() | nil,
          individual_batch_move_statuses:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataIndividualBatchMoveStatus.t()
            )
            | nil
        }

  @wire %{
    common_metadata: "commonMetadata",
    dest_dataset_type: "destDatasetType",
    dest_split_type: "destSplitType",
    individual_batch_move_statuses: "individualBatchMoveStatuses"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      common_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.decode(
          m["commonMetadata"]
        ),
      dest_dataset_type: m["destDatasetType"],
      dest_split_type: m["destSplitType"],
      individual_batch_move_statuses:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchMoveDocumentsMetadataIndividualBatchMoveStatus.decode(
          m["individualBatchMoveStatuses"]
        )
    }
  end
end
