# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfig do
  @moduledoc """
  The configuration used when outputting documents.

  ## Attributes

  *   `field_mask` (*type:* `String.t()`) - Specifies which fields to include in the output documents. Only supports top level document and pages field so it must be in the form of `{document_field_name}` or `pages.{page_field_name}`.
  *   `gcs_uri` (*type:* `String.t()`) - The Cloud Storage uri (a directory) of the output.
  *   `sharding_config` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigShardingConfig.t()`) - Specifies the sharding config for the output document.
  """

  defstruct [:field_mask, :gcs_uri, :sharding_config]

  @type t :: %__MODULE__{
          field_mask: String.t() | nil,
          gcs_uri: String.t() | nil,
          sharding_config:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigShardingConfig.t()
            | nil
        }

  @wire %{field_mask: "fieldMask", gcs_uri: "gcsUri", sharding_config: "shardingConfig"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      field_mask: m["fieldMask"],
      gcs_uri: m["gcsUri"],
      sharding_config:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigShardingConfig.decode(
          m["shardingConfig"]
        )
    }
  end
end
