# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessRequest do
  @moduledoc """
  Request message for the ProcessDocument method.

  ## Attributes

  *   `field_mask` (*type:* `String.t()`) - Specifies which fields to include in the ProcessResponse.document output. Only supports top-level document and pages field, so it must be in the form of `{document_field_name}` or `pages.{page_field_name}`.
  *   `gcs_document` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocument.t()`) - A raw document on Google Cloud Storage.
  *   `imageless_mode` (*type:* `boolean()`) - Optional. Option to remove images from the document.
  *   `inline_document` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t()`) - An inline document proto.
  *   `labels` (*type:* `map()`) - Optional. The labels with user-defined metadata for the request. Label keys and values can be no longer than 63 characters (Unicode codepoints) and can only contain lowercase letters, numeric characters, underscores, and dashes. International characters are allowed. Label values are optional. Label keys must start with a letter.
  *   `process_options` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions.t()`) - Inference-time options for the process API
  *   `raw_document` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocument.t()`) - A raw document content (bytes).
  *   `skip_human_review` (*type:* `boolean()`) - Whether human review should be skipped for this request. Default to `false`.
  """

  defstruct [
    :field_mask,
    :gcs_document,
    :imageless_mode,
    :inline_document,
    :labels,
    :process_options,
    :raw_document,
    :skip_human_review
  ]

  @type t :: %__MODULE__{
          field_mask: String.t() | nil,
          gcs_document: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocument.t() | nil,
          imageless_mode: boolean() | nil,
          inline_document: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t() | nil,
          labels: map() | nil,
          process_options:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions.t() | nil,
          raw_document: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocument.t() | nil,
          skip_human_review: boolean() | nil
        }

  @wire %{
    field_mask: "fieldMask",
    gcs_document: "gcsDocument",
    imageless_mode: "imagelessMode",
    inline_document: "inlineDocument",
    process_options: "processOptions",
    raw_document: "rawDocument",
    skip_human_review: "skipHumanReview"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      field_mask: m["fieldMask"],
      gcs_document:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocument.decode(m["gcsDocument"]),
      imageless_mode: m["imagelessMode"],
      inline_document:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.decode(m["inlineDocument"]),
      labels: m["labels"],
      process_options:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptions.decode(m["processOptions"]),
      raw_document:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1RawDocument.decode(m["rawDocument"]),
      skip_human_review: m["skipHumanReview"]
    }
  end
end
