# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance do
  @moduledoc """
  Structure to identify provenance relationships between annotations in different revisions.

  ## Attributes

  *   `id` (*type:* `integer()`) - The Id of this operation. Needs to be unique within the scope of the revision.
  *   `parents` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenanceParent.t())`) - References to the original elements that are replaced.
  *   `revision` (*type:* `integer()`) - The index of the revision that produced this element.
  *   `type` (*type:* `String.t()`) - The type of provenance operation.
  """

  defstruct [:id, :parents, :revision, :type]

  @type t :: %__MODULE__{
          id: integer() | nil,
          parents:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenanceParent.t())
            | nil,
          revision: integer() | nil,
          type: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      id: m["id"],
      parents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenanceParent.decode(
          m["parents"]
        ),
      revision: m["revision"],
      type: m["type"]
    }
  end
end
