# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentShardInfo do
  @moduledoc """
  For a large document, sharding may be performed to produce several document shards. Each document shard contains this field to detail which shard it is.

  ## Attributes

  *   `page_offset` (*type:* `integer()`) - The index of the first page in Document.pages in the overall document global pages. Available for document shards created by the document splitter.
  *   `shard_count` (*type:* `String.t()`) - Total number of shards.
  *   `shard_index` (*type:* `String.t()`) - The 0-based index of this shard.
  *   `text_offset` (*type:* `String.t()`) - The index of the first character in Document.text in the overall document global text.
  """

  defstruct [:page_offset, :shard_count, :shard_index, :text_offset]

  @type t :: %__MODULE__{
          page_offset: integer() | nil,
          shard_count: String.t() | nil,
          shard_index: String.t() | nil,
          text_offset: String.t() | nil
        }

  @wire %{
    page_offset: "pageOffset",
    shard_count: "shardCount",
    shard_index: "shardIndex",
    text_offset: "textOffset"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      page_offset: m["pageOffset"],
      shard_count: m["shardCount"],
      shard_index: m["shardIndex"],
      text_offset: m["textOffset"]
    }
  end
end
