# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Documents do
  @moduledoc """
  A set of inline documents.

  ## Attributes

  *   `documents` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t())`) - The list of documents.
  """

  defstruct [:documents]

  @type t :: %__MODULE__{
          documents: list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      documents: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.decode(m["documents"])
    }
  end
end
