# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsIndividualPageSelector do
  @moduledoc """
  A list of individual page numbers.

  ## Attributes

  *   `pages` (*type:* `list(integer())`) - Optional. Indices of the pages (starting from 1).
  """

  defstruct [:pages]

  @type t :: %__MODULE__{
          pages: list(integer()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      pages: m["pages"]
    }
  end
end
