# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3FieldExtractionMetadata do
  @moduledoc """
  Metadata for how this field value is extracted.

  ## Attributes

  *   `summary_options` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3SummaryOptions.t()`) - Summary options config.
  """

  defstruct [:summary_options]

  @type t :: %__MODULE__{
          summary_options:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3SummaryOptions.t() | nil
        }

  @wire %{summary_options: "summaryOptions"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      summary_options:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3SummaryOptions.decode(
          m["summaryOptions"]
        )
    }
  end
end
