# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3PropertyMetadata do
  @moduledoc """
  Metadata about a property.

  ## Attributes

  *   `field_extraction_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3FieldExtractionMetadata.t()`) - Field extraction metadata on the property.
  *   `inactive` (*type:* `boolean()`) - Whether the property should be considered as "inactive".
  """

  defstruct [:field_extraction_metadata, :inactive]

  @type t :: %__MODULE__{
          field_extraction_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3FieldExtractionMetadata.t() | nil,
          inactive: boolean() | nil
        }

  @wire %{field_extraction_metadata: "fieldExtractionMetadata"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      field_extraction_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3FieldExtractionMetadata.decode(
          m["fieldExtractionMetadata"]
        ),
      inactive: m["inactive"]
    }
  end
end
