# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfig do
  @moduledoc """
  Serving config for layout parser processor.

  ## Attributes

  *   `chunking_config` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfigChunkingConfig.t()`) - Optional. Config for chunking in layout parser processor.
  *   `enable_image_annotation` (*type:* `boolean()`) - Optional. Whether to include image annotations in layout parser response.
  *   `enable_table_annotation` (*type:* `boolean()`) - Optional. Whether to include table annotations in layout parser response.
  *   `return_bounding_boxes` (*type:* `boolean()`) - Optional. Whether to include bounding boxes in layout parser processor response.
  *   `return_images` (*type:* `boolean()`) - Optional. Whether to include images in layout parser processor response.
  """

  defstruct [
    :chunking_config,
    :enable_image_annotation,
    :enable_table_annotation,
    :return_bounding_boxes,
    :return_images
  ]

  @type t :: %__MODULE__{
          chunking_config:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfigChunkingConfig.t()
            | nil,
          enable_image_annotation: boolean() | nil,
          enable_table_annotation: boolean() | nil,
          return_bounding_boxes: boolean() | nil,
          return_images: boolean() | nil
        }

  @wire %{
    chunking_config: "chunkingConfig",
    enable_image_annotation: "enableImageAnnotation",
    enable_table_annotation: "enableTableAnnotation",
    return_bounding_boxes: "returnBoundingBoxes",
    return_images: "returnImages"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      chunking_config:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfigChunkingConfig.decode(
          m["chunkingConfig"]
        ),
      enable_image_annotation: m["enableImageAnnotation"],
      enable_table_annotation: m["enableTableAnnotation"],
      return_bounding_boxes: m["returnBoundingBoxes"],
      return_images: m["returnImages"]
    }
  end
end
