# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1EvaluateProcessorVersionRequest do
  @moduledoc """
  Evaluates the given ProcessorVersion against the supplied documents.

  ## Attributes

  *   `evaluation_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t()`) - Optional. The documents used in the evaluation. If unspecified, use the processor's dataset as evaluation input.
  """

  defstruct [:evaluation_documents]

  @type t :: %__MODULE__{
          evaluation_documents:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t() | nil
        }

  @wire %{evaluation_documents: "evaluationDocuments"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      evaluation_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.decode(
          m["evaluationDocuments"]
        )
    }
  end
end
