# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SetDefaultProcessorVersionRequest do
  @moduledoc """
  Request message for the SetDefaultProcessorVersion method.

  ## Attributes

  *   `default_processor_version` (*type:* `String.t()`) - Required. The resource name of child ProcessorVersion to use as default. Format: `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{version}`
  """

  defstruct [:default_processor_version]

  @type t :: %__MODULE__{
          default_processor_version: String.t() | nil
        }

  @wire %{default_processor_version: "defaultProcessorVersion"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      default_processor_version: m["defaultProcessorVersion"]
    }
  end
end
