# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType do
  @moduledoc """
  A processor type is responsible for performing a certain document understanding task on a certain type of document.

  ## Attributes

  *   `allow_creation` (*type:* `boolean()`) - Whether the processor type allows creation. If true, users can create a processor of this processor type. Otherwise, users need to request access.
  *   `available_locations` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorTypeLocationInfo.t())`) - The locations in which this processor is available.
  *   `category` (*type:* `String.t()`) - The processor category, used by UI to group processor types.
  *   `launch_stage` (*type:* `String.t()`) - Launch stage of the processor type
  *   `name` (*type:* `String.t()`) - The resource name of the processor type. Format: `projects/{project}/processorTypes/{processor_type}`
  *   `sample_document_uris` (*type:* `list(String.t())`) - A set of Cloud Storage URIs of sample documents for this processor.
  *   `type` (*type:* `String.t()`) - The processor type, such as: `OCR_PROCESSOR`, `INVOICE_PROCESSOR`.
  """

  defstruct [
    :allow_creation,
    :available_locations,
    :category,
    :launch_stage,
    :name,
    :sample_document_uris,
    :type
  ]

  @type t :: %__MODULE__{
          allow_creation: boolean() | nil,
          available_locations:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorTypeLocationInfo.t())
            | nil,
          category: String.t() | nil,
          launch_stage: String.t() | nil,
          name: String.t() | nil,
          sample_document_uris: list(String.t()) | nil,
          type: String.t() | nil
        }

  @wire %{
    allow_creation: "allowCreation",
    available_locations: "availableLocations",
    launch_stage: "launchStage",
    sample_document_uris: "sampleDocumentUris"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      allow_creation: m["allowCreation"],
      available_locations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorTypeLocationInfo.decode(
          m["availableLocations"]
        ),
      category: m["category"],
      launch_stage: m["launchStage"],
      name: m["name"],
      sample_document_uris: m["sampleDocumentUris"],
      type: m["type"]
    }
  end
end
