# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig do
  @moduledoc """
  The common config to specify a set of documents used as input.

  ## Attributes

  *   `gcs_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocuments.t()`) - The set of documents individually specified on Cloud Storage.
  *   `gcs_prefix` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsPrefix.t()`) - The set of documents that match the specified Cloud Storage `gcs_prefix`.
  """

  defstruct [:gcs_documents, :gcs_prefix]

  @type t :: %__MODULE__{
          gcs_documents: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocuments.t() | nil,
          gcs_prefix: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsPrefix.t() | nil
        }

  @wire %{gcs_documents: "gcsDocuments", gcs_prefix: "gcsPrefix"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      gcs_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsDocuments.decode(m["gcsDocuments"]),
      gcs_prefix: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GcsPrefix.decode(m["gcsPrefix"])
    }
  end
end
