# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTextBlock do
  @moduledoc """
  Represents a text type block.

  ## Attributes

  *   `annotations` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t()`) - Annotation of the text block.
  *   `blocks` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.t())`) - A text block could further have child blocks. Repeated blocks support further hierarchies and nested blocks.
  *   `text` (*type:* `String.t()`) - Text content stored in the block.
  *   `type` (*type:* `String.t()`) - Type of the text in the block. Available options are: `paragraph`, `subtitle`, `heading-1`, `heading-2`, `heading-3`, `heading-4`, `heading-5`, `header`, `footer`.
  """

  defstruct [:annotations, :blocks, :text, :type]

  @type t :: %__MODULE__{
          annotations:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t() | nil,
          blocks:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.t()
            )
            | nil,
          text: String.t() | nil,
          type: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      annotations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.decode(
          m["annotations"]
        ),
      blocks:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.decode(
          m["blocks"]
        ),
      text: m["text"],
      type: m["type"]
    }
  end
end
