# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadataEntityQuery do
  @moduledoc """
  Message for entity query.

  ## Attributes

  *   `user_entity_query` (*type:* `String.t()`) - The original entity query inputed by the user.
  """

  defstruct [:user_entity_query]

  @type t :: %__MODULE__{
          user_entity_query: String.t() | nil
        }

  @wire %{user_entity_query: "userEntityQuery"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      user_entity_query: m["userEntityQuery"]
    }
  end
end
