# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedBarcode do
  @moduledoc """
  A detected barcode.

  ## Attributes

  *   `barcode` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Barcode.t()`) - Detailed barcode information of the DetectedBarcode.
  *   `layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for DetectedBarcode.
  """

  defstruct [:barcode, :layout]

  @type t :: %__MODULE__{
          barcode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Barcode.t() | nil,
          layout: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      barcode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Barcode.decode(m["barcode"]),
      layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["layout"])
    }
  end
end
