# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ExportDocumentsMetadataIndividualExportStatus do
  @moduledoc """
  The status of each individual document in the export process.

  ## Attributes

  *   `document_id` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3DocumentId.t()`) - The path to source docproto of the document.
  *   `output_gcs_destination` (*type:* `String.t()`) - The output_gcs_destination of the exported document if it was successful, otherwise empty.
  *   `status` (*type:* `Googly.DocumentAI.Model.GoogleRpcStatus.t()`) - The status of the exporting of the document.
  """

  defstruct [:document_id, :output_gcs_destination, :status]

  @type t :: %__MODULE__{
          document_id: Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3DocumentId.t() | nil,
          output_gcs_destination: String.t() | nil,
          status: Googly.DocumentAI.Model.GoogleRpcStatus.t() | nil
        }

  @wire %{document_id: "documentId", output_gcs_destination: "outputGcsDestination"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document_id:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3DocumentId.decode(m["documentId"]),
      output_gcs_destination: m["outputGcsDestination"],
      status: Googly.DocumentAI.Model.GoogleRpcStatus.decode(m["status"])
    }
  end
end
