# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewLabelingMetadata do
  @moduledoc """
  Metadata for human review labeling config.

  ## Attributes

  *   `enable_normalization_editing` (*type:* `boolean()`) - Whether to enable normalization editing.
  """

  defstruct [:enable_normalization_editing]

  @type t :: %__MODULE__{
          enable_normalization_editing: boolean() | nil
        }

  @wire %{enable_normalization_editing: "enableNormalizationEditing"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      enable_normalization_editing: m["enableNormalizationEditing"]
    }
  end
end
