# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SampleDocumentsResponseSelectedDocument do
  @moduledoc """


  ## Attributes

  *   `document_id` (*type:* `String.t()`) - An internal identifier for document.
  """

  defstruct [:document_id]

  @type t :: %__MODULE__{
          document_id: String.t() | nil
        }

  @wire %{document_id: "documentId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document_id: m["documentId"]
    }
  end
end
