# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaInferenceMetadata do
  @moduledoc """
  Metadata for schema inference. Only used on dataset.schema for schema inference, can be safely ignored elsewhere.

  ## Attributes

  *   `inferred` (*type:* `boolean()`) - True if is inferred by schema inference.
  """

  defstruct [:inferred]

  @type t :: %__MODULE__{
          inferred: boolean() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      inferred: m["inferred"]
    }
  end
end
