# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfig do
  @moduledoc """
  Config that controls the output of documents. All documents will be written as a JSON file.

  ## Attributes

  *   `gcs_output_config` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfig.t()`) - Output config to write the results to Cloud Storage.
  """

  defstruct [:gcs_output_config]

  @type t :: %__MODULE__{
          gcs_output_config:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfig.t()
            | nil
        }

  @wire %{gcs_output_config: "gcsOutputConfig"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      gcs_output_config:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfig.decode(
          m["gcsOutputConfig"]
        )
    }
  end
end
