# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3DocumentIdUnmanagedDocumentId do
  @moduledoc """
  Identifies a document uniquely within the scope of a dataset in unmanaged option.

  ## Attributes

  *   `doc_id` (*type:* `String.t()`) - Required. The id of the document.
  """

  defstruct [:doc_id]

  @type t :: %__MODULE__{
          doc_id: String.t() | nil
        }

  @wire %{doc_id: "docId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      doc_id: m["docId"]
    }
  end
end
