# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentStyleFontSize do
  @moduledoc """
  Font size with unit.

  ## Attributes

  *   `size` (*type:* `number()`) - Font size for the text.
  *   `unit` (*type:* `String.t()`) - Unit for the font size. Follows CSS naming (such as `in`, `px`, and `pt`).
  """

  defstruct [:size, :unit]

  @type t :: %__MODULE__{
          size: number() | nil,
          unit: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      size: m["size"],
      unit: m["unit"]
    }
  end
end
