# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessResponse do
  @moduledoc """
  Response message for the ProcessDocument method.

  ## Attributes

  *   `document` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t()`) - The document payload, will populate fields based on the processor's behavior.
  *   `human_review_status` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1HumanReviewStatus.t()`) - The status of human review on the processed document.
  """

  defstruct [:document, :human_review_status]

  @type t :: %__MODULE__{
          document: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t() | nil,
          human_review_status:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1HumanReviewStatus.t() | nil
        }

  @wire %{human_review_status: "humanReviewStatus"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.decode(m["document"]),
      human_review_status:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1HumanReviewStatus.decode(
          m["humanReviewStatus"]
        )
    }
  end
end
