# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListSchemasResponse do
  @moduledoc """
  Response message for ListSchemas.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - Points to the next Schema, otherwise empty.
  *   `schemas` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1NextSchema.t())`) - The list of Schemas.
  """

  defstruct [:next_page_token, :schemas]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          schemas: list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1NextSchema.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      schemas: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1NextSchema.decode(m["schemas"])
    }
  end
end
