# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3EntityTypeMetadata do
  @moduledoc """
  Metadata about an entity type.

  ## Attributes

  *   `inactive` (*type:* `boolean()`) - Whether the entity type should be considered inactive.
  """

  defstruct [:inactive]

  @type t :: %__MODULE__{
          inactive: boolean() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      inactive: m["inactive"]
    }
  end
end
