# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableRow do
  @moduledoc """
  A row of table cells.

  ## Attributes

  *   `cells` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableCell.t())`) - Cells that make up this row.
  """

  defstruct [:cells]

  @type t :: %__MODULE__{
          cells:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableCell.t())
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      cells:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTableTableCell.decode(
          m["cells"]
        )
    }
  end
end
