# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchUpdateDocumentsMetadata do
  @moduledoc """


  ## Attributes

  *   `common_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()`) - The basic metadata of the long-running operation.
  *   `individual_batch_update_statuses` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchUpdateDocumentsMetadataIndividualBatchUpdateStatus.t())`) - The list of response details of each document.
  """

  defstruct [:common_metadata, :individual_batch_update_statuses]

  @type t :: %__MODULE__{
          common_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()
            | nil,
          individual_batch_update_statuses:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchUpdateDocumentsMetadataIndividualBatchUpdateStatus.t()
            )
            | nil
        }

  @wire %{
    common_metadata: "commonMetadata",
    individual_batch_update_statuses: "individualBatchUpdateStatuses"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      common_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.decode(
          m["commonMetadata"]
        ),
      individual_batch_update_statuses:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3BatchUpdateDocumentsMetadataIndividualBatchUpdateStatus.decode(
          m["individualBatchUpdateStatuses"]
        )
    }
  end
end
