# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchor do
  @moduledoc """
  Text reference indexing into the Document.text.

  ## Attributes

  *   `content` (*type:* `String.t()`) - Contains the content of the text span so that users do not have to look it up in the text_segments. It is always populated for formFields.
  *   `text_segments` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchorTextSegment.t())`) - The text segments from the Document.text.
  """

  defstruct [:content, :text_segments]

  @type t :: %__MODULE__{
          content: String.t() | nil,
          text_segments:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchorTextSegment.t())
            | nil
        }

  @wire %{text_segments: "textSegments"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      content: m["content"],
      text_segments:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchorTextSegment.decode(
          m["textSegments"]
        )
    }
  end
end
