# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3ProcessorVersionDeprecationInfo do
  @moduledoc """
  Information about the upcoming deprecation of this processor version.

  ## Attributes

  *   `deprecation_time` (*type:* `DateTime.t()`) - The time at which this processor version will be deprecated.
  *   `replacement_processor_version` (*type:* `String.t()`) - If set, the processor version that will be used as a replacement.
  """

  alias Googly.DocumentAI.Decode

  defstruct [:deprecation_time, :replacement_processor_version]

  @type t :: %__MODULE__{
          deprecation_time: DateTime.t() | nil,
          replacement_processor_version: String.t() | nil
        }

  @wire %{
    deprecation_time: "deprecationTime",
    replacement_processor_version: "replacementProcessorVersion"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      deprecation_time: Decode.datetime(m["deprecationTime"]),
      replacement_processor_version: m["replacementProcessorVersion"]
    }
  end
end
