# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1NextSchema do
  @moduledoc """
  NextSchema is a collection of SchemaVersions.

  ## Attributes

  *   `create_time` (*type:* `DateTime.t()`) - Output only. The time when the Schema was created.
  *   `display_name` (*type:* `String.t()`) - Required. The user-defined name of the Schema.
  *   `labels` (*type:* `map()`) - Optional. The {{gcp_name_short}} labels for the Schema.
  *   `name` (*type:* `String.t()`) - Identifier. The resource name of the Schema. Format: `projects/{project}/locations/{location}/schemas/{schema}`
  *   `update_time` (*type:* `DateTime.t()`) - Output only. The time when the Schema was last updated.
  """

  alias Googly.DocumentAI.Decode

  defstruct [:create_time, :display_name, :labels, :name, :update_time]

  @type t :: %__MODULE__{
          create_time: DateTime.t() | nil,
          display_name: String.t() | nil,
          labels: map() | nil,
          name: String.t() | nil,
          update_time: DateTime.t() | nil
        }

  @wire %{create_time: "createTime", display_name: "displayName", update_time: "updateTime"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      create_time: Decode.datetime(m["createTime"]),
      display_name: m["displayName"],
      labels: m["labels"],
      name: m["name"],
      update_time: Decode.datetime(m["updateTime"])
    }
  end
end
