# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPage do
  @moduledoc """
  A page in a Document.

  ## Attributes

  *   `blocks` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageBlock.t())`) - A list of visually detected text blocks on the page. A block has a set of lines (collected into paragraphs) that have a common line-spacing and orientation.
  *   `detected_barcodes` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedBarcode.t())`) - A list of detected barcodes.
  *   `detected_languages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())`) - A list of detected languages together with confidence.
  *   `dimension` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDimension.t()`) - Physical dimension of the page.
  *   `form_fields` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageFormField.t())`) - A list of visually detected form fields on the page.
  *   `image` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImage.t()`) - Rendered image for this page. This image is preprocessed to remove any skew, rotation, and distortions such that the annotation bounding boxes can be upright and axis-aligned.
  *   `image_quality_scores` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScores.t()`) - Image quality scores.
  *   `layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t()`) - Layout for the page.
  *   `lines` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLine.t())`) - A list of visually detected text lines on the page. A collection of tokens that a human would perceive as a line.
  *   `page_number` (*type:* `integer()`) - 1-based index for current Page in a parent Document. Useful when a page is taken out of a Document for individual processing.
  *   `paragraphs` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageParagraph.t())`) - A list of visually detected text paragraphs on the page. A collection of lines that a human would perceive as a paragraph.
  *   `provenance` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t()`) - The history of this page.
  *   `symbols` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageSymbol.t())`) - A list of visually detected symbols on the page.
  *   `tables` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTable.t())`) - A list of visually detected tables on the page.
  *   `tokens` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageToken.t())`) - A list of visually detected tokens on the page.
  *   `transforms` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageMatrix.t())`) - Transformation matrices that were applied to the original document image to produce Page.image.
  *   `visual_elements` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageVisualElement.t())`) - A list of detected non-text visual elements, for example, checkbox, signature etc. on the page.
  """

  defstruct [
    :blocks,
    :detected_barcodes,
    :detected_languages,
    :dimension,
    :form_fields,
    :image,
    :image_quality_scores,
    :layout,
    :lines,
    :page_number,
    :paragraphs,
    :provenance,
    :symbols,
    :tables,
    :tokens,
    :transforms,
    :visual_elements
  ]

  @type t :: %__MODULE__{
          blocks:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageBlock.t()) | nil,
          detected_barcodes:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedBarcode.t())
            | nil,
          detected_languages:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.t())
            | nil,
          dimension:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDimension.t() | nil,
          form_fields:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageFormField.t()) | nil,
          image: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImage.t() | nil,
          image_quality_scores:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScores.t()
            | nil,
          layout: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.t() | nil,
          lines: list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLine.t()) | nil,
          page_number: integer() | nil,
          paragraphs:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageParagraph.t()) | nil,
          provenance: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t() | nil,
          symbols:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageSymbol.t()) | nil,
          tables:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTable.t()) | nil,
          tokens:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageToken.t()) | nil,
          transforms:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageMatrix.t()) | nil,
          visual_elements:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageVisualElement.t())
            | nil
        }

  @wire %{
    detected_barcodes: "detectedBarcodes",
    detected_languages: "detectedLanguages",
    form_fields: "formFields",
    image_quality_scores: "imageQualityScores",
    page_number: "pageNumber",
    visual_elements: "visualElements"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      blocks:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageBlock.decode(m["blocks"]),
      detected_barcodes:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedBarcode.decode(
          m["detectedBarcodes"]
        ),
      detected_languages:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDetectedLanguage.decode(
          m["detectedLanguages"]
        ),
      dimension:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageDimension.decode(
          m["dimension"]
        ),
      form_fields:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageFormField.decode(
          m["formFields"]
        ),
      image: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImage.decode(m["image"]),
      image_quality_scores:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScores.decode(
          m["imageQualityScores"]
        ),
      layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout.decode(m["layout"]),
      lines: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLine.decode(m["lines"]),
      page_number: m["pageNumber"],
      paragraphs:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageParagraph.decode(
          m["paragraphs"]
        ),
      provenance:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.decode(m["provenance"]),
      symbols:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageSymbol.decode(m["symbols"]),
      tables:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageTable.decode(m["tables"]),
      tokens:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageToken.decode(m["tokens"]),
      transforms:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageMatrix.decode(m["transforms"]),
      visual_elements:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageVisualElement.decode(
          m["visualElements"]
        )
    }
  end
end
