# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageAnchorPageRef do
  @moduledoc """
  Represents a weak reference to a page element within a document.

  ## Attributes

  *   `bounding_poly` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.t()`) - Optional. Identifies the bounding polygon of a layout element on the page. If `layout_type` is set, the bounding polygon must be exactly the same to the layout element it's referring to.
  *   `confidence` (*type:* `number()`) - Optional. Confidence of detected page element, if applicable. Range `[0, 1]`.
  *   `layout_id` (*type:* `String.t()`) - Optional. Deprecated. Use PageRef.bounding_poly instead.
  *   `layout_type` (*type:* `String.t()`) - Optional. The type of the layout element that is being referenced if any.
  *   `page` (*type:* `String.t()`) - Required. Index into the Document.pages element, for example using `Document.pages` to locate the related page element. This field is skipped when its value is the default `0`. See https://developers.google.com/protocol-buffers/docs/proto3#json.
  """

  defstruct [:bounding_poly, :confidence, :layout_id, :layout_type, :page]

  @type t :: %__MODULE__{
          bounding_poly: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.t() | nil,
          confidence: number() | nil,
          layout_id: String.t() | nil,
          layout_type: String.t() | nil,
          page: String.t() | nil
        }

  @wire %{bounding_poly: "boundingPoly", layout_id: "layoutId", layout_type: "layoutType"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bounding_poly:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.decode(m["boundingPoly"]),
      confidence: m["confidence"],
      layout_id: m["layoutId"],
      layout_type: m["layoutType"],
      page: m["page"]
    }
  end
end
