# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleTypeTimeZone do
  @moduledoc """
  Represents a time zone from the [IANA Time Zone Database](https://www.iana.org/time-zones).

  ## Attributes

  *   `id` (*type:* `String.t()`) - IANA Time Zone Database time zone. For example "America/New_York".
  *   `version` (*type:* `String.t()`) - Optional. IANA Time Zone Database version number. For example "2019a".
  """

  defstruct [:id, :version]

  @type t :: %__MODULE__{
          id: String.t() | nil,
          version: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      id: m["id"],
      version: m["version"]
    }
  end
end
