# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1TrainProcessorVersionRequestInputData do
  @moduledoc """
  The input data used to train a new ProcessorVersion.

  ## Attributes

  *   `test_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t()`) - The documents used for testing the trained version.
  *   `training_documents` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t()`) - The documents used for training the new version.
  """

  defstruct [:test_documents, :training_documents]

  @type t :: %__MODULE__{
          test_documents:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t() | nil,
          training_documents:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.t() | nil
        }

  @wire %{test_documents: "testDocuments", training_documents: "trainingDocuments"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      test_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.decode(
          m["testDocuments"]
        ),
      training_documents:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchDocumentsInputConfig.decode(
          m["trainingDocuments"]
        )
    }
  end
end
