# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutListEntry do
  @moduledoc """
  Represents an entry in the list.

  ## Attributes

  *   `blocks` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.t())`) - A list entry is a list of blocks. Repeated blocks support further hierarchies and nested blocks.
  """

  defstruct [:blocks]

  @type t :: %__MODULE__{
          blocks:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.t()
            )
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      blocks:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlock.decode(
          m["blocks"]
        )
    }
  end
end
