# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchorTextSegment do
  @moduledoc """
  A text segment in the Document.text. The indices may be out of bounds which indicate that the text extends into another document shard for large sharded documents. See ShardInfo.text_offset

  ## Attributes

  *   `end_index` (*type:* `String.t()`) - TextSegment half open end UTF-8 char index in the Document.text.
  *   `start_index` (*type:* `String.t()`) - TextSegment start UTF-8 char index in the Document.text.
  """

  defstruct [:end_index, :start_index]

  @type t :: %__MODULE__{
          end_index: String.t() | nil,
          start_index: String.t() | nil
        }

  @wire %{end_index: "endIndex", start_index: "startIndex"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      end_index: m["endIndex"],
      start_index: m["startIndex"]
    }
  end
end
