# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadata do
  @moduledoc """
  Metadata of the auto-labeling documents operation.

  ## Attributes

  *   `common_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()`) - The basic metadata of the long-running operation.
  *   `individual_auto_label_statuses` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataIndividualAutoLabelStatus.t())`) - The list of individual auto-labeling statuses of the dataset documents.
  *   `total_document_count` (*type:* `integer()`) - Total number of the auto-labeling documents.
  """

  defstruct [:common_metadata, :individual_auto_label_statuses, :total_document_count]

  @type t :: %__MODULE__{
          common_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.t()
            | nil,
          individual_auto_label_statuses:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataIndividualAutoLabelStatus.t()
            )
            | nil,
          total_document_count: integer() | nil
        }

  @wire %{
    common_metadata: "commonMetadata",
    individual_auto_label_statuses: "individualAutoLabelStatuses",
    total_document_count: "totalDocumentCount"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      common_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3CommonOperationMetadata.decode(
          m["commonMetadata"]
        ),
      individual_auto_label_statuses:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3AutoLabelDocumentsMetadataIndividualAutoLabelStatus.decode(
          m["individualAutoLabelStatuses"]
        ),
      total_document_count: m["totalDocumentCount"]
    }
  end
end
