# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeProperty do
  @moduledoc """
  Defines properties that can be part of the entity type.

  ## Attributes

  *   `display_name` (*type:* `String.t()`) - User defined name for the property.
  *   `method` (*type:* `String.t()`) - Specifies how the entity's value is obtained.
  *   `name` (*type:* `String.t()`) - The name of the property. Follows the same guidelines as the EntityType name.
  *   `occurrence_type` (*type:* `String.t()`) - Occurrence type limits the number of instances an entity type appears in the document.
  *   `value_type` (*type:* `String.t()`) - A reference to the value type of the property. This type is subject to the same conventions as the `Entity.base_types` field.
  """

  defstruct [:display_name, :method, :name, :occurrence_type, :value_type]

  @type t :: %__MODULE__{
          display_name: String.t() | nil,
          method: String.t() | nil,
          name: String.t() | nil,
          occurrence_type: String.t() | nil,
          value_type: String.t() | nil
        }

  @wire %{display_name: "displayName", occurrence_type: "occurrenceType", value_type: "valueType"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      display_name: m["displayName"],
      method: m["method"],
      name: m["name"],
      occurrence_type: m["occurrenceType"],
      value_type: m["valueType"]
    }
  end
end
