# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageImageQualityScoresDetectedDefect do
  @moduledoc """
  Image Quality Defects

  ## Attributes

  *   `confidence` (*type:* `number()`) - Confidence of detected defect. Range `[0, 1]` where `1` indicates strong confidence that the defect exists.
  *   `type` (*type:* `String.t()`) - Name of the defect type. Supported values are: - `quality/defect_blurry` - `quality/defect_noisy` - `quality/defect_dark` - `quality/defect_faint` - `quality/defect_text_too_small` - `quality/defect_document_cutoff` - `quality/defect_text_cutoff` - `quality/defect_glare`
  """

  defstruct [:confidence, :type]

  @type t :: %__MODULE__{
          confidence: number() | nil,
          type: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      confidence: m["confidence"],
      type: m["type"]
    }
  end
end
