# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenanceParent do
  @moduledoc """
  The parent element the current element is based on. Used for referencing/aligning, removal and replacement operations.

  ## Attributes

  *   `id` (*type:* `integer()`) - The id of the parent provenance.
  *   `index` (*type:* `integer()`) - The index of the parent item in the corresponding item list (eg. list of entities, properties within entities, etc.) in the parent revision.
  *   `revision` (*type:* `integer()`) - The index of the index into current revision's parent_ids list.
  """

  defstruct [:id, :index, :revision]

  @type t :: %__MODULE__{
          id: integer() | nil,
          index: integer() | nil,
          revision: integer() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      id: m["id"],
      index: m["index"],
      revision: m["revision"]
    }
  end
end
