# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableBlock do
  @moduledoc """
  Represents a table type block.

  ## Attributes

  *   `annotations` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t()`) - Annotation of the table block.
  *   `body_rows` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow.t())`) - Body rows containing main table content.
  *   `caption` (*type:* `String.t()`) - Table caption/title.
  *   `header_rows` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow.t())`) - Header rows at the top of the table.
  """

  defstruct [:annotations, :body_rows, :caption, :header_rows]

  @type t :: %__MODULE__{
          annotations:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t() | nil,
          body_rows:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow.t()
            )
            | nil,
          caption: String.t() | nil,
          header_rows:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow.t()
            )
            | nil
        }

  @wire %{body_rows: "bodyRows", header_rows: "headerRows"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      annotations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.decode(
          m["annotations"]
        ),
      body_rows:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow.decode(
          m["bodyRows"]
        ),
      caption: m["caption"],
      header_rows:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow.decode(
          m["headerRows"]
        )
    }
  end
end
