# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3ExportProcessorVersionResponse do
  @moduledoc """
  Response message associated with the ExportProcessorVersion operation.

  ## Attributes

  *   `gcs_uri` (*type:* `String.t()`) - The Cloud Storage URI containing the output artifacts.
  """

  defstruct [:gcs_uri]

  @type t :: %__MODULE__{
          gcs_uri: String.t() | nil
        }

  @wire %{gcs_uri: "gcsUri"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      gcs_uri: m["gcsUri"]
    }
  end
end
