# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkChunkPageFooter do
  @moduledoc """
  Represents the page footer associated with the chunk.

  ## Attributes

  *   `page_span` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkChunkPageSpan.t()`) - Page span of the footer.
  *   `text` (*type:* `String.t()`) - Footer in text format.
  """

  defstruct [:page_span, :text]

  @type t :: %__MODULE__{
          page_span:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkChunkPageSpan.t()
            | nil,
          text: String.t() | nil
        }

  @wire %{page_span: "pageSpan"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      page_span:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkChunkPageSpan.decode(
          m["pageSpan"]
        ),
      text: m["text"]
    }
  end
end
