# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorTypeLocationInfo do
  @moduledoc """
  The location information about where the processor is available.

  ## Attributes

  *   `location_id` (*type:* `String.t()`) - The location ID. For supported locations, refer to [regional and multi-regional support](https://cloud.google.com/document-ai/docs/regions).
  """

  defstruct [:location_id]

  @type t :: %__MODULE__{
          location_id: String.t() | nil
        }

  @wire %{location_id: "locationId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      location_id: m["locationId"]
    }
  end
end
