# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationHistory do
  @moduledoc """
  The history of schema generation iterations.

  ## Attributes

  *   `iterations` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationIteration.t())`) - Required. Previous prompt-answers in a chronological order.
  """

  defstruct [:iterations]

  @type t :: %__MODULE__{
          iterations:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationIteration.t())
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      iterations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaGenerationIteration.decode(
          m["iterations"]
        )
    }
  end
end
