# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentOutputConfigGcsOutputConfigShardingConfig do
  @moduledoc """
  The sharding config for the output document.

  ## Attributes

  *   `pages_overlap` (*type:* `integer()`) - The number of overlapping pages between consecutive shards.
  *   `pages_per_shard` (*type:* `integer()`) - The number of pages per shard.
  """

  defstruct [:pages_overlap, :pages_per_shard]

  @type t :: %__MODULE__{
          pages_overlap: integer() | nil,
          pages_per_shard: integer() | nil
        }

  @wire %{pages_overlap: "pagesOverlap", pages_per_shard: "pagesPerShard"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      pages_overlap: m["pagesOverlap"],
      pages_per_shard: m["pagesPerShard"]
    }
  end
end
