# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SummaryOptions do
  @moduledoc """
  Metadata for document summarization.

  ## Attributes

  *   `format` (*type:* `String.t()`) - The format the summary should be in.
  *   `length` (*type:* `String.t()`) - How long the summary should be.
  """

  defstruct [:format, :length]

  @type t :: %__MODULE__{
          format: String.t() | nil,
          length: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      format: m["format"],
      length: m["length"]
    }
  end
end
