# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityType do
  @moduledoc """
  EntityType is the wrapper of a label of the corresponding model with detailed attributes and limitations for entity-based processors. Multiple types can also compose a dependency tree to represent nested types.

  ## Attributes

  *   `base_types` (*type:* `list(String.t())`) - The entity type that this type is derived from. For now, one and only one should be set.
  *   `display_name` (*type:* `String.t()`) - User defined name for the type.
  *   `enum_values` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeEnumValues.t()`) - If specified, lists all the possible values for this entity. This should not be more than a handful of values. If the number of values is >10 or could change frequently, use the `EntityType.value_ontology` field and specify a list of all possible values in a value ontology file.
  *   `name` (*type:* `String.t()`) - Name of the type. It must be unique within the schema file and cannot be a "Common Type". The following naming conventions are used: - Use `snake_casing`. - Name matching is case-sensitive. - Maximum 64 characters. - Must start with a letter. - Allowed characters: ASCII letters `[a-z0-9_-]`. (For backward compatibility, internal infrastructure and tooling can handle any ASCII character.) - The `/` is sometimes used to denote a property of a type. For example `line_item/amount`. This convention is deprecated, but will still be honored for backward compatibility.
  *   `properties` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeProperty.t())`) - Description the nested structure, or composition of an entity.
  """

  defstruct [:base_types, :display_name, :enum_values, :name, :properties]

  @type t :: %__MODULE__{
          base_types: list(String.t()) | nil,
          display_name: String.t() | nil,
          enum_values:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeEnumValues.t()
            | nil,
          name: String.t() | nil,
          properties:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeProperty.t()
            )
            | nil
        }

  @wire %{base_types: "baseTypes", display_name: "displayName", enum_values: "enumValues"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      base_types: m["baseTypes"],
      display_name: m["displayName"],
      enum_values:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeEnumValues.decode(
          m["enumValues"]
        ),
      name: m["name"],
      properties:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityTypeProperty.decode(
          m["properties"]
        )
    }
  end
end
