# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableRow do
  @moduledoc """
  Represents a row in a table.

  ## Attributes

  *   `cells` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableCell.t())`) - A table row is a list of table cells.
  """

  defstruct [:cells]

  @type t :: %__MODULE__{
          cells:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableCell.t()
            )
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      cells:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayoutDocumentLayoutBlockLayoutTableCell.decode(
          m["cells"]
        )
    }
  end
end
