# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldTierMetadata do
  @moduledoc """
  Metadata for the field tier of a property.

  ## Attributes

  *   `tier_level` (*type:* `integer()`) - Integer that indicates the tier of a property. e.g. Invoice has entities that are classified as tier 1 which is the most important, while tier 2 and tier 3 less so. This attribute can be used to filter schema attributes before running eval. e.g. compute F1 score for only tier 1 entities. If not present this attribute should be inferred as 1.
  """

  defstruct [:tier_level]

  @type t :: %__MODULE__{
          tier_level: integer() | nil
        }

  @wire %{tier_level: "tierLevel"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      tier_level: m["tierLevel"]
    }
  end
end
