# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1OcrConfigPremiumFeatures do
  @moduledoc """
  Configurations for premium OCR features.

  ## Attributes

  *   `compute_style_info` (*type:* `boolean()`) - Turn on font identification model and return font style information.
  *   `enable_math_ocr` (*type:* `boolean()`) - Turn on the model that can extract LaTeX math formulas.
  *   `enable_selection_mark_detection` (*type:* `boolean()`) - Turn on selection mark detector in OCR engine. Only available in OCR 2.0 (and later) processors.
  """

  defstruct [:compute_style_info, :enable_math_ocr, :enable_selection_mark_detection]

  @type t :: %__MODULE__{
          compute_style_info: boolean() | nil,
          enable_math_ocr: boolean() | nil,
          enable_selection_mark_detection: boolean() | nil
        }

  @wire %{
    compute_style_info: "computeStyleInfo",
    enable_math_ocr: "enableMathOcr",
    enable_selection_mark_detection: "enableSelectionMarkDetection"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      compute_style_info: m["computeStyleInfo"],
      enable_math_ocr: m["enableMathOcr"],
      enable_selection_mark_detection: m["enableSelectionMarkDetection"]
    }
  end
end
