# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ReviewDocumentRequest do
  @moduledoc """
  Request message for the ReviewDocument method.

  ## Attributes

  *   `document_schema` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.t()`) - The document schema of the human review task.
  *   `enable_schema_validation` (*type:* `boolean()`) - Whether the validation should be performed on the ad-hoc review request.
  *   `inline_document` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t()`) - An inline document proto.
  *   `priority` (*type:* `String.t()`) - The priority of the human review task.
  """

  defstruct [:document_schema, :enable_schema_validation, :inline_document, :priority]

  @type t :: %__MODULE__{
          document_schema:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.t() | nil,
          enable_schema_validation: boolean() | nil,
          inline_document: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.t() | nil,
          priority: String.t() | nil
        }

  @wire %{
    document_schema: "documentSchema",
    enable_schema_validation: "enableSchemaValidation",
    inline_document: "inlineDocument"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      document_schema:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema.decode(m["documentSchema"]),
      enable_schema_validation: m["enableSchemaValidation"],
      inline_document:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document.decode(m["inlineDocument"]),
      priority: m["priority"]
    }
  end
end
