# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3GcsPrefix do
  @moduledoc """
  Specifies all documents on Cloud Storage with a common prefix.

  ## Attributes

  *   `gcs_uri_prefix` (*type:* `String.t()`) - The URI prefix.
  """

  defstruct [:gcs_uri_prefix]

  @type t :: %__MODULE__{
          gcs_uri_prefix: String.t() | nil
        }

  @wire %{gcs_uri_prefix: "gcsUriPrefix"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      gcs_uri_prefix: m["gcsUriPrefix"]
    }
  end
end
