# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkImageChunkField do
  @moduledoc """
  The image chunk field in the chunk.

  ## Attributes

  *   `annotations` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t()`) - Annotation of the image chunk field.
  *   `blob_asset_id` (*type:* `String.t()`) - Optional. Asset id of the inline image. If set, find the image content in the blob_assets field.
  *   `data_uri` (*type:* `String.t()`) - Optional. Data uri of the image. It is composed of four parts: a prefix (data:), a MIME type indicating the type of data, an optional base64 token if non-textual, and the data itself: data:,
  *   `gcs_uri` (*type:* `String.t()`) - Optional. Google Cloud Storage uri of the image.
  """

  defstruct [:annotations, :blob_asset_id, :data_uri, :gcs_uri]

  @type t :: %__MODULE__{
          annotations:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t() | nil,
          blob_asset_id: String.t() | nil,
          data_uri: String.t() | nil,
          gcs_uri: String.t() | nil
        }

  @wire %{blob_asset_id: "blobAssetId", data_uri: "dataUri", gcs_uri: "gcsUri"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      annotations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.decode(
          m["annotations"]
        ),
      blob_asset_id: m["blobAssetId"],
      data_uri: m["dataUri"],
      gcs_uri: m["gcsUri"]
    }
  end
end
