# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPageLayout do
  @moduledoc """
  Visual element describing a layout unit on a page.

  ## Attributes

  *   `bounding_poly` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.t()`) - The bounding polygon for the Layout.
  *   `confidence` (*type:* `number()`) - Confidence of the current Layout within context of the object this layout is for. For example, confidence can be for a single token, a table, a visual element, etc. depending on context. Range `[0, 1]`.
  *   `orientation` (*type:* `String.t()`) - Detected orientation for the Layout.
  *   `text_anchor` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchor.t()`) - Text anchor indexing into the Document.text.
  """

  defstruct [:bounding_poly, :confidence, :orientation, :text_anchor]

  @type t :: %__MODULE__{
          bounding_poly: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.t() | nil,
          confidence: number() | nil,
          orientation: String.t() | nil,
          text_anchor: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchor.t() | nil
        }

  @wire %{bounding_poly: "boundingPoly", text_anchor: "textAnchor"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bounding_poly:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BoundingPoly.decode(m["boundingPoly"]),
      confidence: m["confidence"],
      orientation: m["orientation"],
      text_anchor:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextAnchor.decode(m["textAnchor"])
    }
  end
end
