# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchProcessMetadata do
  @moduledoc """
  The long-running operation metadata for BatchProcessDocuments.

  ## Attributes

  *   `create_time` (*type:* `DateTime.t()`) - The creation time of the operation.
  *   `individual_process_statuses` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchProcessMetadataIndividualProcessStatus.t())`) - The list of response details of each document.
  *   `state` (*type:* `String.t()`) - The state of the current batch processing.
  *   `state_message` (*type:* `String.t()`) - A message providing more details about the current state of processing. For example, the error message if the operation is failed.
  *   `update_time` (*type:* `DateTime.t()`) - The last update time of the operation.
  """

  alias Googly.DocumentAI.Decode

  defstruct [:create_time, :individual_process_statuses, :state, :state_message, :update_time]

  @type t :: %__MODULE__{
          create_time: DateTime.t() | nil,
          individual_process_statuses:
            list(
              Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchProcessMetadataIndividualProcessStatus.t()
            )
            | nil,
          state: String.t() | nil,
          state_message: String.t() | nil,
          update_time: DateTime.t() | nil
        }

  @wire %{
    create_time: "createTime",
    individual_process_statuses: "individualProcessStatuses",
    state_message: "stateMessage",
    update_time: "updateTime"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      create_time: Decode.datetime(m["createTime"]),
      individual_process_statuses:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1BatchProcessMetadataIndividualProcessStatus.decode(
          m["individualProcessStatuses"]
        ),
      state: m["state"],
      state_message: m["stateMessage"],
      update_time: Decode.datetime(m["updateTime"])
    }
  end
end
