# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunkTableChunkField do
  @moduledoc """
  The table chunk field in the chunk.

  ## Attributes

  *   `annotations` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t()`) - Annotation of the table chunk field.
  """

  defstruct [:annotations]

  @type t :: %__MODULE__{
          annotations:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      annotations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations.decode(
          m["annotations"]
        )
    }
  end
end
