# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1TrainProcessorVersionRequestFoundationModelTuningOptions do
  @moduledoc """
  Options to control foundation model tuning of the processor.

  ## Attributes

  *   `learning_rate_multiplier` (*type:* `number()`) - Optional. The multiplier to apply to the recommended learning rate. Valid values are between 0.1 and 10. If not provided, recommended learning rate will be used.
  *   `previous_fine_tuned_processor_version_name` (*type:* `String.t()`) - Optional. Resource name of a previously fine tuned version id to copy the overwritten configs from. The base_processor_version should be newer than the base processor version used to fine tune this provided processor version. Format: `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`.
  *   `train_steps` (*type:* `integer()`) - Optional. The number of steps to run for model tuning. Valid values are between 1 and 400. If not provided, recommended steps will be used.
  """

  defstruct [:learning_rate_multiplier, :previous_fine_tuned_processor_version_name, :train_steps]

  @type t :: %__MODULE__{
          learning_rate_multiplier: number() | nil,
          previous_fine_tuned_processor_version_name: String.t() | nil,
          train_steps: integer() | nil
        }

  @wire %{
    learning_rate_multiplier: "learningRateMultiplier",
    previous_fine_tuned_processor_version_name: "previousFineTunedProcessorVersionName",
    train_steps: "trainSteps"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      learning_rate_multiplier: m["learningRateMultiplier"],
      previous_fine_tuned_processor_version_name: m["previousFineTunedProcessorVersionName"],
      train_steps: m["trainSteps"]
    }
  end
end
