# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocument do
  @moduledoc """
  Represents the chunks that the document is divided into.

  ## Attributes

  *   `chunks` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunk.t())`) - List of chunks.
  """

  defstruct [:chunks]

  @type t :: %__MODULE__{
          chunks:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunk.t())
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      chunks:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocumentChunk.decode(
          m["chunks"]
        )
    }
  end
end
