# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1beta3RevisionRef do
  @moduledoc """
  The revision reference specifies which revision on the document to read.

  ## Attributes

  *   `latest_processor_version` (*type:* `String.t()`) - Reads the revision generated by the processor version. The format takes the full resource name of processor version. `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`
  *   `revision_case` (*type:* `String.t()`) - Reads the revision by the predefined case.
  *   `revision_id` (*type:* `String.t()`) - Reads the revision given by the id.
  """

  defstruct [:latest_processor_version, :revision_case, :revision_id]

  @type t :: %__MODULE__{
          latest_processor_version: String.t() | nil,
          revision_case: String.t() | nil,
          revision_id: String.t() | nil
        }

  @wire %{
    latest_processor_version: "latestProcessorVersion",
    revision_case: "revisionCase",
    revision_id: "revisionId"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      latest_processor_version: m["latestProcessorVersion"],
      revision_case: m["revisionCase"],
      revision_id: m["revisionId"]
    }
  end
end
