# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchema do
  @moduledoc """
  The schema defines the output of the processed document by a processor.

  ## Attributes

  *   `description` (*type:* `String.t()`) - Description of the schema.
  *   `display_name` (*type:* `String.t()`) - Display name to show users.
  *   `document_prompt` (*type:* `String.t()`) - Optional. Document level prompt provided by the user. This custom text is injected into the AI model's prompt to provide extra, document-wide guidance for processing.
  *   `entity_types` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityType.t())`) - Entity types of the schema.
  *   `metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaMetadata.t()`) - Metadata of the schema.
  """

  defstruct [:description, :display_name, :document_prompt, :entity_types, :metadata]

  @type t :: %__MODULE__{
          description: String.t() | nil,
          display_name: String.t() | nil,
          document_prompt: String.t() | nil,
          entity_types:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityType.t())
            | nil,
          metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaMetadata.t() | nil
        }

  @wire %{
    display_name: "displayName",
    document_prompt: "documentPrompt",
    entity_types: "entityTypes"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      description: m["description"],
      display_name: m["displayName"],
      document_prompt: m["documentPrompt"],
      entity_types:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaEntityType.decode(
          m["entityTypes"]
        ),
      metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentSchemaMetadata.decode(
          m["metadata"]
        )
    }
  end
end
