# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntitiesRevision do
  @moduledoc """
  Entity revision.

  ## Attributes

  *   `entities` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntity.t())`) - The entities in this revision.
  *   `entity_validation_output` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput.t()`) - The entity validation output for this revision.
  *   `provenance` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t()`) - Optional. The history of this revision.
  *   `revision_id` (*type:* `String.t()`) - The revision id.
  """

  defstruct [:entities, :entity_validation_output, :provenance, :revision_id]

  @type t :: %__MODULE__{
          entities: list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntity.t()) | nil,
          entity_validation_output:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput.t()
            | nil,
          provenance: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.t() | nil,
          revision_id: String.t() | nil
        }

  @wire %{entity_validation_output: "entityValidationOutput", revision_id: "revisionId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      entities:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntity.decode(m["entities"]),
      entity_validation_output:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput.decode(
          m["entityValidationOutput"]
        ),
      provenance:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentProvenance.decode(m["provenance"]),
      revision_id: m["revisionId"]
    }
  end
end
