# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3PropertyMetadata do
  @moduledoc """
  Metadata about a property.

  ## Attributes

  *   `field_extraction_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadata.t()`) - Field extraction metadata on the property.
  *   `field_tier_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldTierMetadata.t()`) - Field tier metadata on the property
  *   `human_review_labeling_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewLabelingMetadata.t()`) - Human review labeling config on the property.
  *   `human_review_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewValidationMetadata.t()`) - Human review validation config on the property.
  *   `inactive` (*type:* `boolean()`) - Whether the property should be considered as "inactive".
  *   `schema_editability_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEditabilityMetadata.t()`) - Schema editability metadata on the property.
  *   `schema_inference_metadata` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaInferenceMetadata.t()`) - Schema inference metadata on the property.
  """

  defstruct [
    :field_extraction_metadata,
    :field_tier_metadata,
    :human_review_labeling_metadata,
    :human_review_metadata,
    :inactive,
    :schema_editability_metadata,
    :schema_inference_metadata
  ]

  @type t :: %__MODULE__{
          field_extraction_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadata.t()
            | nil,
          field_tier_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldTierMetadata.t() | nil,
          human_review_labeling_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewLabelingMetadata.t()
            | nil,
          human_review_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewValidationMetadata.t()
            | nil,
          inactive: boolean() | nil,
          schema_editability_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEditabilityMetadata.t()
            | nil,
          schema_inference_metadata:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaInferenceMetadata.t()
            | nil
        }

  @wire %{
    field_extraction_metadata: "fieldExtractionMetadata",
    field_tier_metadata: "fieldTierMetadata",
    human_review_labeling_metadata: "humanReviewLabelingMetadata",
    human_review_metadata: "humanReviewMetadata",
    schema_editability_metadata: "schemaEditabilityMetadata",
    schema_inference_metadata: "schemaInferenceMetadata"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      field_extraction_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldExtractionMetadata.decode(
          m["fieldExtractionMetadata"]
        ),
      field_tier_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3FieldTierMetadata.decode(
          m["fieldTierMetadata"]
        ),
      human_review_labeling_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewLabelingMetadata.decode(
          m["humanReviewLabelingMetadata"]
        ),
      human_review_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3HumanReviewValidationMetadata.decode(
          m["humanReviewMetadata"]
        ),
      inactive: m["inactive"],
      schema_editability_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaEditabilityMetadata.decode(
          m["schemaEditabilityMetadata"]
        ),
      schema_inference_metadata:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiUiv1beta3SchemaInferenceMetadata.decode(
          m["schemaInferenceMetadata"]
        )
    }
  end
end
