# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessOptionsLayoutConfigChunkingConfig do
  @moduledoc """
  Serving config for chunking.

  ## Attributes

  *   `chunk_size` (*type:* `integer()`) - Optional. The chunk sizes to use when splitting documents, in order of level.
  *   `include_ancestor_headings` (*type:* `boolean()`) - Optional. Whether or not to include ancestor headings when splitting.
  """

  defstruct [:chunk_size, :include_ancestor_headings]

  @type t :: %__MODULE__{
          chunk_size: integer() | nil,
          include_ancestor_headings: boolean() | nil
        }

  @wire %{chunk_size: "chunkSize", include_ancestor_headings: "includeAncestorHeadings"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      chunk_size: m["chunkSize"],
      include_ancestor_headings: m["includeAncestorHeadings"]
    }
  end
end
