# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1FetchProcessorTypesResponse do
  @moduledoc """
  Response message for the FetchProcessorTypes method.

  ## Attributes

  *   `processor_types` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType.t())`) - The list of processor types.
  """

  defstruct [:processor_types]

  @type t :: %__MODULE__{
          processor_types:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType.t()) | nil
        }

  @wire %{processor_types: "processorTypes"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      processor_types:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ProcessorType.decode(m["processorTypes"])
    }
  end
end
