# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1NormalizedVertex do
  @moduledoc """
  A vertex represents a 2D point in the image. NOTE: the normalized vertex coordinates are relative to the original image and range from 0 to 1.

  ## Attributes

  *   `x` (*type:* `number()`) - X coordinate.
  *   `y` (*type:* `number()`) - Y coordinate (starts from the top of the image).
  """

  defstruct [:x, :y]

  @type t :: %__MODULE__{
          x: number() | nil,
          y: number() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      x: m["x"],
      y: m["y"]
    }
  end
end
