# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1TrainProcessorVersionRequestCustomDocumentExtractionOptions do
  @moduledoc """
  Options to control the training of the Custom Document Extraction (CDE) Processor.

  ## Attributes

  *   `training_method` (*type:* `String.t()`) - Optional. Training method to use for CDE training.
  """

  defstruct [:training_method]

  @type t :: %__MODULE__{
          training_method: String.t() | nil
        }

  @wire %{training_method: "trainingMethod"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      training_method: m["trainingMethod"]
    }
  end
end
