# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Document do
  @moduledoc """
  Document represents the canonical document resource in Document AI. It is an interchange format that provides insights into documents and allows for collaboration between users and Document AI to iterate and optimize for quality.

  ## Attributes

  *   `blob_assets` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentBlobAsset.t())`) - Optional. The blob assets in this document. This is used to store the content of the inline blobs in this document, for example, image bytes, such that it can be referenced by other fields in the document via asset id.
  *   `chunked_document` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocument.t()`) - Document chunked based on chunking config.
  *   `content` (*type:* `String.t()`) - Optional. Inline document content, represented as a stream of bytes. Note: As with all `bytes` fields, protobuffers use a pure binary representation, whereas JSON representations use base64.
  *   `docid` (*type:* `String.t()`) - Optional. An internal identifier for document. Should be loggable (no PII).
  *   `document_layout` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayout.t()`) - Parsed layout of the document.
  *   `entities` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntity.t())`) - A list of entities detected on Document.text. For document shards, entities in this list may cross shard boundaries.
  *   `entities_revision_id` (*type:* `String.t()`) - The entity revision ID that `document.entities` field is based on. If this field is set and `entities_revisions` is not empty, the entities in `document.entities` field are the entities in the entity revision with this id and `document.entity_validation_output` field is the `entity_validation_output` field in this entity revision.
  *   `entities_revisions` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntitiesRevision.t())`) - A list of entity revisions. The entity revisions are appended to the document in the processing order. This field can be used for comparing the entity extraction results at different stages of the processing.
  *   `entity_relations` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityRelation.t())`) - Placeholder. Relationship among Document.entities.
  *   `entity_validation_output` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput.t()`) - The entity validation output for the document. This is the validation output for `document.entities` field.
  *   `error` (*type:* `Googly.DocumentAI.Model.GoogleRpcStatus.t()`) - Any error that occurred while processing this document.
  *   `mime_type` (*type:* `String.t()`) - An IANA published [media type (MIME type)](https://www.iana.org/assignments/media-types/media-types.xhtml).
  *   `pages` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPage.t())`) - Visual page layout for the Document.
  *   `revisions` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentRevision.t())`) - Placeholder. Revision history of this document.
  *   `shard_info` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentShardInfo.t()`) - Information about the sharding if this document is sharded part of a larger document. If the document is not sharded, this message is not specified.
  *   `text` (*type:* `String.t()`) - Optional. UTF-8 encoded text in reading order from the document.
  *   `text_changes` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextChange.t())`) - Placeholder. A list of text corrections made to Document.text. This is usually used for annotating corrections to OCR mistakes. Text changes for a given revision may not overlap with each other.
  *   `text_styles` (*type:* `list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentStyle.t())`) - Styles for the Document.text.
  *   `uri` (*type:* `String.t()`) - Optional. Currently supports Google Cloud Storage URI of the form `gs://bucket_name/object_name`. Object versioning is not supported. For more information, refer to [Google Cloud Storage Request URIs](https://cloud.google.com/storage/docs/reference-uris).
  """

  defstruct [
    :blob_assets,
    :chunked_document,
    :content,
    :docid,
    :document_layout,
    :entities,
    :entities_revision_id,
    :entities_revisions,
    :entity_relations,
    :entity_validation_output,
    :error,
    :mime_type,
    :pages,
    :revisions,
    :shard_info,
    :text,
    :text_changes,
    :text_styles,
    :uri
  ]

  @type t :: %__MODULE__{
          blob_assets:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentBlobAsset.t()) | nil,
          chunked_document:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocument.t() | nil,
          content: String.t() | nil,
          docid: String.t() | nil,
          document_layout:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayout.t() | nil,
          entities: list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntity.t()) | nil,
          entities_revision_id: String.t() | nil,
          entities_revisions:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntitiesRevision.t())
            | nil,
          entity_relations:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityRelation.t()) | nil,
          entity_validation_output:
            Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput.t()
            | nil,
          error: Googly.DocumentAI.Model.GoogleRpcStatus.t() | nil,
          mime_type: String.t() | nil,
          pages: list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPage.t()) | nil,
          revisions:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentRevision.t()) | nil,
          shard_info: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentShardInfo.t() | nil,
          text: String.t() | nil,
          text_changes:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextChange.t()) | nil,
          text_styles:
            list(Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentStyle.t()) | nil,
          uri: String.t() | nil
        }

  @wire %{
    blob_assets: "blobAssets",
    chunked_document: "chunkedDocument",
    document_layout: "documentLayout",
    entities_revision_id: "entitiesRevisionId",
    entities_revisions: "entitiesRevisions",
    entity_relations: "entityRelations",
    entity_validation_output: "entityValidationOutput",
    mime_type: "mimeType",
    shard_info: "shardInfo",
    text_changes: "textChanges",
    text_styles: "textStyles"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      blob_assets:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentBlobAsset.decode(m["blobAssets"]),
      chunked_document:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentChunkedDocument.decode(
          m["chunkedDocument"]
        ),
      content: m["content"],
      docid: m["docid"],
      document_layout:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentDocumentLayout.decode(
          m["documentLayout"]
        ),
      entities:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntity.decode(m["entities"]),
      entities_revision_id: m["entitiesRevisionId"],
      entities_revisions:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntitiesRevision.decode(
          m["entitiesRevisions"]
        ),
      entity_relations:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityRelation.decode(
          m["entityRelations"]
        ),
      entity_validation_output:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentEntityValidationOutput.decode(
          m["entityValidationOutput"]
        ),
      error: Googly.DocumentAI.Model.GoogleRpcStatus.decode(m["error"]),
      mime_type: m["mimeType"],
      pages: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentPage.decode(m["pages"]),
      revisions:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentRevision.decode(m["revisions"]),
      shard_info:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentShardInfo.decode(m["shardInfo"]),
      text: m["text"],
      text_changes:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentTextChange.decode(m["textChanges"]),
      text_styles:
        Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentStyle.decode(m["textStyles"]),
      uri: m["uri"]
    }
  end
end
