# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Model.GoogleCloudDocumentaiV1DocumentAnnotations do
  @moduledoc """
  Represents the annotation of a block or a chunk.

  ## Attributes

  *   `description` (*type:* `String.t()`) - The description of the content with this annotation.
  """

  defstruct [:description]

  @type t :: %__MODULE__{
          description: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      description: m["description"]
    }
  end
end
