# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Projects.ServiceAccount do
  @moduledoc """
  Endpoints for the `Projects.ServiceAccount` resource.
  """

  alias Googly.CloudStorage.Request

  @doc """
  Get the email address of this project's Google Cloud Storage service account.

  ## Parameters

  *   `project_id` (*type:* `String.t()`) - Project ID
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.ServiceAccount{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec get(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.ServiceAccount.t()} | {:error, term()}
  def get(project_id, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/projects/{projectId}/serviceAccount",
      path_params: %{"projectId" => URI.encode(project_id, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.ServiceAccount,
      opts: opts
    )
  end
end
