# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketLogging do
  @moduledoc """
  The bucket's logging configuration, which defines the destination bucket and optional name prefix for the current bucket's logs.

  ## Attributes

  *   `log_bucket` (*type:* `String.t()`) - The destination bucket where the current bucket's logs should be placed.
  *   `log_object_prefix` (*type:* `String.t()`) - A prefix for log object names.
  """

  defstruct [:log_bucket, :log_object_prefix]

  @type t :: %__MODULE__{
          log_bucket: String.t() | nil,
          log_object_prefix: String.t() | nil
        }

  @wire %{log_bucket: "logBucket", log_object_prefix: "logObjectPrefix"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      log_bucket: m["logBucket"],
      log_object_prefix: m["logObjectPrefix"]
    }
  end
end
