# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketBilling do
  @moduledoc """
  The bucket's billing configuration.

  ## Attributes

  *   `requester_pays` (*type:* `boolean()`) - When set to true, Requester Pays is enabled for this bucket.
  """

  defstruct [:requester_pays]

  @type t :: %__MODULE__{
          requester_pays: boolean() | nil
        }

  @wire %{requester_pays: "requesterPays"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      requester_pays: m["requesterPays"]
    }
  end
end
