# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketCors do
  @moduledoc """


  ## Attributes

  *   `max_age_seconds` (*type:* `integer()`) - The value, in seconds, to return in the  Access-Control-Max-Age header used in preflight responses.
  *   `method` (*type:* `list(String.t())`) - The list of HTTP methods on which to include CORS response headers, (GET, OPTIONS, POST, etc) Note: "*" is permitted in the list of methods, and means "any method".
  *   `origin` (*type:* `list(String.t())`) - The list of Origins eligible to receive CORS response headers. Note: "*" is permitted in the list of origins, and means "any Origin".
  *   `response_header` (*type:* `list(String.t())`) - The list of HTTP headers other than the simple response headers to give permission for the user-agent to share across domains.
  """

  defstruct [:max_age_seconds, :method, :origin, :response_header]

  @type t :: %__MODULE__{
          max_age_seconds: integer() | nil,
          method: list(String.t()) | nil,
          origin: list(String.t()) | nil,
          response_header: list(String.t()) | nil
        }

  @wire %{max_age_seconds: "maxAgeSeconds", response_header: "responseHeader"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      max_age_seconds: m["maxAgeSeconds"],
      method: m["method"],
      origin: m["origin"],
      response_header: m["responseHeader"]
    }
  end
end
