# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketEncryptionCustomerManagedEncryptionEnforcementConfig do
  @moduledoc """
  If set, the new objects created in this bucket must comply with this enforcement config. Changing this has no effect on existing objects; it applies to new objects only. If omitted, the new objects are allowed to be encrypted with Customer Managed Encryption type by default.

  ## Attributes

  *   `effective_time` (*type:* `DateTime.t()`) - Server-determined value that indicates the time from which configuration was enforced and effective. This value is in RFC 3339 format.
  *   `restriction_mode` (*type:* `String.t()`) - Restriction mode for Customer-Managed Encryption Keys. Defaults to NotRestricted.
  """

  alias Googly.CloudStorage.Decode

  defstruct [:effective_time, :restriction_mode]

  @type t :: %__MODULE__{
          effective_time: DateTime.t() | nil,
          restriction_mode: String.t() | nil
        }

  @wire %{effective_time: "effectiveTime", restriction_mode: "restrictionMode"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      effective_time: Decode.datetime(m["effectiveTime"]),
      restriction_mode: m["restrictionMode"]
    }
  end
end
