# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketLifecycle do
  @moduledoc """
  The bucket's lifecycle configuration. See [Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) for more information.

  ## Attributes

  *   `rule` (*type:* `list(Googly.CloudStorage.Model.BucketLifecycleRule.t())`) - A lifecycle management rule, which is made of an action to take and the condition(s) under which the action will be taken.
  """

  defstruct [:rule]

  @type t :: %__MODULE__{
          rule: list(Googly.CloudStorage.Model.BucketLifecycleRule.t()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      rule: Googly.CloudStorage.Model.BucketLifecycleRule.decode(m["rule"])
    }
  end
end
