# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketObjectRetention do
  @moduledoc """
  The bucket's object retention config.

  ## Attributes

  *   `mode` (*type:* `String.t()`) - The bucket's object retention mode. Can be Enabled.
  """

  defstruct [:mode]

  @type t :: %__MODULE__{
          mode: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      mode: m["mode"]
    }
  end
end
