# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketIamConfigurationUniformBucketLevelAccess do
  @moduledoc """
  The bucket's uniform bucket-level access configuration.

  ## Attributes

  *   `enabled` (*type:* `boolean()`) - If set, access is controlled only by bucket-level or above IAM policies.
  *   `locked_time` (*type:* `DateTime.t()`) - The deadline for changing iamConfiguration.uniformBucketLevelAccess.enabled from true to false in RFC 3339  format. iamConfiguration.uniformBucketLevelAccess.enabled may be changed from true to false until the locked time, after which the field is immutable.
  """

  alias Googly.CloudStorage.Decode

  defstruct [:enabled, :locked_time]

  @type t :: %__MODULE__{
          enabled: boolean() | nil,
          locked_time: DateTime.t() | nil
        }

  @wire %{locked_time: "lockedTime"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      enabled: m["enabled"],
      locked_time: Decode.datetime(m["lockedTime"])
    }
  end
end
