# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketAccessControl do
  @moduledoc """
  An access-control entry.

  ## Attributes

  *   `bucket` (*type:* `String.t()`) - The name of the bucket.
  *   `domain` (*type:* `String.t()`) - The domain associated with the entity, if any.
  *   `email` (*type:* `String.t()`) - The email address associated with the entity, if any.
  *   `entity` (*type:* `String.t()`) - The entity holding the permission, in one of the following forms: 
      - user-userId 
      - user-email 
      - group-groupId 
      - group-email 
      - domain-domain 
      - project-team-projectId 
      - allUsers 
      - allAuthenticatedUsers Examples: 
      - The user liz@example.com would be user-liz@example.com. 
      - The group example@googlegroups.com would be group-example@googlegroups.com. 
      - To refer to all members of the Google Apps for Business domain example.com, the entity would be domain-example.com.
  *   `entity_id` (*type:* `String.t()`) - The ID for the entity, if any.
  *   `etag` (*type:* `String.t()`) - HTTP 1.1 Entity tag for the access-control entry.
  *   `id` (*type:* `String.t()`) - The ID of the access-control entry.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For bucket access control entries, this is always storage#bucketAccessControl.
  *   `project_team` (*type:* `Googly.CloudStorage.Model.BucketAccessControlProjectTeam.t()`) - The project team associated with the entity, if any.
  *   `role` (*type:* `String.t()`) - The access permission for the entity.
  *   `self_link` (*type:* `String.t()`) - The link to this access-control entry.
  """

  defstruct [
    :bucket,
    :domain,
    :email,
    :entity,
    :entity_id,
    :etag,
    :id,
    :kind,
    :project_team,
    :role,
    :self_link
  ]

  @type t :: %__MODULE__{
          bucket: String.t() | nil,
          domain: String.t() | nil,
          email: String.t() | nil,
          entity: String.t() | nil,
          entity_id: String.t() | nil,
          etag: String.t() | nil,
          id: String.t() | nil,
          kind: String.t() | nil,
          project_team: Googly.CloudStorage.Model.BucketAccessControlProjectTeam.t() | nil,
          role: String.t() | nil,
          self_link: String.t() | nil
        }

  @wire %{entity_id: "entityId", project_team: "projectTeam", self_link: "selfLink"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bucket: m["bucket"],
      domain: m["domain"],
      email: m["email"],
      entity: m["entity"],
      entity_id: m["entityId"],
      etag: m["etag"],
      id: m["id"],
      kind: m["kind"],
      project_team:
        Googly.CloudStorage.Model.BucketAccessControlProjectTeam.decode(m["projectTeam"]),
      role: m["role"],
      self_link: m["selfLink"]
    }
  end
end
