# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketLifecycleRuleAction do
  @moduledoc """
  The action to take.

  ## Attributes

  *   `storage_class` (*type:* `String.t()`) - Target storage class. Required iff the type of the action is SetStorageClass.
  *   `type` (*type:* `String.t()`) - Type of the action. Currently, only Delete, SetStorageClass, and AbortIncompleteMultipartUpload are supported.
  """

  defstruct [:storage_class, :type]

  @type t :: %__MODULE__{
          storage_class: String.t() | nil,
          type: String.t() | nil
        }

  @wire %{storage_class: "storageClass"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      storage_class: m["storageClass"],
      type: m["type"]
    }
  end
end
