# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketLifecycleRule do
  @moduledoc """


  ## Attributes

  *   `action` (*type:* `Googly.CloudStorage.Model.BucketLifecycleRuleAction.t()`) - The action to take.
  *   `condition` (*type:* `Googly.CloudStorage.Model.BucketLifecycleRuleCondition.t()`) - The condition(s) under which the action will be taken.
  """

  defstruct [:action, :condition]

  @type t :: %__MODULE__{
          action: Googly.CloudStorage.Model.BucketLifecycleRuleAction.t() | nil,
          condition: Googly.CloudStorage.Model.BucketLifecycleRuleCondition.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      action: Googly.CloudStorage.Model.BucketLifecycleRuleAction.decode(m["action"]),
      condition: Googly.CloudStorage.Model.BucketLifecycleRuleCondition.decode(m["condition"])
    }
  end
end
