# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketAccessControlProjectTeam do
  @moduledoc """
  The project team associated with the entity, if any.

  ## Attributes

  *   `project_number` (*type:* `String.t()`) - The project number.
  *   `team` (*type:* `String.t()`) - The team.
  """

  defstruct [:project_number, :team]

  @type t :: %__MODULE__{
          project_number: String.t() | nil,
          team: String.t() | nil
        }

  @wire %{project_number: "projectNumber"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      project_number: m["projectNumber"],
      team: m["team"]
    }
  end
end
