# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketLifecycleRuleCondition do
  @moduledoc """
  The condition(s) under which the action will be taken.

  ## Attributes

  *   `age` (*type:* `integer()`) - Age of an object (in days). This condition is satisfied when an object reaches the specified age.
  *   `created_before` (*type:* `Date.t()`) - A date in RFC 3339 format with only the date part (for instance, "2013-01-15"). This condition is satisfied when an object is created before midnight of the specified date in UTC.
  *   `custom_time_before` (*type:* `Date.t()`) - A date in RFC 3339 format with only the date part (for instance, "2013-01-15"). This condition is satisfied when the custom time on an object is before this date in UTC.
  *   `days_since_custom_time` (*type:* `integer()`) - Number of days elapsed since the user-specified timestamp set on an object. The condition is satisfied if the days elapsed is at least this number. If no custom timestamp is specified on an object, the condition does not apply.
  *   `days_since_noncurrent_time` (*type:* `integer()`) - Number of days elapsed since the noncurrent timestamp of an object. The condition is satisfied if the days elapsed is at least this number. This condition is relevant only for versioned objects. The value of the field must be a nonnegative integer. If it's zero, the object version will become eligible for Lifecycle action as soon as it becomes noncurrent.
  *   `is_live` (*type:* `boolean()`) - Relevant only for versioned objects. If the value is true, this condition matches live objects; if the value is false, it matches archived objects.
  *   `matches_pattern` (*type:* `String.t()`) - A regular expression that satisfies the RE2 syntax. This condition is satisfied when the name of the object matches the RE2 pattern. Note: This feature is currently in the "Early Access" launch stage and is only available to a whitelisted set of users; that means that this feature may be changed in backward-incompatible ways and that it is not guaranteed to be released.
  *   `matches_prefix` (*type:* `list(String.t())`) - List of object name prefixes. This condition will be satisfied when at least one of the prefixes exactly matches the beginning of the object name.
  *   `matches_storage_class` (*type:* `list(String.t())`) - Objects having any of the storage classes specified by this condition will be matched. Values include MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE, STANDARD, and DURABLE_REDUCED_AVAILABILITY.
  *   `matches_suffix` (*type:* `list(String.t())`) - List of object name suffixes. This condition will be satisfied when at least one of the suffixes exactly matches the end of the object name.
  *   `noncurrent_time_before` (*type:* `Date.t()`) - A date in RFC 3339 format with only the date part (for instance, "2013-01-15"). This condition is satisfied when the noncurrent time on an object is before this date in UTC. This condition is relevant only for versioned objects.
  *   `num_newer_versions` (*type:* `integer()`) - Relevant only for versioned objects. If the value is N, this condition is satisfied when there are at least N versions (including the live version) newer than this version of the object.
  *   `size_above_bytes` (*type:* `String.t()`) - Objects having a size greater than this value in bytes will be matched.
  *   `size_below_bytes` (*type:* `String.t()`) - Objects having a size less than this value in bytes will be matched.
  """

  alias Googly.CloudStorage.Decode

  defstruct [
    :age,
    :created_before,
    :custom_time_before,
    :days_since_custom_time,
    :days_since_noncurrent_time,
    :is_live,
    :matches_pattern,
    :matches_prefix,
    :matches_storage_class,
    :matches_suffix,
    :noncurrent_time_before,
    :num_newer_versions,
    :size_above_bytes,
    :size_below_bytes
  ]

  @type t :: %__MODULE__{
          age: integer() | nil,
          created_before: Date.t() | nil,
          custom_time_before: Date.t() | nil,
          days_since_custom_time: integer() | nil,
          days_since_noncurrent_time: integer() | nil,
          is_live: boolean() | nil,
          matches_pattern: String.t() | nil,
          matches_prefix: list(String.t()) | nil,
          matches_storage_class: list(String.t()) | nil,
          matches_suffix: list(String.t()) | nil,
          noncurrent_time_before: Date.t() | nil,
          num_newer_versions: integer() | nil,
          size_above_bytes: String.t() | nil,
          size_below_bytes: String.t() | nil
        }

  @wire %{
    created_before: "createdBefore",
    custom_time_before: "customTimeBefore",
    days_since_custom_time: "daysSinceCustomTime",
    days_since_noncurrent_time: "daysSinceNoncurrentTime",
    is_live: "isLive",
    matches_pattern: "matchesPattern",
    matches_prefix: "matchesPrefix",
    matches_storage_class: "matchesStorageClass",
    matches_suffix: "matchesSuffix",
    noncurrent_time_before: "noncurrentTimeBefore",
    num_newer_versions: "numNewerVersions",
    size_above_bytes: "sizeAboveBytes",
    size_below_bytes: "sizeBelowBytes"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      age: m["age"],
      created_before: Decode.date(m["createdBefore"]),
      custom_time_before: Decode.date(m["customTimeBefore"]),
      days_since_custom_time: m["daysSinceCustomTime"],
      days_since_noncurrent_time: m["daysSinceNoncurrentTime"],
      is_live: m["isLive"],
      matches_pattern: m["matchesPattern"],
      matches_prefix: m["matchesPrefix"],
      matches_storage_class: m["matchesStorageClass"],
      matches_suffix: m["matchesSuffix"],
      noncurrent_time_before: Decode.date(m["noncurrentTimeBefore"]),
      num_newer_versions: m["numNewerVersions"],
      size_above_bytes: m["sizeAboveBytes"],
      size_below_bytes: m["sizeBelowBytes"]
    }
  end
end
