# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketWebsite do
  @moduledoc """
  The bucket's website configuration, controlling how the service behaves when accessing bucket contents as a web site. See the [Static Website Examples](https://cloud.google.com/storage/docs/static-website) for more information.

  ## Attributes

  *   `main_page_suffix` (*type:* `String.t()`) - If the requested object path is missing, the service will ensure the path has a trailing '/', append this suffix, and attempt to retrieve the resulting object. This allows the creation of index.html objects to represent directory pages.
  *   `not_found_page` (*type:* `String.t()`) - If the requested object path is missing, and any mainPageSuffix object is missing, if applicable, the service will return the named object from this bucket as the content for a 404 Not Found result.
  """

  defstruct [:main_page_suffix, :not_found_page]

  @type t :: %__MODULE__{
          main_page_suffix: String.t() | nil,
          not_found_page: String.t() | nil
        }

  @wire %{main_page_suffix: "mainPageSuffix", not_found_page: "notFoundPage"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      main_page_suffix: m["mainPageSuffix"],
      not_found_page: m["notFoundPage"]
    }
  end
end
