# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketHierarchicalNamespace do
  @moduledoc """
  The bucket's hierarchical namespace configuration.

  ## Attributes

  *   `enabled` (*type:* `boolean()`) - When set to true, hierarchical namespace is enabled for this bucket.
  """

  defstruct [:enabled]

  @type t :: %__MODULE__{
          enabled: boolean() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      enabled: m["enabled"]
    }
  end
end
