# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketEncryption do
  @moduledoc """
  Encryption configuration for a bucket.

  ## Attributes

  *   `customer_managed_encryption_enforcement_config` (*type:* `Googly.CloudStorage.Model.BucketEncryptionCustomerManagedEncryptionEnforcementConfig.t()`) - If set, the new objects created in this bucket must comply with this enforcement config. Changing this has no effect on existing objects; it applies to new objects only. If omitted, the new objects are allowed to be encrypted with Customer Managed Encryption type by default.
  *   `customer_supplied_encryption_enforcement_config` (*type:* `Googly.CloudStorage.Model.BucketEncryptionCustomerSuppliedEncryptionEnforcementConfig.t()`) - If set, the new objects created in this bucket must comply with this enforcement config. Changing this has no effect on existing objects; it applies to new objects only. If omitted, the new objects are allowed to be encrypted with Customer Supplied Encryption type by default.
  *   `default_kms_key_name` (*type:* `String.t()`) - A Cloud KMS key that will be used to encrypt objects inserted into this bucket, if no encryption method is specified.
  *   `google_managed_encryption_enforcement_config` (*type:* `Googly.CloudStorage.Model.BucketEncryptionGoogleManagedEncryptionEnforcementConfig.t()`) - If set, the new objects created in this bucket must comply with this enforcement config. Changing this has no effect on existing objects; it applies to new objects only. If omitted, the new objects are allowed to be encrypted with Google Managed Encryption type by default.
  """

  defstruct [
    :customer_managed_encryption_enforcement_config,
    :customer_supplied_encryption_enforcement_config,
    :default_kms_key_name,
    :google_managed_encryption_enforcement_config
  ]

  @type t :: %__MODULE__{
          customer_managed_encryption_enforcement_config:
            Googly.CloudStorage.Model.BucketEncryptionCustomerManagedEncryptionEnforcementConfig.t()
            | nil,
          customer_supplied_encryption_enforcement_config:
            Googly.CloudStorage.Model.BucketEncryptionCustomerSuppliedEncryptionEnforcementConfig.t()
            | nil,
          default_kms_key_name: String.t() | nil,
          google_managed_encryption_enforcement_config:
            Googly.CloudStorage.Model.BucketEncryptionGoogleManagedEncryptionEnforcementConfig.t()
            | nil
        }

  @wire %{
    customer_managed_encryption_enforcement_config: "customerManagedEncryptionEnforcementConfig",
    customer_supplied_encryption_enforcement_config:
      "customerSuppliedEncryptionEnforcementConfig",
    default_kms_key_name: "defaultKmsKeyName",
    google_managed_encryption_enforcement_config: "googleManagedEncryptionEnforcementConfig"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      customer_managed_encryption_enforcement_config:
        Googly.CloudStorage.Model.BucketEncryptionCustomerManagedEncryptionEnforcementConfig.decode(
          m["customerManagedEncryptionEnforcementConfig"]
        ),
      customer_supplied_encryption_enforcement_config:
        Googly.CloudStorage.Model.BucketEncryptionCustomerSuppliedEncryptionEnforcementConfig.decode(
          m["customerSuppliedEncryptionEnforcementConfig"]
        ),
      default_kms_key_name: m["defaultKmsKeyName"],
      google_managed_encryption_enforcement_config:
        Googly.CloudStorage.Model.BucketEncryptionGoogleManagedEncryptionEnforcementConfig.decode(
          m["googleManagedEncryptionEnforcementConfig"]
        )
    }
  end
end
