# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketOwner do
  @moduledoc """
  The owner of the bucket. This is always the project team's owner group.

  ## Attributes

  *   `entity` (*type:* `String.t()`) - The entity, in the form project-owner-projectId.
  *   `entity_id` (*type:* `String.t()`) - The ID for the entity.
  """

  defstruct [:entity, :entity_id]

  @type t :: %__MODULE__{
          entity: String.t() | nil,
          entity_id: String.t() | nil
        }

  @wire %{entity_id: "entityId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      entity: m["entity"],
      entity_id: m["entityId"]
    }
  end
end
