# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.Bucket do
  @moduledoc """
  A bucket.

  ## Attributes

  *   `acl` (*type:* `list(Googly.CloudStorage.Model.BucketAccessControl.t())`) - Access controls on the bucket.
  *   `autoclass` (*type:* `Googly.CloudStorage.Model.BucketAutoclass.t()`) - The bucket's Autoclass configuration.
  *   `billing` (*type:* `Googly.CloudStorage.Model.BucketBilling.t()`) - The bucket's billing configuration.
  *   `cors` (*type:* `list(Googly.CloudStorage.Model.BucketCors.t())`) - The bucket's Cross-Origin Resource Sharing (CORS) configuration.
  *   `custom_placement_config` (*type:* `Googly.CloudStorage.Model.BucketCustomPlacementConfig.t()`) - The bucket's custom placement configuration for Custom Dual Regions.
  *   `default_event_based_hold` (*type:* `boolean()`) - The default value for event-based hold on newly created objects in this bucket. Event-based hold is a way to retain objects indefinitely until an event occurs, signified by the hold's release. After being released, such objects will be subject to bucket-level retention (if any). One sample use case of this flag is for banks to hold loan documents for at least 3 years after loan is paid in full. Here, bucket-level retention is 3 years and the event is loan being paid in full. In this example, these objects will be held intact for any number of years until the event has occurred (event-based hold on the object is released) and then 3 more years after that. That means retention duration of the objects begins from the moment event-based hold transitioned from true to false. Objects under event-based hold cannot be deleted, overwritten or archived until the hold is removed.
  *   `default_object_acl` (*type:* `list(Googly.CloudStorage.Model.ObjectAccessControl.t())`) - Default access controls to apply to new objects when no ACL is provided.
  *   `encryption` (*type:* `Googly.CloudStorage.Model.BucketEncryption.t()`) - Encryption configuration for a bucket.
  *   `etag` (*type:* `String.t()`) - HTTP 1.1 Entity tag for the bucket.
  *   `generation` (*type:* `String.t()`) - The generation of this bucket.
  *   `hard_delete_time` (*type:* `DateTime.t()`) - The hard delete time of the bucket in RFC 3339 format.
  *   `hierarchical_namespace` (*type:* `Googly.CloudStorage.Model.BucketHierarchicalNamespace.t()`) - The bucket's hierarchical namespace configuration.
  *   `iam_configuration` (*type:* `Googly.CloudStorage.Model.BucketIamConfiguration.t()`) - The bucket's IAM configuration.
  *   `id` (*type:* `String.t()`) - The ID of the bucket. For buckets, the id and name properties are the same.
  *   `ip_filter` (*type:* `Googly.CloudStorage.Model.BucketIpFilter.t()`) - The bucket's IP filter configuration. Specifies the network sources that are allowed to access the operations on the bucket, as well as its underlying objects. Only enforced when the mode is set to 'Enabled'.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For buckets, this is always storage#bucket.
  *   `labels` (*type:* `map()`) - User-provided labels, in key/value pairs.
  *   `lifecycle` (*type:* `Googly.CloudStorage.Model.BucketLifecycle.t()`) - The bucket's lifecycle configuration. See [Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) for more information.
  *   `location` (*type:* `String.t()`) - The location of the bucket. Object data for objects in the bucket resides in physical storage within this region. Defaults to US. See the [Developer's Guide](https://cloud.google.com/storage/docs/locations) for the authoritative list.
  *   `location_type` (*type:* `String.t()`) - The type of the bucket location.
  *   `logging` (*type:* `Googly.CloudStorage.Model.BucketLogging.t()`) - The bucket's logging configuration, which defines the destination bucket and optional name prefix for the current bucket's logs.
  *   `metageneration` (*type:* `String.t()`) - The metadata generation of this bucket.
  *   `name` (*type:* `String.t()`) - The name of the bucket.
  *   `object_retention` (*type:* `Googly.CloudStorage.Model.BucketObjectRetention.t()`) - The bucket's object retention config.
  *   `owner` (*type:* `Googly.CloudStorage.Model.BucketOwner.t()`) - The owner of the bucket. This is always the project team's owner group.
  *   `project_number` (*type:* `String.t()`) - The project number of the project the bucket belongs to.
  *   `retention_policy` (*type:* `Googly.CloudStorage.Model.BucketRetentionPolicy.t()`) - The bucket's retention policy. The retention policy enforces a minimum retention time for all objects contained in the bucket, based on their creation time. Any attempt to overwrite or delete objects younger than the retention period will result in a PERMISSION_DENIED error. An unlocked retention policy can be modified or removed from the bucket via a storage.buckets.update operation. A locked retention policy cannot be removed or shortened in duration for the lifetime of the bucket. Attempting to remove or decrease period of a locked retention policy will result in a PERMISSION_DENIED error.
  *   `rpo` (*type:* `String.t()`) - The Recovery Point Objective (RPO) of this bucket. Set to ASYNC_TURBO to turn on Turbo Replication on a bucket.
  *   `satisfies_pzi` (*type:* `boolean()`) - Reserved for future use.
  *   `satisfies_pzs` (*type:* `boolean()`) - Reserved for future use.
  *   `self_link` (*type:* `String.t()`) - The URI of this bucket.
  *   `soft_delete_policy` (*type:* `Googly.CloudStorage.Model.BucketSoftDeletePolicy.t()`) - The bucket's soft delete policy, which defines the period of time that soft-deleted objects will be retained, and cannot be permanently deleted.
  *   `soft_delete_time` (*type:* `DateTime.t()`) - The soft delete time of the bucket in RFC 3339 format.
  *   `storage_class` (*type:* `String.t()`) - The bucket's default storage class, used whenever no storageClass is specified for a newly-created object. This defines how objects in the bucket are stored and determines the SLA and the cost of storage. Values include MULTI_REGIONAL, REGIONAL, STANDARD, NEARLINE, COLDLINE, ARCHIVE, and DURABLE_REDUCED_AVAILABILITY. If this value is not specified when the bucket is created, it will default to STANDARD. For more information, see [Storage Classes](https://cloud.google.com/storage/docs/storage-classes).
  *   `time_created` (*type:* `DateTime.t()`) - The creation time of the bucket in RFC 3339 format.
  *   `updated` (*type:* `DateTime.t()`) - The modification time of the bucket in RFC 3339 format.
  *   `versioning` (*type:* `Googly.CloudStorage.Model.BucketVersioning.t()`) - The bucket's versioning configuration.
  *   `website` (*type:* `Googly.CloudStorage.Model.BucketWebsite.t()`) - The bucket's website configuration, controlling how the service behaves when accessing bucket contents as a web site. See the [Static Website Examples](https://cloud.google.com/storage/docs/static-website) for more information.
  """

  alias Googly.CloudStorage.Decode

  defstruct [
    :acl,
    :autoclass,
    :billing,
    :cors,
    :custom_placement_config,
    :default_event_based_hold,
    :default_object_acl,
    :encryption,
    :etag,
    :generation,
    :hard_delete_time,
    :hierarchical_namespace,
    :iam_configuration,
    :id,
    :ip_filter,
    :kind,
    :labels,
    :lifecycle,
    :location,
    :location_type,
    :logging,
    :metageneration,
    :name,
    :object_retention,
    :owner,
    :project_number,
    :retention_policy,
    :rpo,
    :satisfies_pzi,
    :satisfies_pzs,
    :self_link,
    :soft_delete_policy,
    :soft_delete_time,
    :storage_class,
    :time_created,
    :updated,
    :versioning,
    :website
  ]

  @type t :: %__MODULE__{
          acl: list(Googly.CloudStorage.Model.BucketAccessControl.t()) | nil,
          autoclass: Googly.CloudStorage.Model.BucketAutoclass.t() | nil,
          billing: Googly.CloudStorage.Model.BucketBilling.t() | nil,
          cors: list(Googly.CloudStorage.Model.BucketCors.t()) | nil,
          custom_placement_config:
            Googly.CloudStorage.Model.BucketCustomPlacementConfig.t() | nil,
          default_event_based_hold: boolean() | nil,
          default_object_acl: list(Googly.CloudStorage.Model.ObjectAccessControl.t()) | nil,
          encryption: Googly.CloudStorage.Model.BucketEncryption.t() | nil,
          etag: String.t() | nil,
          generation: String.t() | nil,
          hard_delete_time: DateTime.t() | nil,
          hierarchical_namespace: Googly.CloudStorage.Model.BucketHierarchicalNamespace.t() | nil,
          iam_configuration: Googly.CloudStorage.Model.BucketIamConfiguration.t() | nil,
          id: String.t() | nil,
          ip_filter: Googly.CloudStorage.Model.BucketIpFilter.t() | nil,
          kind: String.t() | nil,
          labels: map() | nil,
          lifecycle: Googly.CloudStorage.Model.BucketLifecycle.t() | nil,
          location: String.t() | nil,
          location_type: String.t() | nil,
          logging: Googly.CloudStorage.Model.BucketLogging.t() | nil,
          metageneration: String.t() | nil,
          name: String.t() | nil,
          object_retention: Googly.CloudStorage.Model.BucketObjectRetention.t() | nil,
          owner: Googly.CloudStorage.Model.BucketOwner.t() | nil,
          project_number: String.t() | nil,
          retention_policy: Googly.CloudStorage.Model.BucketRetentionPolicy.t() | nil,
          rpo: String.t() | nil,
          satisfies_pzi: boolean() | nil,
          satisfies_pzs: boolean() | nil,
          self_link: String.t() | nil,
          soft_delete_policy: Googly.CloudStorage.Model.BucketSoftDeletePolicy.t() | nil,
          soft_delete_time: DateTime.t() | nil,
          storage_class: String.t() | nil,
          time_created: DateTime.t() | nil,
          updated: DateTime.t() | nil,
          versioning: Googly.CloudStorage.Model.BucketVersioning.t() | nil,
          website: Googly.CloudStorage.Model.BucketWebsite.t() | nil
        }

  @wire %{
    custom_placement_config: "customPlacementConfig",
    default_event_based_hold: "defaultEventBasedHold",
    default_object_acl: "defaultObjectAcl",
    hard_delete_time: "hardDeleteTime",
    hierarchical_namespace: "hierarchicalNamespace",
    iam_configuration: "iamConfiguration",
    ip_filter: "ipFilter",
    location_type: "locationType",
    object_retention: "objectRetention",
    project_number: "projectNumber",
    retention_policy: "retentionPolicy",
    satisfies_pzi: "satisfiesPZI",
    satisfies_pzs: "satisfiesPZS",
    self_link: "selfLink",
    soft_delete_policy: "softDeletePolicy",
    soft_delete_time: "softDeleteTime",
    storage_class: "storageClass",
    time_created: "timeCreated"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      acl: Googly.CloudStorage.Model.BucketAccessControl.decode(m["acl"]),
      autoclass: Googly.CloudStorage.Model.BucketAutoclass.decode(m["autoclass"]),
      billing: Googly.CloudStorage.Model.BucketBilling.decode(m["billing"]),
      cors: Googly.CloudStorage.Model.BucketCors.decode(m["cors"]),
      custom_placement_config:
        Googly.CloudStorage.Model.BucketCustomPlacementConfig.decode(m["customPlacementConfig"]),
      default_event_based_hold: m["defaultEventBasedHold"],
      default_object_acl:
        Googly.CloudStorage.Model.ObjectAccessControl.decode(m["defaultObjectAcl"]),
      encryption: Googly.CloudStorage.Model.BucketEncryption.decode(m["encryption"]),
      etag: m["etag"],
      generation: m["generation"],
      hard_delete_time: Decode.datetime(m["hardDeleteTime"]),
      hierarchical_namespace:
        Googly.CloudStorage.Model.BucketHierarchicalNamespace.decode(m["hierarchicalNamespace"]),
      iam_configuration:
        Googly.CloudStorage.Model.BucketIamConfiguration.decode(m["iamConfiguration"]),
      id: m["id"],
      ip_filter: Googly.CloudStorage.Model.BucketIpFilter.decode(m["ipFilter"]),
      kind: m["kind"],
      labels: m["labels"],
      lifecycle: Googly.CloudStorage.Model.BucketLifecycle.decode(m["lifecycle"]),
      location: m["location"],
      location_type: m["locationType"],
      logging: Googly.CloudStorage.Model.BucketLogging.decode(m["logging"]),
      metageneration: m["metageneration"],
      name: m["name"],
      object_retention:
        Googly.CloudStorage.Model.BucketObjectRetention.decode(m["objectRetention"]),
      owner: Googly.CloudStorage.Model.BucketOwner.decode(m["owner"]),
      project_number: m["projectNumber"],
      retention_policy:
        Googly.CloudStorage.Model.BucketRetentionPolicy.decode(m["retentionPolicy"]),
      rpo: m["rpo"],
      satisfies_pzi: m["satisfiesPZI"],
      satisfies_pzs: m["satisfiesPZS"],
      self_link: m["selfLink"],
      soft_delete_policy:
        Googly.CloudStorage.Model.BucketSoftDeletePolicy.decode(m["softDeletePolicy"]),
      soft_delete_time: Decode.datetime(m["softDeleteTime"]),
      storage_class: m["storageClass"],
      time_created: Decode.datetime(m["timeCreated"]),
      updated: Decode.datetime(m["updated"]),
      versioning: Googly.CloudStorage.Model.BucketVersioning.decode(m["versioning"]),
      website: Googly.CloudStorage.Model.BucketWebsite.decode(m["website"])
    }
  end
end
