# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketAutoclass do
  @moduledoc """
  The bucket's Autoclass configuration.

  ## Attributes

  *   `enabled` (*type:* `boolean()`) - Whether or not Autoclass is enabled on this bucket
  *   `terminal_storage_class` (*type:* `String.t()`) - The storage class that objects in the bucket eventually transition to if they are not read for a certain length of time. Valid values are NEARLINE and ARCHIVE.
  *   `terminal_storage_class_update_time` (*type:* `DateTime.t()`) - A date and time in RFC 3339 format representing the time of the most recent update to "terminalStorageClass".
  *   `toggle_time` (*type:* `DateTime.t()`) - A date and time in RFC 3339 format representing the instant at which "enabled" was last toggled.
  """

  alias Googly.CloudStorage.Decode

  defstruct [:enabled, :terminal_storage_class, :terminal_storage_class_update_time, :toggle_time]

  @type t :: %__MODULE__{
          enabled: boolean() | nil,
          terminal_storage_class: String.t() | nil,
          terminal_storage_class_update_time: DateTime.t() | nil,
          toggle_time: DateTime.t() | nil
        }

  @wire %{
    terminal_storage_class: "terminalStorageClass",
    terminal_storage_class_update_time: "terminalStorageClassUpdateTime",
    toggle_time: "toggleTime"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      enabled: m["enabled"],
      terminal_storage_class: m["terminalStorageClass"],
      terminal_storage_class_update_time: Decode.datetime(m["terminalStorageClassUpdateTime"]),
      toggle_time: Decode.datetime(m["toggleTime"])
    }
  end
end
