# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketIpFilterVpcNetworkSources do
  @moduledoc """


  ## Attributes

  *   `allowed_ip_cidr_ranges` (*type:* `list(String.t())`) - The list of IPv4, IPv6 cidr ranges subnetworks that are allowed to access the bucket.
  *   `network` (*type:* `String.t()`) - Name of the network. Format: projects/{PROJECT_ID}/global/networks/{NETWORK_NAME}
  """

  defstruct [:allowed_ip_cidr_ranges, :network]

  @type t :: %__MODULE__{
          allowed_ip_cidr_ranges: list(String.t()) | nil,
          network: String.t() | nil
        }

  @wire %{allowed_ip_cidr_ranges: "allowedIpCidrRanges"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      allowed_ip_cidr_ranges: m["allowedIpCidrRanges"],
      network: m["network"]
    }
  end
end
