# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketCustomPlacementConfig do
  @moduledoc """
  The bucket's custom placement configuration for Custom Dual Regions.

  ## Attributes

  *   `data_locations` (*type:* `list(String.t())`) - The list of regional locations in which data is placed.
  """

  defstruct [:data_locations]

  @type t :: %__MODULE__{
          data_locations: list(String.t()) | nil
        }

  @wire %{data_locations: "dataLocations"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      data_locations: m["dataLocations"]
    }
  end
end
