# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketIpFilterPublicNetworkSource do
  @moduledoc """
  The public network source of the bucket's IP filter.

  ## Attributes

  *   `allowed_ip_cidr_ranges` (*type:* `list(String.t())`) - The list of public IPv4, IPv6 cidr ranges that are allowed to access the bucket.
  """

  defstruct [:allowed_ip_cidr_ranges]

  @type t :: %__MODULE__{
          allowed_ip_cidr_ranges: list(String.t()) | nil
        }

  @wire %{allowed_ip_cidr_ranges: "allowedIpCidrRanges"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      allowed_ip_cidr_ranges: m["allowedIpCidrRanges"]
    }
  end
end
