# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.BucketStorageLayout do
  @moduledoc """
  The storage layout configuration of a bucket.

  ## Attributes

  *   `bucket` (*type:* `String.t()`) - The name of the bucket.
  *   `custom_placement_config` (*type:* `Googly.CloudStorage.Model.BucketStorageLayoutCustomPlacementConfig.t()`) - The bucket's custom placement configuration for Custom Dual Regions.
  *   `hierarchical_namespace` (*type:* `Googly.CloudStorage.Model.BucketStorageLayoutHierarchicalNamespace.t()`) - The bucket's hierarchical namespace configuration.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For storage layout, this is always storage#storageLayout.
  *   `location` (*type:* `String.t()`) - The location of the bucket.
  *   `location_type` (*type:* `String.t()`) - The type of the bucket location.
  """

  defstruct [
    :bucket,
    :custom_placement_config,
    :hierarchical_namespace,
    :kind,
    :location,
    :location_type
  ]

  @type t :: %__MODULE__{
          bucket: String.t() | nil,
          custom_placement_config:
            Googly.CloudStorage.Model.BucketStorageLayoutCustomPlacementConfig.t() | nil,
          hierarchical_namespace:
            Googly.CloudStorage.Model.BucketStorageLayoutHierarchicalNamespace.t() | nil,
          kind: String.t() | nil,
          location: String.t() | nil,
          location_type: String.t() | nil
        }

  @wire %{
    custom_placement_config: "customPlacementConfig",
    hierarchical_namespace: "hierarchicalNamespace",
    location_type: "locationType"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bucket: m["bucket"],
      custom_placement_config:
        Googly.CloudStorage.Model.BucketStorageLayoutCustomPlacementConfig.decode(
          m["customPlacementConfig"]
        ),
      hierarchical_namespace:
        Googly.CloudStorage.Model.BucketStorageLayoutHierarchicalNamespace.decode(
          m["hierarchicalNamespace"]
        ),
      kind: m["kind"],
      location: m["location"],
      location_type: m["locationType"]
    }
  end
end
