# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.ComposeRequestSourceObjects do
  @moduledoc """


  ## Attributes

  *   `generation` (*type:* `String.t()`) - The generation of this object to use as the source.
  *   `name` (*type:* `String.t()`) - The source object's name. All source objects must reside in the same bucket.
  *   `object_preconditions` (*type:* `Googly.CloudStorage.Model.ComposeRequestSourceObjectsObjectPreconditions.t()`) - Conditions that must be met for this operation to execute.
  """

  defstruct [:generation, :name, :object_preconditions]

  @type t :: %__MODULE__{
          generation: String.t() | nil,
          name: String.t() | nil,
          object_preconditions:
            Googly.CloudStorage.Model.ComposeRequestSourceObjectsObjectPreconditions.t() | nil
        }

  @wire %{object_preconditions: "objectPreconditions"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      generation: m["generation"],
      name: m["name"],
      object_preconditions:
        Googly.CloudStorage.Model.ComposeRequestSourceObjectsObjectPreconditions.decode(
          m["objectPreconditions"]
        )
    }
  end
end
