# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.ComposeRequest do
  @moduledoc """
  A Compose request.

  ## Attributes

  *   `delete_source_objects` (*type:* `boolean()`) - If true, the source objects will be deleted.
  *   `destination` (*type:* `Googly.CloudStorage.Model.Object.t()`) - Properties of the resulting object.
  *   `kind` (*type:* `String.t()`) - The kind of item this is.
  *   `source_objects` (*type:* `list(Googly.CloudStorage.Model.ComposeRequestSourceObjects.t())`) - The list of source objects that will be concatenated into a single object.
  """

  defstruct [:delete_source_objects, :destination, :kind, :source_objects]

  @type t :: %__MODULE__{
          delete_source_objects: boolean() | nil,
          destination: Googly.CloudStorage.Model.Object.t() | nil,
          kind: String.t() | nil,
          source_objects: list(Googly.CloudStorage.Model.ComposeRequestSourceObjects.t()) | nil
        }

  @wire %{delete_source_objects: "deleteSourceObjects", source_objects: "sourceObjects"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      delete_source_objects: m["deleteSourceObjects"],
      destination: Googly.CloudStorage.Model.Object.decode(m["destination"]),
      kind: m["kind"],
      source_objects:
        Googly.CloudStorage.Model.ComposeRequestSourceObjects.decode(m["sourceObjects"])
    }
  end
end
