# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.ComposeRequestSourceObjectsObjectPreconditions do
  @moduledoc """
  Conditions that must be met for this operation to execute.

  ## Attributes

  *   `if_generation_match` (*type:* `String.t()`) - Only perform the composition if the generation of the source object that would be used matches this value. If this value and a generation are both specified, they must be the same value or the call will fail.
  """

  defstruct [:if_generation_match]

  @type t :: %__MODULE__{
          if_generation_match: String.t() | nil
        }

  @wire %{if_generation_match: "ifGenerationMatch"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      if_generation_match: m["ifGenerationMatch"]
    }
  end
end
