# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.Folder do
  @moduledoc """
  A folder. Only available in buckets with hierarchical namespace enabled.

  ## Attributes

  *   `bucket` (*type:* `String.t()`) - The name of the bucket containing this folder.
  *   `create_time` (*type:* `DateTime.t()`) - The creation time of the folder in RFC 3339 format.
  *   `id` (*type:* `String.t()`) - The ID of the folder, including the bucket name, folder name.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For folders, this is always storage#folder.
  *   `metageneration` (*type:* `String.t()`) - The version of the metadata for this folder. Used for preconditions and for detecting changes in metadata.
  *   `name` (*type:* `String.t()`) - The name of the folder. Required if not specified by URL parameter.
  *   `pending_rename_info` (*type:* `Googly.CloudStorage.Model.FolderPendingRenameInfo.t()`) - Only present if the folder is part of an ongoing rename folder operation. Contains information which can be used to query the operation status.
  *   `self_link` (*type:* `String.t()`) - The link to this folder.
  *   `update_time` (*type:* `DateTime.t()`) - The modification time of the folder metadata in RFC 3339 format.
  """

  alias Googly.CloudStorage.Decode

  defstruct [
    :bucket,
    :create_time,
    :id,
    :kind,
    :metageneration,
    :name,
    :pending_rename_info,
    :self_link,
    :update_time
  ]

  @type t :: %__MODULE__{
          bucket: String.t() | nil,
          create_time: DateTime.t() | nil,
          id: String.t() | nil,
          kind: String.t() | nil,
          metageneration: String.t() | nil,
          name: String.t() | nil,
          pending_rename_info: Googly.CloudStorage.Model.FolderPendingRenameInfo.t() | nil,
          self_link: String.t() | nil,
          update_time: DateTime.t() | nil
        }

  @wire %{
    create_time: "createTime",
    pending_rename_info: "pendingRenameInfo",
    self_link: "selfLink",
    update_time: "updateTime"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bucket: m["bucket"],
      create_time: Decode.datetime(m["createTime"]),
      id: m["id"],
      kind: m["kind"],
      metageneration: m["metageneration"],
      name: m["name"],
      pending_rename_info:
        Googly.CloudStorage.Model.FolderPendingRenameInfo.decode(m["pendingRenameInfo"]),
      self_link: m["selfLink"],
      update_time: Decode.datetime(m["updateTime"])
    }
  end
end
