# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.FolderPendingRenameInfo do
  @moduledoc """
  Only present if the folder is part of an ongoing rename folder operation. Contains information which can be used to query the operation status.

  ## Attributes

  *   `operation_id` (*type:* `String.t()`) - The ID of the rename folder operation.
  """

  defstruct [:operation_id]

  @type t :: %__MODULE__{
          operation_id: String.t() | nil
        }

  @wire %{operation_id: "operationId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      operation_id: m["operationId"]
    }
  end
end
