# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.HmacKey do
  @moduledoc """
  JSON template to produce a JSON-style HMAC Key resource for Create responses.

  ## Attributes

  *   `kind` (*type:* `String.t()`) - The kind of item this is. For HMAC keys, this is always storage#hmacKey.
  *   `metadata` (*type:* `Googly.CloudStorage.Model.HmacKeyMetadata.t()`) - Key metadata.
  *   `secret` (*type:* `String.t()`) - HMAC secret key material.
  """

  defstruct [:kind, :metadata, :secret]

  @type t :: %__MODULE__{
          kind: String.t() | nil,
          metadata: Googly.CloudStorage.Model.HmacKeyMetadata.t() | nil,
          secret: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      kind: m["kind"],
      metadata: Googly.CloudStorage.Model.HmacKeyMetadata.decode(m["metadata"]),
      secret: m["secret"]
    }
  end
end
