# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.Notifications do
  @moduledoc """
  A list of notification subscriptions.

  ## Attributes

  *   `items` (*type:* `list(Googly.CloudStorage.Model.Notification.t())`) - The list of items.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For lists of notifications, this is always storage#notifications.
  """

  defstruct [:items, :kind]

  @type t :: %__MODULE__{
          items: list(Googly.CloudStorage.Model.Notification.t()) | nil,
          kind: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      items: Googly.CloudStorage.Model.Notification.decode(m["items"]),
      kind: m["kind"]
    }
  end
end
