# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.Object do
  @moduledoc """
  An object.

  ## Attributes

  *   `acl` (*type:* `list(Googly.CloudStorage.Model.ObjectAccessControl.t())`) - Access controls on the object.
  *   `bucket` (*type:* `String.t()`) - The name of the bucket containing this object.
  *   `cache_control` (*type:* `String.t()`) - Cache-Control directive for the object data. If omitted, and the object is accessible to all anonymous users, the default will be public, max-age=3600.
  *   `component_count` (*type:* `integer()`) - Number of underlying components that make up this object. Components are accumulated by compose operations.
  *   `content_disposition` (*type:* `String.t()`) - Content-Disposition of the object data.
  *   `content_encoding` (*type:* `String.t()`) - Content-Encoding of the object data.
  *   `content_language` (*type:* `String.t()`) - Content-Language of the object data.
  *   `content_type` (*type:* `String.t()`) - Content-Type of the object data. If an object is stored without a Content-Type, it is served as application/octet-stream.
  *   `contexts` (*type:* `Googly.CloudStorage.Model.ObjectContexts.t()`) - User-defined or system-defined object contexts. Each object context is a key-payload pair, where the key provides the identification and the payload holds the associated value and additional metadata.
  *   `crc32c` (*type:* `String.t()`) - CRC32c checksum, as described in RFC 4960, Appendix B; encoded using base64 in big-endian byte order. For more information about using the CRC32c checksum, see [Data Validation and Change Detection](https://cloud.google.com/storage/docs/data-validation).
  *   `custom_time` (*type:* `DateTime.t()`) - A timestamp in RFC 3339 format specified by the user for an object.
  *   `customer_encryption` (*type:* `Googly.CloudStorage.Model.ObjectCustomerEncryption.t()`) - Metadata of customer-supplied encryption key, if the object is encrypted by such a key.
  *   `etag` (*type:* `String.t()`) - HTTP 1.1 Entity tag for the object.
  *   `event_based_hold` (*type:* `boolean()`) - Whether an object is under event-based hold. Event-based hold is a way to retain objects until an event occurs, which is signified by the hold's release (i.e. this value is set to false). After being released (set to false), such objects will be subject to bucket-level retention (if any). One sample use case of this flag is for banks to hold loan documents for at least 3 years after loan is paid in full. Here, bucket-level retention is 3 years and the event is the loan being paid in full. In this example, these objects will be held intact for any number of years until the event has occurred (event-based hold on the object is released) and then 3 more years after that. That means retention duration of the objects begins from the moment event-based hold transitioned from true to false.
  *   `generation` (*type:* `String.t()`) - The content generation of this object. Used for object versioning.
  *   `hard_delete_time` (*type:* `DateTime.t()`) - This is the time (in the future) when the soft-deleted object will no longer be restorable. It is equal to the soft delete time plus the current soft delete retention duration of the bucket.
  *   `id` (*type:* `String.t()`) - The ID of the object, including the bucket name, object name, and generation number.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For objects, this is always storage#object.
  *   `kms_key_name` (*type:* `String.t()`) - Not currently supported. Specifying the parameter causes the request to fail with status code 400 - Bad Request.
  *   `md5_hash` (*type:* `String.t()`) - MD5 hash of the data; encoded using base64. For more information about using the MD5 hash, see [Data Validation and Change Detection](https://cloud.google.com/storage/docs/data-validation).
  *   `media_link` (*type:* `String.t()`) - Media download link.
  *   `metadata` (*type:* `map()`) - User-provided metadata, in key/value pairs.
  *   `metageneration` (*type:* `String.t()`) - The version of the metadata for this object at this generation. Used for preconditions and for detecting changes in metadata. A metageneration number is only meaningful in the context of a particular generation of a particular object.
  *   `name` (*type:* `String.t()`) - The name of the object. Required if not specified by URL parameter.
  *   `owner` (*type:* `Googly.CloudStorage.Model.ObjectOwner.t()`) - The owner of the object. This will always be the uploader of the object.
  *   `restore_token` (*type:* `String.t()`) - Restore token used to differentiate deleted objects with the same name and generation. This field is only returned for deleted objects in hierarchical namespace buckets.
  *   `retention` (*type:* `Googly.CloudStorage.Model.ObjectRetention.t()`) - A collection of object level retention parameters.
  *   `retention_expiration_time` (*type:* `DateTime.t()`) - A server-determined value that specifies the earliest time that the object's retention period expires. This value is in RFC 3339 format. Note 1: This field is not provided for objects with an active event-based hold, since retention expiration is unknown until the hold is removed. Note 2: This value can be provided even when temporary hold is set (so that the user can reason about policy without having to first unset the temporary hold).
  *   `self_link` (*type:* `String.t()`) - The link to this object.
  *   `size` (*type:* `String.t()`) - Content-Length of the data in bytes.
  *   `soft_delete_time` (*type:* `DateTime.t()`) - The time at which the object became soft-deleted in RFC 3339 format.
  *   `storage_class` (*type:* `String.t()`) - Storage class of the object.
  *   `temporary_hold` (*type:* `boolean()`) - Whether an object is under temporary hold. While this flag is set to true, the object is protected against deletion and overwrites. A common use case of this flag is regulatory investigations where objects need to be retained while the investigation is ongoing. Note that unlike event-based hold, temporary hold does not impact retention expiration time of an object.
  *   `time_created` (*type:* `DateTime.t()`) - The creation time of the object in RFC 3339 format.
  *   `time_deleted` (*type:* `DateTime.t()`) - The time at which the object became noncurrent in RFC 3339 format. Will be returned if and only if this version of the object has been deleted.
  *   `time_finalized` (*type:* `DateTime.t()`) - The time when the object was finalized.
  *   `time_storage_class_updated` (*type:* `DateTime.t()`) - The time at which the object's storage class was last changed. When the object is initially created, it will be set to timeCreated.
  *   `updated` (*type:* `DateTime.t()`) - The modification time of the object metadata in RFC 3339 format. Set initially to object creation time and then updated whenever any metadata of the object changes. This includes changes made by a requester, such as modifying custom metadata, as well as changes made by Cloud Storage on behalf of a requester, such as changing the storage class based on an Object Lifecycle Configuration.
  """

  alias Googly.CloudStorage.Decode

  defstruct [
    :acl,
    :bucket,
    :cache_control,
    :component_count,
    :content_disposition,
    :content_encoding,
    :content_language,
    :content_type,
    :contexts,
    :crc32c,
    :custom_time,
    :customer_encryption,
    :etag,
    :event_based_hold,
    :generation,
    :hard_delete_time,
    :id,
    :kind,
    :kms_key_name,
    :md5_hash,
    :media_link,
    :metadata,
    :metageneration,
    :name,
    :owner,
    :restore_token,
    :retention,
    :retention_expiration_time,
    :self_link,
    :size,
    :soft_delete_time,
    :storage_class,
    :temporary_hold,
    :time_created,
    :time_deleted,
    :time_finalized,
    :time_storage_class_updated,
    :updated
  ]

  @type t :: %__MODULE__{
          acl: list(Googly.CloudStorage.Model.ObjectAccessControl.t()) | nil,
          bucket: String.t() | nil,
          cache_control: String.t() | nil,
          component_count: integer() | nil,
          content_disposition: String.t() | nil,
          content_encoding: String.t() | nil,
          content_language: String.t() | nil,
          content_type: String.t() | nil,
          contexts: Googly.CloudStorage.Model.ObjectContexts.t() | nil,
          crc32c: String.t() | nil,
          custom_time: DateTime.t() | nil,
          customer_encryption: Googly.CloudStorage.Model.ObjectCustomerEncryption.t() | nil,
          etag: String.t() | nil,
          event_based_hold: boolean() | nil,
          generation: String.t() | nil,
          hard_delete_time: DateTime.t() | nil,
          id: String.t() | nil,
          kind: String.t() | nil,
          kms_key_name: String.t() | nil,
          md5_hash: String.t() | nil,
          media_link: String.t() | nil,
          metadata: map() | nil,
          metageneration: String.t() | nil,
          name: String.t() | nil,
          owner: Googly.CloudStorage.Model.ObjectOwner.t() | nil,
          restore_token: String.t() | nil,
          retention: Googly.CloudStorage.Model.ObjectRetention.t() | nil,
          retention_expiration_time: DateTime.t() | nil,
          self_link: String.t() | nil,
          size: String.t() | nil,
          soft_delete_time: DateTime.t() | nil,
          storage_class: String.t() | nil,
          temporary_hold: boolean() | nil,
          time_created: DateTime.t() | nil,
          time_deleted: DateTime.t() | nil,
          time_finalized: DateTime.t() | nil,
          time_storage_class_updated: DateTime.t() | nil,
          updated: DateTime.t() | nil
        }

  @wire %{
    cache_control: "cacheControl",
    component_count: "componentCount",
    content_disposition: "contentDisposition",
    content_encoding: "contentEncoding",
    content_language: "contentLanguage",
    content_type: "contentType",
    custom_time: "customTime",
    customer_encryption: "customerEncryption",
    event_based_hold: "eventBasedHold",
    hard_delete_time: "hardDeleteTime",
    kms_key_name: "kmsKeyName",
    md5_hash: "md5Hash",
    media_link: "mediaLink",
    restore_token: "restoreToken",
    retention_expiration_time: "retentionExpirationTime",
    self_link: "selfLink",
    soft_delete_time: "softDeleteTime",
    storage_class: "storageClass",
    temporary_hold: "temporaryHold",
    time_created: "timeCreated",
    time_deleted: "timeDeleted",
    time_finalized: "timeFinalized",
    time_storage_class_updated: "timeStorageClassUpdated"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      acl: Googly.CloudStorage.Model.ObjectAccessControl.decode(m["acl"]),
      bucket: m["bucket"],
      cache_control: m["cacheControl"],
      component_count: m["componentCount"],
      content_disposition: m["contentDisposition"],
      content_encoding: m["contentEncoding"],
      content_language: m["contentLanguage"],
      content_type: m["contentType"],
      contexts: Googly.CloudStorage.Model.ObjectContexts.decode(m["contexts"]),
      crc32c: m["crc32c"],
      custom_time: Decode.datetime(m["customTime"]),
      customer_encryption:
        Googly.CloudStorage.Model.ObjectCustomerEncryption.decode(m["customerEncryption"]),
      etag: m["etag"],
      event_based_hold: m["eventBasedHold"],
      generation: m["generation"],
      hard_delete_time: Decode.datetime(m["hardDeleteTime"]),
      id: m["id"],
      kind: m["kind"],
      kms_key_name: m["kmsKeyName"],
      md5_hash: m["md5Hash"],
      media_link: m["mediaLink"],
      metadata: m["metadata"],
      metageneration: m["metageneration"],
      name: m["name"],
      owner: Googly.CloudStorage.Model.ObjectOwner.decode(m["owner"]),
      restore_token: m["restoreToken"],
      retention: Googly.CloudStorage.Model.ObjectRetention.decode(m["retention"]),
      retention_expiration_time: Decode.datetime(m["retentionExpirationTime"]),
      self_link: m["selfLink"],
      size: m["size"],
      soft_delete_time: Decode.datetime(m["softDeleteTime"]),
      storage_class: m["storageClass"],
      temporary_hold: m["temporaryHold"],
      time_created: Decode.datetime(m["timeCreated"]),
      time_deleted: Decode.datetime(m["timeDeleted"]),
      time_finalized: Decode.datetime(m["timeFinalized"]),
      time_storage_class_updated: Decode.datetime(m["timeStorageClassUpdated"]),
      updated: Decode.datetime(m["updated"])
    }
  end
end
