# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.ObjectCustomContextPayload do
  @moduledoc """
  The payload of a single user-defined object context.

  ## Attributes

  *   `create_time` (*type:* `DateTime.t()`) - The time at which the object context was created in RFC 3339 format.
  *   `update_time` (*type:* `DateTime.t()`) - The time at which the object context was last updated in RFC 3339 format.
  *   `value` (*type:* `String.t()`) - The value of the object context.
  """

  alias Googly.CloudStorage.Decode

  defstruct [:create_time, :update_time, :value]

  @type t :: %__MODULE__{
          create_time: DateTime.t() | nil,
          update_time: DateTime.t() | nil,
          value: String.t() | nil
        }

  @wire %{create_time: "createTime", update_time: "updateTime"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      create_time: Decode.datetime(m["createTime"]),
      update_time: Decode.datetime(m["updateTime"]),
      value: m["value"]
    }
  end
end
