# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.ObjectCustomerEncryption do
  @moduledoc """
  Metadata of customer-supplied encryption key, if the object is encrypted by such a key.

  ## Attributes

  *   `encryption_algorithm` (*type:* `String.t()`) - The encryption algorithm.
  *   `key_sha256` (*type:* `String.t()`) - SHA256 hash value of the encryption key.
  """

  defstruct [:encryption_algorithm, :key_sha256]

  @type t :: %__MODULE__{
          encryption_algorithm: String.t() | nil,
          key_sha256: String.t() | nil
        }

  @wire %{encryption_algorithm: "encryptionAlgorithm", key_sha256: "keySha256"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      encryption_algorithm: m["encryptionAlgorithm"],
      key_sha256: m["keySha256"]
    }
  end
end
