# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.ObjectAccessControls do
  @moduledoc """
  An access-control list.

  ## Attributes

  *   `items` (*type:* `list(Googly.CloudStorage.Model.ObjectAccessControl.t())`) - The list of items.
  *   `kind` (*type:* `String.t()`) - The kind of item this is. For lists of object access control entries, this is always storage#objectAccessControls.
  """

  defstruct [:items, :kind]

  @type t :: %__MODULE__{
          items: list(Googly.CloudStorage.Model.ObjectAccessControl.t()) | nil,
          kind: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      items: Googly.CloudStorage.Model.ObjectAccessControl.decode(m["items"]),
      kind: m["kind"]
    }
  end
end
