# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.RelocateBucketRequest do
  @moduledoc """
  A Relocate Bucket request.

  ## Attributes

  *   `destination_custom_placement_config` (*type:* `Googly.CloudStorage.Model.RelocateBucketRequestDestinationCustomPlacementConfig.t()`) - The bucket's new custom placement configuration if relocating to a Custom Dual Region.
  *   `destination_kms_key_name` (*type:* `String.t()`) - Resource name of a Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key. If set, is used to encrypt all objects in the destination bucket.
  *   `destination_location` (*type:* `String.t()`) - The new location the bucket will be relocated to.
  *   `validate_only` (*type:* `boolean()`) - If true, validate the operation, but do not actually relocate the bucket.
  """

  defstruct [
    :destination_custom_placement_config,
    :destination_kms_key_name,
    :destination_location,
    :validate_only
  ]

  @type t :: %__MODULE__{
          destination_custom_placement_config:
            Googly.CloudStorage.Model.RelocateBucketRequestDestinationCustomPlacementConfig.t()
            | nil,
          destination_kms_key_name: String.t() | nil,
          destination_location: String.t() | nil,
          validate_only: boolean() | nil
        }

  @wire %{
    destination_custom_placement_config: "destinationCustomPlacementConfig",
    destination_kms_key_name: "destinationKmsKeyName",
    destination_location: "destinationLocation",
    validate_only: "validateOnly"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      destination_custom_placement_config:
        Googly.CloudStorage.Model.RelocateBucketRequestDestinationCustomPlacementConfig.decode(
          m["destinationCustomPlacementConfig"]
        ),
      destination_kms_key_name: m["destinationKmsKeyName"],
      destination_location: m["destinationLocation"],
      validate_only: m["validateOnly"]
    }
  end
end
