# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.RewriteResponse do
  @moduledoc """
  A rewrite response.

  ## Attributes

  *   `done` (*type:* `boolean()`) - true if the copy is finished; otherwise, false if the copy is in progress. This property is always present in the response.
  *   `kind` (*type:* `String.t()`) - The kind of item this is.
  *   `object_size` (*type:* `String.t()`) - The total size of the object being copied in bytes. This property is always present in the response.
  *   `resource` (*type:* `Googly.CloudStorage.Model.Object.t()`) - A resource containing the metadata for the copied-to object. This property is present in the response only when copying completes.
  *   `rewrite_token` (*type:* `String.t()`) - A token to use in subsequent requests to continue copying data. This token is present in the response only when there is more data to copy.
  *   `total_bytes_rewritten` (*type:* `String.t()`) - The total bytes written so far, which can be used to provide a waiting user with a progress indicator. This property is always present in the response.
  """

  defstruct [:done, :kind, :object_size, :resource, :rewrite_token, :total_bytes_rewritten]

  @type t :: %__MODULE__{
          done: boolean() | nil,
          kind: String.t() | nil,
          object_size: String.t() | nil,
          resource: Googly.CloudStorage.Model.Object.t() | nil,
          rewrite_token: String.t() | nil,
          total_bytes_rewritten: String.t() | nil
        }

  @wire %{
    object_size: "objectSize",
    rewrite_token: "rewriteToken",
    total_bytes_rewritten: "totalBytesRewritten"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      done: m["done"],
      kind: m["kind"],
      object_size: m["objectSize"],
      resource: Googly.CloudStorage.Model.Object.decode(m["resource"]),
      rewrite_token: m["rewriteToken"],
      total_bytes_rewritten: m["totalBytesRewritten"]
    }
  end
end
