# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Model.TestIamPermissionsResponse do
  @moduledoc """
  A storage.(buckets|objects|managedFolders).testIamPermissions response.

  ## Attributes

  *   `kind` (*type:* `String.t()`) - The kind of item this is.
  *   `permissions` (*type:* `list(String.t())`) - The permissions held by the caller. Permissions are always of the format storage.resource.capability, where resource is one of buckets, objects, or managedFolders. The supported permissions are as follows:  
      - storage.buckets.delete - Delete bucket.  
      - storage.buckets.get - Read bucket metadata.  
      - storage.buckets.getIamPolicy - Read bucket IAM policy.  
      - storage.buckets.create - Create bucket.  
      - storage.buckets.list - List buckets.  
      - storage.buckets.setIamPolicy - Update bucket IAM policy.  
      - storage.buckets.update - Update bucket metadata.  
      - storage.objects.delete - Delete object.  
      - storage.objects.get - Read object data and metadata.  
      - storage.objects.getIamPolicy - Read object IAM policy.  
      - storage.objects.create - Create object.  
      - storage.objects.list - List objects.  
      - storage.objects.setIamPolicy - Update object IAM policy.  
      - storage.objects.update - Update object metadata. 
      - storage.managedFolders.delete - Delete managed folder.  
      - storage.managedFolders.get - Read managed folder metadata.  
      - storage.managedFolders.getIamPolicy - Read managed folder IAM policy.  
      - storage.managedFolders.create - Create managed folder.  
      - storage.managedFolders.list - List managed folders.  
      - storage.managedFolders.setIamPolicy - Update managed folder IAM policy.
  """

  defstruct [:kind, :permissions]

  @type t :: %__MODULE__{
          kind: String.t() | nil,
          permissions: list(String.t()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      kind: m["kind"],
      permissions: m["permissions"]
    }
  end
end
