# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Channels do
  @moduledoc """
  Endpoints for the `Channels` resource.
  """

  alias Googly.CloudStorage.Request

  @doc """
  Stop watching resources through this channel

  ## Parameters

  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `body` (*type:* `Googly.CloudStorage.Model.Channel.t()`) - 

  ## Returns

  *   `{:ok, Req.Response.t()}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec stop(keyword()) :: {:ok, Req.Response.t()} | {:error, term()}
  def stop(opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/channels/stop",
      path_params: %{},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        body: {:body, nil}
      },
      decode: nil,
      opts: opts
    )
  end
end
