# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.AsyncBatchAnnotateImagesRequest do
  @moduledoc """
  Request for async image annotation for a list of images.

  ## Attributes

  *   `labels` (*type:* `map()`) - Optional. The labels with user-defined metadata for the request. Label keys and values can be no longer than 63 characters (Unicode codepoints), can only contain lowercase letters, numeric characters, underscores and dashes. International characters are allowed. Label values are optional. Label keys must start with a letter.
  *   `output_config` (*type:* `Googly.CloudVision.Model.OutputConfig.t()`) - Required. The desired output location and metadata (e.g. format).
  *   `parent` (*type:* `String.t()`) - Optional. Target project and location to make a call. Format: `projects/{project-id}/locations/{location-id}`. If no parent is specified, a region will be chosen automatically. Supported location-ids: `us`: USA country only, `asia`: East asia areas, like Japan, Taiwan, `eu`: The European Union. Example: `projects/project-A/locations/eu`.
  *   `requests` (*type:* `list(Googly.CloudVision.Model.AnnotateImageRequest.t())`) - Required. Individual image annotation requests for this batch.
  """

  defstruct [:labels, :output_config, :parent, :requests]

  @type t :: %__MODULE__{
          labels: map() | nil,
          output_config: Googly.CloudVision.Model.OutputConfig.t() | nil,
          parent: String.t() | nil,
          requests: list(Googly.CloudVision.Model.AnnotateImageRequest.t()) | nil
        }

  @wire %{output_config: "outputConfig"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      labels: m["labels"],
      output_config: Googly.CloudVision.Model.OutputConfig.decode(m["outputConfig"]),
      parent: m["parent"],
      requests: Googly.CloudVision.Model.AnnotateImageRequest.decode(m["requests"])
    }
  end
end
