# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.AsyncAnnotateFileRequest do
  @moduledoc """
  An offline file annotation request.

  ## Attributes

  *   `features` (*type:* `list(Googly.CloudVision.Model.Feature.t())`) - Required. Requested features.
  *   `image_context` (*type:* `Googly.CloudVision.Model.ImageContext.t()`) - Additional context that may accompany the image(s) in the file.
  *   `input_config` (*type:* `Googly.CloudVision.Model.InputConfig.t()`) - Required. Information about the input file.
  *   `output_config` (*type:* `Googly.CloudVision.Model.OutputConfig.t()`) - Required. The desired output location and metadata (e.g. format).
  """

  defstruct [:features, :image_context, :input_config, :output_config]

  @type t :: %__MODULE__{
          features: list(Googly.CloudVision.Model.Feature.t()) | nil,
          image_context: Googly.CloudVision.Model.ImageContext.t() | nil,
          input_config: Googly.CloudVision.Model.InputConfig.t() | nil,
          output_config: Googly.CloudVision.Model.OutputConfig.t() | nil
        }

  @wire %{
    image_context: "imageContext",
    input_config: "inputConfig",
    output_config: "outputConfig"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      features: Googly.CloudVision.Model.Feature.decode(m["features"]),
      image_context: Googly.CloudVision.Model.ImageContext.decode(m["imageContext"]),
      input_config: Googly.CloudVision.Model.InputConfig.decode(m["inputConfig"]),
      output_config: Googly.CloudVision.Model.OutputConfig.decode(m["outputConfig"])
    }
  end
end
