# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.BatchAnnotateFilesResponse do
  @moduledoc """
  A list of file annotation responses.

  ## Attributes

  *   `responses` (*type:* `list(Googly.CloudVision.Model.AnnotateFileResponse.t())`) - The list of file annotation responses, each response corresponding to each AnnotateFileRequest in BatchAnnotateFilesRequest.
  """

  defstruct [:responses]

  @type t :: %__MODULE__{
          responses: list(Googly.CloudVision.Model.AnnotateFileResponse.t()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      responses: Googly.CloudVision.Model.AnnotateFileResponse.decode(m["responses"])
    }
  end
end
