# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.BoundingPoly do
  @moduledoc """
  A bounding polygon for the detected image annotation.

  ## Attributes

  *   `normalized_vertices` (*type:* `list(Googly.CloudVision.Model.NormalizedVertex.t())`) - The bounding polygon normalized vertices.
  *   `vertices` (*type:* `list(Googly.CloudVision.Model.Vertex.t())`) - The bounding polygon vertices.
  """

  defstruct [:normalized_vertices, :vertices]

  @type t :: %__MODULE__{
          normalized_vertices: list(Googly.CloudVision.Model.NormalizedVertex.t()) | nil,
          vertices: list(Googly.CloudVision.Model.Vertex.t()) | nil
        }

  @wire %{normalized_vertices: "normalizedVertices"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      normalized_vertices:
        Googly.CloudVision.Model.NormalizedVertex.decode(m["normalizedVertices"]),
      vertices: Googly.CloudVision.Model.Vertex.decode(m["vertices"])
    }
  end
end
