# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ColorInfo do
  @moduledoc """
  Color information consists of RGB channels, score, and the fraction of the image that the color occupies in the image.

  ## Attributes

  *   `color` (*type:* `Googly.CloudVision.Model.Color.t()`) - RGB components of the color.
  *   `pixel_fraction` (*type:* `number()`) - The fraction of pixels the color occupies in the image. Value in range [0, 1].
  *   `score` (*type:* `number()`) - Image-specific score for this color. Value in range [0, 1].
  """

  defstruct [:color, :pixel_fraction, :score]

  @type t :: %__MODULE__{
          color: Googly.CloudVision.Model.Color.t() | nil,
          pixel_fraction: number() | nil,
          score: number() | nil
        }

  @wire %{pixel_fraction: "pixelFraction"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      color: Googly.CloudVision.Model.Color.decode(m["color"]),
      pixel_fraction: m["pixelFraction"],
      score: m["score"]
    }
  end
end
