# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.FaceAnnotation do
  @moduledoc """
  A face annotation object contains the results of face detection.

  ## Attributes

  *   `anger_likelihood` (*type:* `String.t()`) - Anger likelihood.
  *   `blurred_likelihood` (*type:* `String.t()`) - Blurred likelihood.
  *   `bounding_poly` (*type:* `Googly.CloudVision.Model.BoundingPoly.t()`) - The bounding polygon around the face. The coordinates of the bounding box are in the original image's scale. The bounding box is computed to "frame" the face in accordance with human expectations. It is based on the landmarker results. Note that one or more x and/or y coordinates may not be generated in the `BoundingPoly` (the polygon will be unbounded) if only a partial face appears in the image to be annotated.
  *   `detection_confidence` (*type:* `number()`) - Detection confidence. Range [0, 1].
  *   `fd_bounding_poly` (*type:* `Googly.CloudVision.Model.BoundingPoly.t()`) - The `fd_bounding_poly` bounding polygon is tighter than the `boundingPoly`, and encloses only the skin part of the face. Typically, it is used to eliminate the face from any image analysis that detects the "amount of skin" visible in an image. It is not based on the landmarker results, only on the initial face detection, hence the fd (face detection) prefix.
  *   `headwear_likelihood` (*type:* `String.t()`) - Headwear likelihood.
  *   `joy_likelihood` (*type:* `String.t()`) - Joy likelihood.
  *   `landmarking_confidence` (*type:* `number()`) - Face landmarking confidence. Range [0, 1].
  *   `landmarks` (*type:* `list(Googly.CloudVision.Model.Landmark.t())`) - Detected face landmarks.
  *   `pan_angle` (*type:* `number()`) - Yaw angle, which indicates the leftward/rightward angle that the face is pointing relative to the vertical plane perpendicular to the image. Range [-180,180].
  *   `roll_angle` (*type:* `number()`) - Roll angle, which indicates the amount of clockwise/anti-clockwise rotation of the face relative to the image vertical about the axis perpendicular to the face. Range [-180,180].
  *   `sorrow_likelihood` (*type:* `String.t()`) - Sorrow likelihood.
  *   `surprise_likelihood` (*type:* `String.t()`) - Surprise likelihood.
  *   `tilt_angle` (*type:* `number()`) - Pitch angle, which indicates the upwards/downwards angle that the face is pointing relative to the image's horizontal plane. Range [-180,180].
  *   `under_exposed_likelihood` (*type:* `String.t()`) - Under-exposed likelihood.
  """

  defstruct [
    :anger_likelihood,
    :blurred_likelihood,
    :bounding_poly,
    :detection_confidence,
    :fd_bounding_poly,
    :headwear_likelihood,
    :joy_likelihood,
    :landmarking_confidence,
    :landmarks,
    :pan_angle,
    :roll_angle,
    :sorrow_likelihood,
    :surprise_likelihood,
    :tilt_angle,
    :under_exposed_likelihood
  ]

  @type t :: %__MODULE__{
          anger_likelihood: String.t() | nil,
          blurred_likelihood: String.t() | nil,
          bounding_poly: Googly.CloudVision.Model.BoundingPoly.t() | nil,
          detection_confidence: number() | nil,
          fd_bounding_poly: Googly.CloudVision.Model.BoundingPoly.t() | nil,
          headwear_likelihood: String.t() | nil,
          joy_likelihood: String.t() | nil,
          landmarking_confidence: number() | nil,
          landmarks: list(Googly.CloudVision.Model.Landmark.t()) | nil,
          pan_angle: number() | nil,
          roll_angle: number() | nil,
          sorrow_likelihood: String.t() | nil,
          surprise_likelihood: String.t() | nil,
          tilt_angle: number() | nil,
          under_exposed_likelihood: String.t() | nil
        }

  @wire %{
    anger_likelihood: "angerLikelihood",
    blurred_likelihood: "blurredLikelihood",
    bounding_poly: "boundingPoly",
    detection_confidence: "detectionConfidence",
    fd_bounding_poly: "fdBoundingPoly",
    headwear_likelihood: "headwearLikelihood",
    joy_likelihood: "joyLikelihood",
    landmarking_confidence: "landmarkingConfidence",
    pan_angle: "panAngle",
    roll_angle: "rollAngle",
    sorrow_likelihood: "sorrowLikelihood",
    surprise_likelihood: "surpriseLikelihood",
    tilt_angle: "tiltAngle",
    under_exposed_likelihood: "underExposedLikelihood"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      anger_likelihood: m["angerLikelihood"],
      blurred_likelihood: m["blurredLikelihood"],
      bounding_poly: Googly.CloudVision.Model.BoundingPoly.decode(m["boundingPoly"]),
      detection_confidence: m["detectionConfidence"],
      fd_bounding_poly: Googly.CloudVision.Model.BoundingPoly.decode(m["fdBoundingPoly"]),
      headwear_likelihood: m["headwearLikelihood"],
      joy_likelihood: m["joyLikelihood"],
      landmarking_confidence: m["landmarkingConfidence"],
      landmarks: Googly.CloudVision.Model.Landmark.decode(m["landmarks"]),
      pan_angle: m["panAngle"],
      roll_angle: m["rollAngle"],
      sorrow_likelihood: m["sorrowLikelihood"],
      surprise_likelihood: m["surpriseLikelihood"],
      tilt_angle: m["tiltAngle"],
      under_exposed_likelihood: m["underExposedLikelihood"]
    }
  end
end
