# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1OutputConfig do
  @moduledoc """
  The desired output location and metadata.

  ## Attributes

  *   `batch_size` (*type:* `integer()`) - The max number of response protos to put into each output JSON file on Google Cloud Storage. The valid range is [1, 100]. If not specified, the default value is 20. For example, for one pdf file with 100 pages, 100 response protos will be generated. If `batch_size` = 20, then 5 json files each containing 20 response protos will be written under the prefix `gcs_destination`.`uri`. Currently, batch_size only applies to GcsDestination, with potential future support for other output configurations.
  *   `gcs_destination` (*type:* `Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1GcsDestination.t()`) - The Google Cloud Storage location to write the output(s) to.
  """

  defstruct [:batch_size, :gcs_destination]

  @type t :: %__MODULE__{
          batch_size: integer() | nil,
          gcs_destination:
            Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1GcsDestination.t() | nil
        }

  @wire %{batch_size: "batchSize", gcs_destination: "gcsDestination"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      batch_size: m["batchSize"],
      gcs_destination:
        Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1GcsDestination.decode(
          m["gcsDestination"]
        )
    }
  end
end
