# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p3beta1GcsSource do
  @moduledoc """
  The Google Cloud Storage location where the input will be read from.

  ## Attributes

  *   `uri` (*type:* `String.t()`) - Google Cloud Storage URI for the input file. This must only be a Google Cloud Storage object. Wildcards are not currently supported.
  """

  defstruct [:uri]

  @type t :: %__MODULE__{
          uri: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      uri: m["uri"]
    }
  end
end
