# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ImportProductSetsResponse do
  @moduledoc """
  Response message for the `ImportProductSets` method. This message is returned by the google.longrunning.Operations.GetOperation method in the returned google.longrunning.Operation.response field.

  ## Attributes

  *   `reference_images` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ReferenceImage.t())`) - The list of reference_images that are imported successfully.
  *   `statuses` (*type:* `list(Googly.CloudVision.Model.Status.t())`) - The rpc status for each ImportProductSet request, including both successes and errors. The number of statuses here matches the number of lines in the csv file, and statuses[i] stores the success or failure status of processing the i-th line of the csv, starting from line 0.
  """

  defstruct [:reference_images, :statuses]

  @type t :: %__MODULE__{
          reference_images:
            list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ReferenceImage.t()) | nil,
          statuses: list(Googly.CloudVision.Model.Status.t()) | nil
        }

  @wire %{reference_images: "referenceImages"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      reference_images:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ReferenceImage.decode(
          m["referenceImages"]
        ),
      statuses: Googly.CloudVision.Model.Status.decode(m["statuses"])
    }
  end
end
