# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1DominantColorsAnnotation do
  @moduledoc """
  Set of dominant colors and their corresponding scores.

  ## Attributes

  *   `colors` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ColorInfo.t())`) - RGB color values with their score and pixel fraction.
  """

  defstruct [:colors]

  @type t :: %__MODULE__{
          colors: list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ColorInfo.t()) | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      colors: Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ColorInfo.decode(m["colors"])
    }
  end
end
