# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1CropHintsAnnotation do
  @moduledoc """
  Set of crop hints that are used to generate new crops when serving images.

  ## Attributes

  *   `crop_hints` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1CropHint.t())`) - Crop hint results.
  """

  defstruct [:crop_hints]

  @type t :: %__MODULE__{
          crop_hints: list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1CropHint.t()) | nil
        }

  @wire %{crop_hints: "cropHints"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      crop_hints:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1CropHint.decode(m["cropHints"])
    }
  end
end
