# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1EntityAnnotation do
  @moduledoc """
  Set of detected entity features.

  ## Attributes

  *   `bounding_poly` (*type:* `Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1BoundingPoly.t()`) - Image region to which this entity belongs. Not produced for `LABEL_DETECTION` features.
  *   `confidence` (*type:* `number()`) - **Deprecated. Use `score` instead.** The accuracy of the entity detection in an image. For example, for an image in which the "Eiffel Tower" entity is detected, this field represents the confidence that there is a tower in the query image. Range [0, 1].
  *   `description` (*type:* `String.t()`) - Entity textual description, expressed in its `locale` language.
  *   `locale` (*type:* `String.t()`) - The language code for the locale in which the entity textual `description` is expressed.
  *   `locations` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1LocationInfo.t())`) - The location information for the detected entity. Multiple `LocationInfo` elements can be present because one location may indicate the location of the scene in the image, and another location may indicate the location of the place where the image was taken. Location information is usually present for landmarks.
  *   `mid` (*type:* `String.t()`) - Opaque entity ID. Some IDs may be available in [Google Knowledge Graph Search API](https://developers.google.com/knowledge-graph/).
  *   `properties` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1Property.t())`) - Some entities may have optional user-supplied `Property` (name/value) fields, such a score or string that qualifies the entity.
  *   `score` (*type:* `number()`) - Overall score of the result. Range [0, 1].
  *   `topicality` (*type:* `number()`) - The relevancy of the ICA (Image Content Annotation) label to the image. For example, the relevancy of "tower" is likely higher to an image containing the detected "Eiffel Tower" than to an image containing a detected distant towering building, even though the confidence that there is a tower in each image may be the same. Range [0, 1].
  """

  defstruct [
    :bounding_poly,
    :confidence,
    :description,
    :locale,
    :locations,
    :mid,
    :properties,
    :score,
    :topicality
  ]

  @type t :: %__MODULE__{
          bounding_poly:
            Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1BoundingPoly.t() | nil,
          confidence: number() | nil,
          description: String.t() | nil,
          locale: String.t() | nil,
          locations:
            list(Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1LocationInfo.t()) | nil,
          mid: String.t() | nil,
          properties: list(Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1Property.t()) | nil,
          score: number() | nil,
          topicality: number() | nil
        }

  @wire %{bounding_poly: "boundingPoly"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bounding_poly:
        Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1BoundingPoly.decode(m["boundingPoly"]),
      confidence: m["confidence"],
      description: m["description"],
      locale: m["locale"],
      locations:
        Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1LocationInfo.decode(m["locations"]),
      mid: m["mid"],
      properties:
        Googly.CloudVision.Model.GoogleCloudVisionV1p1beta1Property.decode(m["properties"]),
      score: m["score"],
      topicality: m["topicality"]
    }
  end
end
