# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AsyncBatchAnnotateImagesResponse do
  @moduledoc """
  Response to an async batch image annotation request.

  ## Attributes

  *   `output_config` (*type:* `Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1OutputConfig.t()`) - The output location and metadata from AsyncBatchAnnotateImagesRequest.
  """

  defstruct [:output_config]

  @type t :: %__MODULE__{
          output_config: Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1OutputConfig.t() | nil
        }

  @wire %{output_config: "outputConfig"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      output_config:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1OutputConfig.decode(m["outputConfig"])
    }
  end
end
