# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1LocationInfo do
  @moduledoc """
  Detected entity location information.

  ## Attributes

  *   `lat_lng` (*type:* `Googly.CloudVision.Model.LatLng.t()`) - lat/long location coordinates.
  """

  defstruct [:lat_lng]

  @type t :: %__MODULE__{
          lat_lng: Googly.CloudVision.Model.LatLng.t() | nil
        }

  @wire %{lat_lng: "latLng"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      lat_lng: Googly.CloudVision.Model.LatLng.decode(m["latLng"])
    }
  end
end
