# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1ProductKeyValue do
  @moduledoc """
  A product label represented as a key-value pair.

  ## Attributes

  *   `key` (*type:* `String.t()`) - The key of the label attached to the product. Cannot be empty and cannot exceed 128 bytes.
  *   `value` (*type:* `String.t()`) - The value of the label attached to the product. Cannot be empty and cannot exceed 128 bytes.
  """

  defstruct [:key, :value]

  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      key: m["key"],
      value: m["value"]
    }
  end
end
