# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1Symbol do
  @moduledoc """
  A single symbol representation.

  ## Attributes

  *   `bounding_box` (*type:* `Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1BoundingPoly.t()`) - The bounding box for the symbol. The vertices are in the order of top-left, top-right, bottom-right, bottom-left. When a rotation of the bounding box is detected the rotation is represented as around the top-left corner as defined when the text is read in the 'natural' orientation. For example: * when the text is horizontal it might look like: 0----1 | | 3----2 * when it's rotated 180 degrees around the top-left corner it becomes: 2----3 | | 1----0 and the vertex order will still be (0, 1, 2, 3).
  *   `confidence` (*type:* `number()`) - Confidence of the OCR results for the symbol. Range [0, 1].
  *   `property` (*type:* `Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1TextAnnotationTextProperty.t()`) - Additional information detected for the symbol.
  *   `text` (*type:* `String.t()`) - The actual UTF-8 representation of the symbol.
  """

  defstruct [:bounding_box, :confidence, :property, :text]

  @type t :: %__MODULE__{
          bounding_box: Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1BoundingPoly.t() | nil,
          confidence: number() | nil,
          property:
            Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1TextAnnotationTextProperty.t()
            | nil,
          text: String.t() | nil
        }

  @wire %{bounding_box: "boundingBox"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bounding_box:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1BoundingPoly.decode(m["boundingBox"]),
      confidence: m["confidence"],
      property:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1TextAnnotationTextProperty.decode(
          m["property"]
        ),
      text: m["text"]
    }
  end
end
