# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1TextAnnotationDetectedBreak do
  @moduledoc """
  Detected start or end of a structural component.

  ## Attributes

  *   `is_prefix` (*type:* `boolean()`) - True if break prepends the element.
  *   `type` (*type:* `String.t()`) - Detected break type.
  """

  defstruct [:is_prefix, :type]

  @type t :: %__MODULE__{
          is_prefix: boolean() | nil,
          type: String.t() | nil
        }

  @wire %{is_prefix: "isPrefix"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      is_prefix: m["isPrefix"],
      type: m["type"]
    }
  end
end
