# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AsyncBatchAnnotateFilesResponse do
  @moduledoc """
  Response to an async batch file annotation request.

  ## Attributes

  *   `responses` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AsyncAnnotateFileResponse.t())`) - The list of file annotation responses, one for each request in AsyncBatchAnnotateFilesRequest.
  """

  defstruct [:responses]

  @type t :: %__MODULE__{
          responses:
            list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AsyncAnnotateFileResponse.t())
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      responses:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AsyncAnnotateFileResponse.decode(
          m["responses"]
        )
    }
  end
end
