# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationTextProperty do
  @moduledoc """
  Additional information detected on the structural component.

  ## Attributes

  *   `detected_break` (*type:* `Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationDetectedBreak.t()`) - Detected start or end of a text segment.
  *   `detected_languages` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationDetectedLanguage.t())`) - A list of detected languages together with confidence.
  """

  defstruct [:detected_break, :detected_languages]

  @type t :: %__MODULE__{
          detected_break:
            Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationDetectedBreak.t()
            | nil,
          detected_languages:
            list(
              Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationDetectedLanguage.t()
            )
            | nil
        }

  @wire %{detected_break: "detectedBreak", detected_languages: "detectedLanguages"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      detected_break:
        Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationDetectedBreak.decode(
          m["detectedBreak"]
        ),
      detected_languages:
        Googly.CloudVision.Model.GoogleCloudVisionV1p2beta1TextAnnotationDetectedLanguage.decode(
          m["detectedLanguages"]
        )
    }
  end
end
