# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1BatchAnnotateFilesResponse do
  @moduledoc """
  A list of file annotation responses.

  ## Attributes

  *   `responses` (*type:* `list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AnnotateFileResponse.t())`) - The list of file annotation responses, each response corresponding to each AnnotateFileRequest in BatchAnnotateFilesRequest.
  """

  defstruct [:responses]

  @type t :: %__MODULE__{
          responses:
            list(Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AnnotateFileResponse.t())
            | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      responses:
        Googly.CloudVision.Model.GoogleCloudVisionV1p4beta1AnnotateFileResponse.decode(
          m["responses"]
        )
    }
  end
end
