# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ImageSource do
  @moduledoc """
  External image source (Google Cloud Storage or web URL image location).

  ## Attributes

  *   `gcs_image_uri` (*type:* `String.t()`) - **Use `image_uri` instead.** The Google Cloud Storage URI of the form `gs://bucket_name/object_name`. Object versioning is not supported. See [Google Cloud Storage Request URIs](https://cloud.google.com/storage/docs/reference-uris) for more info.
  *   `image_uri` (*type:* `String.t()`) - The URI of the source image. Can be either: 1. A Google Cloud Storage URI of the form `gs://bucket_name/object_name`. Object versioning is not supported. See [Google Cloud Storage Request URIs](https://cloud.google.com/storage/docs/reference-uris) for more info. 2. A publicly-accessible image HTTP/HTTPS URL. When fetching images from HTTP/HTTPS URLs, Google cannot guarantee that the request will be completed. Your request may fail if the specified host denies the request (e.g. due to request throttling or DOS prevention), or if Google throttles requests to the site for abuse prevention. You should not depend on externally-hosted images for production applications. When both `gcs_image_uri` and `image_uri` are specified, `image_uri` takes precedence.
  """

  defstruct [:gcs_image_uri, :image_uri]

  @type t :: %__MODULE__{
          gcs_image_uri: String.t() | nil,
          image_uri: String.t() | nil
        }

  @wire %{gcs_image_uri: "gcsImageUri", image_uri: "imageUri"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      gcs_image_uri: m["gcsImageUri"],
      image_uri: m["imageUri"]
    }
  end
end
