# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ImportProductSetsRequest do
  @moduledoc """
  Request message for the `ImportProductSets` method.

  ## Attributes

  *   `input_config` (*type:* `Googly.CloudVision.Model.ImportProductSetsInputConfig.t()`) - Required. The input content for the list of requests.
  """

  defstruct [:input_config]

  @type t :: %__MODULE__{
          input_config: Googly.CloudVision.Model.ImportProductSetsInputConfig.t() | nil
        }

  @wire %{input_config: "inputConfig"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      input_config: Googly.CloudVision.Model.ImportProductSetsInputConfig.decode(m["inputConfig"])
    }
  end
end
