# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ImportProductSetsInputConfig do
  @moduledoc """
  The input content for the `ImportProductSets` method.

  ## Attributes

  *   `gcs_source` (*type:* `Googly.CloudVision.Model.ImportProductSetsGcsSource.t()`) - The Google Cloud Storage location for a csv file which preserves a list of ImportProductSetRequests in each line.
  """

  defstruct [:gcs_source]

  @type t :: %__MODULE__{
          gcs_source: Googly.CloudVision.Model.ImportProductSetsGcsSource.t() | nil
        }

  @wire %{gcs_source: "gcsSource"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      gcs_source: Googly.CloudVision.Model.ImportProductSetsGcsSource.decode(m["gcsSource"])
    }
  end
end
