# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ListProductSetsResponse do
  @moduledoc """
  Response message for the `ListProductSets` method.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - Token to retrieve the next page of results, or empty if there are no more results in the list.
  *   `product_sets` (*type:* `list(Googly.CloudVision.Model.ProductSet.t())`) - List of ProductSets.
  """

  defstruct [:next_page_token, :product_sets]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          product_sets: list(Googly.CloudVision.Model.ProductSet.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken", product_sets: "productSets"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      product_sets: Googly.CloudVision.Model.ProductSet.decode(m["productSets"])
    }
  end
end
