# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ListReferenceImagesResponse do
  @moduledoc """
  Response message for the `ListReferenceImages` method.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - The next_page_token returned from a previous List request, if any.
  *   `page_size` (*type:* `integer()`) - The maximum number of items to return. Default 10, maximum 100.
  *   `reference_images` (*type:* `list(Googly.CloudVision.Model.ReferenceImage.t())`) - The list of reference images.
  """

  defstruct [:next_page_token, :page_size, :reference_images]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          page_size: integer() | nil,
          reference_images: list(Googly.CloudVision.Model.ReferenceImage.t()) | nil
        }

  @wire %{
    next_page_token: "nextPageToken",
    page_size: "pageSize",
    reference_images: "referenceImages"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      page_size: m["pageSize"],
      reference_images: Googly.CloudVision.Model.ReferenceImage.decode(m["referenceImages"])
    }
  end
end
