# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ListProductsInProductSetResponse do
  @moduledoc """
  Response message for the `ListProductsInProductSet` method.

  ## Attributes

  *   `next_page_token` (*type:* `String.t()`) - Token to retrieve the next page of results, or empty if there are no more results in the list.
  *   `products` (*type:* `list(Googly.CloudVision.Model.Product.t())`) - The list of Products.
  """

  defstruct [:next_page_token, :products]

  @type t :: %__MODULE__{
          next_page_token: String.t() | nil,
          products: list(Googly.CloudVision.Model.Product.t()) | nil
        }

  @wire %{next_page_token: "nextPageToken"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      next_page_token: m["nextPageToken"],
      products: Googly.CloudVision.Model.Product.decode(m["products"])
    }
  end
end
