# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.Paragraph do
  @moduledoc """
  Structural unit of text representing a number of words in certain order.

  ## Attributes

  *   `bounding_box` (*type:* `Googly.CloudVision.Model.BoundingPoly.t()`) - The bounding box for the paragraph. The vertices are in the order of top-left, top-right, bottom-right, bottom-left. When a rotation of the bounding box is detected the rotation is represented as around the top-left corner as defined when the text is read in the 'natural' orientation. For example: * when the text is horizontal it might look like: 0----1 | | 3----2 * when it's rotated 180 degrees around the top-left corner it becomes: 2----3 | | 1----0 and the vertex order will still be (0, 1, 2, 3).
  *   `confidence` (*type:* `number()`) - Confidence of the OCR results for the paragraph. Range [0, 1].
  *   `property` (*type:* `Googly.CloudVision.Model.TextProperty.t()`) - Additional information detected for the paragraph.
  *   `words` (*type:* `list(Googly.CloudVision.Model.Word.t())`) - List of all words in this paragraph.
  """

  defstruct [:bounding_box, :confidence, :property, :words]

  @type t :: %__MODULE__{
          bounding_box: Googly.CloudVision.Model.BoundingPoly.t() | nil,
          confidence: number() | nil,
          property: Googly.CloudVision.Model.TextProperty.t() | nil,
          words: list(Googly.CloudVision.Model.Word.t()) | nil
        }

  @wire %{bounding_box: "boundingBox"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bounding_box: Googly.CloudVision.Model.BoundingPoly.decode(m["boundingBox"]),
      confidence: m["confidence"],
      property: Googly.CloudVision.Model.TextProperty.decode(m["property"]),
      words: Googly.CloudVision.Model.Word.decode(m["words"])
    }
  end
end
