# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ProductSet do
  @moduledoc """
  A ProductSet contains Products. A ProductSet can contain a maximum of 1 million reference images. If the limit is exceeded, periodic indexing will fail.

  ## Attributes

  *   `display_name` (*type:* `String.t()`) - The user-provided name for this ProductSet. Must not be empty. Must be at most 4096 characters long.
  *   `index_error` (*type:* `Googly.CloudVision.Model.Status.t()`) - Output only. If there was an error with indexing the product set, the field is populated. This field is ignored when creating a ProductSet.
  *   `index_time` (*type:* `DateTime.t()`) - Output only. The time at which this ProductSet was last indexed. Query results will reflect all updates before this time. If this ProductSet has never been indexed, this timestamp is the default value "1970-01-01T00:00:00Z". This field is ignored when creating a ProductSet.
  *   `name` (*type:* `String.t()`) - The resource name of the ProductSet. Format is: `projects/PROJECT_ID/locations/LOC_ID/productSets/PRODUCT_SET_ID`. This field is ignored when creating a ProductSet.
  """

  alias Googly.CloudVision.Decode

  defstruct [:display_name, :index_error, :index_time, :name]

  @type t :: %__MODULE__{
          display_name: String.t() | nil,
          index_error: Googly.CloudVision.Model.Status.t() | nil,
          index_time: DateTime.t() | nil,
          name: String.t() | nil
        }

  @wire %{display_name: "displayName", index_error: "indexError", index_time: "indexTime"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      display_name: m["displayName"],
      index_error: Googly.CloudVision.Model.Status.decode(m["indexError"]),
      index_time: Decode.datetime(m["indexTime"]),
      name: m["name"]
    }
  end
end
