# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ProductSetPurgeConfig do
  @moduledoc """
  Config to control which ProductSet contains the Products to be deleted.

  ## Attributes

  *   `product_set_id` (*type:* `String.t()`) - The ProductSet that contains the Products to delete. If a Product is a member of product_set_id in addition to other ProductSets, the Product will still be deleted.
  """

  defstruct [:product_set_id]

  @type t :: %__MODULE__{
          product_set_id: String.t() | nil
        }

  @wire %{product_set_id: "productSetId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      product_set_id: m["productSetId"]
    }
  end
end
