# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.ProductSearchParams do
  @moduledoc """
  Parameters for a product search request.

  ## Attributes

  *   `bounding_poly` (*type:* `Googly.CloudVision.Model.BoundingPoly.t()`) - The bounding polygon around the area of interest in the image. If it is not specified, system discretion will be applied.
  *   `filter` (*type:* `String.t()`) - The filtering expression. This can be used to restrict search results based on Product labels. We currently support an AND of OR of key-value expressions, where each expression within an OR must have the same key. An '=' should be used to connect the key and value. For example, "(color = red OR color = blue) AND brand = Google" is acceptable, but "(color = red OR brand = Google)" is not acceptable. "color: red" is not acceptable because it uses a ':' instead of an '='.
  *   `product_categories` (*type:* `list(String.t())`) - The list of product categories to search in. Currently, we only consider the first category, and either "homegoods-v2", "apparel-v2", "toys-v2", "packagedgoods-v1", or "general-v1" should be specified. The legacy categories "homegoods", "apparel", and "toys" are still supported but will be deprecated. For new products, please use "homegoods-v2", "apparel-v2", or "toys-v2" for better product search accuracy. It is recommended to migrate existing products to these categories as well.
  *   `product_set` (*type:* `String.t()`) - The resource name of a ProductSet to be searched for similar images. Format is: `projects/PROJECT_ID/locations/LOC_ID/productSets/PRODUCT_SET_ID`.
  """

  defstruct [:bounding_poly, :filter, :product_categories, :product_set]

  @type t :: %__MODULE__{
          bounding_poly: Googly.CloudVision.Model.BoundingPoly.t() | nil,
          filter: String.t() | nil,
          product_categories: list(String.t()) | nil,
          product_set: String.t() | nil
        }

  @wire %{
    bounding_poly: "boundingPoly",
    product_categories: "productCategories",
    product_set: "productSet"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      bounding_poly: Googly.CloudVision.Model.BoundingPoly.decode(m["boundingPoly"]),
      filter: m["filter"],
      product_categories: m["productCategories"],
      product_set: m["productSet"]
    }
  end
end
