# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.PurgeProductsRequest do
  @moduledoc """
  Request message for the `PurgeProducts` method.

  ## Attributes

  *   `delete_orphan_products` (*type:* `boolean()`) - If delete_orphan_products is true, all Products that are not in any ProductSet will be deleted.
  *   `force` (*type:* `boolean()`) - The default value is false. Override this value to true to actually perform the purge.
  *   `product_set_purge_config` (*type:* `Googly.CloudVision.Model.ProductSetPurgeConfig.t()`) - Specify which ProductSet contains the Products to be deleted.
  """

  defstruct [:delete_orphan_products, :force, :product_set_purge_config]

  @type t :: %__MODULE__{
          delete_orphan_products: boolean() | nil,
          force: boolean() | nil,
          product_set_purge_config: Googly.CloudVision.Model.ProductSetPurgeConfig.t() | nil
        }

  @wire %{
    delete_orphan_products: "deleteOrphanProducts",
    product_set_purge_config: "productSetPurgeConfig"
  }
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      delete_orphan_products: m["deleteOrphanProducts"],
      force: m["force"],
      product_set_purge_config:
        Googly.CloudVision.Model.ProductSetPurgeConfig.decode(m["productSetPurgeConfig"])
    }
  end
end
