# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.RemoveProductFromProductSetRequest do
  @moduledoc """
  Request message for the `RemoveProductFromProductSet` method.

  ## Attributes

  *   `product` (*type:* `String.t()`) - Required. The resource name for the Product to be removed from this ProductSet. Format is: `projects/PROJECT_ID/locations/LOC_ID/products/PRODUCT_ID`
  """

  defstruct [:product]

  @type t :: %__MODULE__{
          product: String.t() | nil
        }

  @wire %{}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      product: m["product"]
    }
  end
end
