# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.TextProperty do
  @moduledoc """
  Additional information detected on the structural component.

  ## Attributes

  *   `detected_break` (*type:* `Googly.CloudVision.Model.DetectedBreak.t()`) - Detected start or end of a text segment.
  *   `detected_languages` (*type:* `list(Googly.CloudVision.Model.DetectedLanguage.t())`) - A list of detected languages together with confidence.
  """

  defstruct [:detected_break, :detected_languages]

  @type t :: %__MODULE__{
          detected_break: Googly.CloudVision.Model.DetectedBreak.t() | nil,
          detected_languages: list(Googly.CloudVision.Model.DetectedLanguage.t()) | nil
        }

  @wire %{detected_break: "detectedBreak", detected_languages: "detectedLanguages"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      detected_break: Googly.CloudVision.Model.DetectedBreak.decode(m["detectedBreak"]),
      detected_languages: Googly.CloudVision.Model.DetectedLanguage.decode(m["detectedLanguages"])
    }
  end
end
