# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.WebDetectionParams do
  @moduledoc """
  Parameters for web detection request.

  ## Attributes

  *   `include_geo_results` (*type:* `boolean()`) - This field has no effect on results.
  """

  defstruct [:include_geo_results]

  @type t :: %__MODULE__{
          include_geo_results: boolean() | nil
        }

  @wire %{include_geo_results: "includeGeoResults"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      include_geo_results: m["includeGeoResults"]
    }
  end
end
