# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudVision.Model.WebEntity do
  @moduledoc """
  Entity deduced from similar images on the Internet.

  ## Attributes

  *   `description` (*type:* `String.t()`) - Canonical description of the entity, in English.
  *   `entity_id` (*type:* `String.t()`) - Opaque entity ID.
  *   `score` (*type:* `number()`) - Overall relevancy score for the entity. Not normalized and not comparable across different image queries.
  """

  defstruct [:description, :entity_id, :score]

  @type t :: %__MODULE__{
          description: String.t() | nil,
          entity_id: String.t() | nil,
          score: number() | nil
        }

  @wire %{entity_id: "entityId"}
  @doc false
  def __wire__, do: @wire

  @doc false
  def decode(nil), do: nil
  def decode(list) when is_list(list), do: Enum.map(list, &decode/1)

  def decode(m) do
    %__MODULE__{
      description: m["description"],
      entity_id: m["entityId"],
      score: m["score"]
    }
  end
end
